import {z} from 'zod';

const id=z.uuid(),at=z.iso.datetime(),label=z.string().min(1).max(160),unit=z.number().int().min(0).max(1000);
export const behaviorRulesVersion='npc-behavior-v1';
export const behaviorActions=['speak','travel','message','call','work','socialize','share','care','offer','breakup','withdraw','domain','crime','scene'] as const;
export const featureNames=['G','N','V','O','S','R','E','P'] as const;
export const behaviorFeaturesSchema=z.strictObject({G:unit,N:unit,V:unit,O:unit,S:unit,R:unit,E:unit,P:unit});
export const defaultBehaviorWeights={G:250,N:150,V:150,O:100,S:100,R:-150,E:-50,P:-50};
const weight=z.number().int().min(-1000).max(1000);
export const behaviorWeightsSchema=z.strictObject({G:weight,N:weight,V:weight,O:weight,S:weight,R:weight,E:weight,P:weight}).refine(w=>Object.values(w).reduce((n,v)=>n+Math.abs(v),0)===1000,'Absolute weights must sum to 1000').refine(w=>w.R<=0&&w.E<=0&&w.P<=0,'Costs must be nonpositive');
export const traitNames=['caution','sociability','assertiveness','patience','curiosity','orderliness','persistence'] as const;
export const valueNames=['honesty','loyalty','privacy','fairness','duty','autonomy','status','security'] as const;
const traitValues=z.partialRecord(z.enum(traitNames),unit),valueValues=z.partialRecord(z.enum(valueNames),unit);
export const behaviorPolicySchema=z.strictObject({
 version:z.literal(behaviorRulesVersion).default(behaviorRulesVersion),weights:behaviorWeightsSchema.default(defaultBehaviorWeights),
 variation:z.strictObject({enabled:z.boolean().default(false),band:unit.default(20)}).default({enabled:false,band:20}),
 optionalCandidateCap:z.number().int().min(1).max(12).default(12),switchMargin:unit.default(50),
 waitSeconds:z.number().int().min(1).max(3600).default(60),socialCooldownSeconds:z.number().int().min(30).max(86400).default(30),refusalCooldownSeconds:z.number().int().min(300).max(86400).default(300),
 recoveryPerSecond:z.strictObject({emotion:unit, mood:unit,stress:unit}).default({emotion:1,mood:0,stress:1}),
 threatEnter:unit.default(700),threatExit:unit.default(500),conflictDwellSeconds:z.number().int().min(0).max(3600).default(30),
 unknownRisk:unit.default(500),maxUnchangedFailures:z.literal(3).default(3),
}).refine(p=>p.threatEnter-p.threatExit>=100,'Threat hysteresis requires a gap of at least 100');
const anchor=z.strictObject({id:label,kind:z.enum(['HARD','SOFT','DESCRIPTIVE']),action:z.enum(behaviorActions).nullable().default(null),allow:z.boolean().default(false),priority:z.number().int().min(0).max(100).default(0),text:z.string().max(2000).default('')});
const preference=z.strictObject({planId:id,goalId:id.nullable().default(null),value:z.enum(valueNames).nullable().default(null),features:behaviorFeaturesSchema,sourceIds:z.array(id).max(32).default([]),mandatory:z.boolean().default(false)});
export const npcProfileSchema=z.strictObject({
 actorId:id,version:label,origin:z.enum(['CUSTOM','GENERATED','PROMOTED']).default('CUSTOM'),templateRef:label.nullable().default(null),generationSeed:label.nullable().default(null),
 planner:z.strictObject({enabled:z.boolean().default(false),provider:z.string().max(80).default('grounded')}).default({enabled:false,provider:'grounded'}),
 providerActions:z.array(z.strictObject({planId:id,action:z.json(),durationSeconds:z.number().int().min(1).max(86400),resourceIds:z.array(id).max(16).default([]),reservationSeconds:z.number().int().min(1).max(3600).default(300),violence:z.enum(['none','defense','force','severe']).default('none'),causeKinds:z.array(label).max(16).default([])})).max(100).default([]),
 routines:z.array(z.strictObject({id:label,planIds:z.array(id).min(1).max(3)})).max(32).default([]),
 biases:z.array(z.strictObject({id:label,attribute:z.enum(['tags','occupation','identity.orientation','identity.gender']),equals:label,action:z.enum(behaviorActions),feature:z.enum(featureNames),delta:z.number().int().min(-100).max(100),rationale:z.string().min(1).max(2000),approval:z.literal('APPROVED'),sourceEventId:id})).max(32).default([]),
 cooldownBypasses:z.array(z.strictObject({id:label,planId:id,observationKind:label})).max(32).default([]),
 milestones:z.array(z.strictObject({id:label,trait:z.enum(traitNames),delta:z.number().int().min(-250).max(250),requiredGoalIds:z.array(id).min(1).max(16),minimumEvidence:z.number().int().min(1).max(100).default(3)})).max(32).default([]),
 developments:z.array(z.strictObject({id:label,trait:z.enum(traitNames),observationKind:label,delta:z.number().int().min(-20).max(20),minimumEvidence:z.number().int().min(3).max(100).default(3)})).max(32).default([]),
 traits:traitValues.default({}),values:valueValues.default({}),anchors:z.array(anchor).max(64).default([]),
 motives:z.array(z.strictObject({id:label,description:z.string().max(2000)})).max(32).default([]),
 fears:z.array(z.strictObject({id:label,observationKind:label,intensity:unit})).max(32).default([]),
 loyalties:z.array(z.strictObject({id:label,targetId:id.nullable().default(null),motiveRef:label.nullable().default(null),importance:unit})).max(32).default([]),
 needResponses:z.array(z.strictObject({need:z.enum(['hunger','thirst','fatigue','pain','hygiene']),planId:id,sensitivity:unit})).max(32).default([]),
 boundaryPolicies:z.array(z.strictObject({id:label,action:z.enum(behaviorActions),targetId:id.nullable().default(null),permission:z.enum(['allow','refuse']),expiresAt:at.nullable().default(null),reason:z.string().min(1).max(1000)})).max(64).default([]),
 appraisals:z.array(z.strictObject({id:label,observationKind:label,emotion:label,intensity:unit,stress:unit,mood:unit})).max(32).default([]),
 habits:z.array(z.strictObject({id:label,planId:id,cue:z.enum(['routine','question','threat','promise']),fit:unit})).max(32).default([]),
 allowedActions:z.array(z.enum(behaviorActions)).max(behaviorActions.length).default(behaviorActions.filter(a=>a!=='crime')),
 disclosureLocks:z.array(id).max(100).default([]),preferences:z.array(preference).max(100).default([]),
 speechActs:z.array(z.strictObject({planId:id,intent:z.enum(['greet','ask','inform','refuse','warn','offer','promise','apologize','withdraw']),topic:label,claimEntryIds:z.array(id).max(16).default([]),commitmentIds:z.array(id).max(16).default([]),speakerBelief:z.enum(['believes-true','believes-false','uncertain']).default('uncertain'),certainty:unit.default(500),maximumEscalation:z.enum(['none','assertive','warning']).default('none')})).max(100).default([]),
 // Voice, consent, physiological needs, roles and task progress remain with their owners.
 voiceProfileRef:z.literal('character.voiceProfile').default('character.voiceProfile'),
 policy:behaviorPolicySchema.default(()=>behaviorPolicySchema.parse({})),
 adaptation:z.strictObject({unlocked:z.array(z.enum(traitNames)).max(7).default([]),dailyCap:z.number().int().min(0).max(20).default(20),baselineCap:z.number().int().min(0).max(100).default(100),minimumEvidence:z.number().int().min(2).max(100).default(3)}).default({unlocked:[],dailyCap:20,baselineCap:100,minimumEvidence:3}),
});
export const behaviorGoalSchema=z.strictObject({id,actorId:id,motiveRef:label,planId:id,predicate:z.enum(['attempt-completed','arrived','task-completed','delivered']).default('attempt-completed'),priority:unit,status:z.enum(['PROPOSED','ACTIVE','SUSPENDED','SATISFIED','FAILED','ABANDONED','EXPIRED']).default('PROPOSED'),dependencyGoalIds:z.array(id).max(16).default([]),createdByEventId:id,deadline:at.nullable().default(null),evidenceEventIds:z.array(id).max(100).default([]),suspensionReason:z.string().max(2000).default('')});
export const actionLifecycleSchema=z.enum(['PROPOSED','VALIDATED','RESERVED','READY','EXECUTING','INTERRUPTED','SUCCEEDED','FAILED','CANCELED','REJECTED','EXPIRED','STALE']);
export const behaviorAttemptSchema=z.strictObject({id,actorId:id,planId:id,profileVersion:label,decisionId:id,status:actionLifecycleSchema,startedAt:at,updatedAt:at,causeEventIds:z.array(id).max(100),completedEventIds:z.array(id).max(100),remainingPlanHash:label,failures:z.number().int().min(0).max(3),reasonCode:label});
export const conflictStages=['CALM','WARY','ASSERTIVE','THREATENED','VIOLENT','DISENGAGING','RECOVERING'] as const;
export const behaviorActorSchema=z.strictObject({actorId:id,continuation:z.strictObject({profileVersion:label,planIds:z.array(id).max(3),next:z.number().int().min(0).max(3),waitingForPlayer:z.boolean(),eventId:id}).nullable().default(null),pendingDomain:z.strictObject({decisionId:id,planId:id,resolveAt:at,actionHash:label}).nullable().default(null),milestoneHistory:z.array(z.strictObject({id:label,eventId:id,profileVersion:label,sourceIds:z.array(id)})).default([]),bypasses:z.array(z.strictObject({ruleId:label,sourceId:id,at})).default([]),profileVersion:label,revision:z.number().int().nonnegative(),lastEvaluatedAt:at,recoveredAt:at,nextEvaluationAt:at,tier:z.enum(['ACTIVE','NEARBY','BACKGROUND','DORMANT']),frozen:z.boolean(),persistent:z.boolean(),generation:z.number().int().nonnegative(),currentPlanId:id.nullable(),currentActionId:id.nullable(),emotion:z.record(label,unit),mood:unit,stress:unit,recoveryRemainders:z.record(label,z.number().int().min(0).max(999)),conflicts:z.record(label,z.strictObject({stage:z.enum(conflictStages),threat:unit,changedAt:at,sourceIds:z.array(id).max(32)})),cooldowns:z.array(z.strictObject({key:label,scope:z.enum(['actor-action','actor-target-action','topic-interaction','failed-route']),startedAt:at,expiresAt:at,causeId:id,policyVersion:label})),goals:z.array(behaviorGoalSchema),attempts:z.array(behaviorAttemptSchema),appraisals:z.array(z.strictObject({causeId:id,at,stress:unit,emotion:label,intensity:unit,profileVersion:label})),adaptations:z.array(z.strictObject({eventId:id,trait:z.enum(traitNames),day:z.string(),from:unit,to:unit,profileVersion:label,sourceIds:z.array(id)})),baseline:traitValues,wakes:z.array(z.strictObject({key:label,causeId:id,dueAt:at,mandatory:z.boolean(),kind:label})),promotions:z.array(z.strictObject({eventId:id,at,reason:label})),blockedReason:z.string().max(200)});
export const behaviorCandidateSchema=z.strictObject({id:label,planId:id.nullable(),eligible:z.boolean(),reasonCode:label,mandatory:z.boolean(),features:behaviorFeaturesSchema,score:z.number().int(),evidenceRefs:z.array(z.string()).max(100)});
export const behaviorDecisionSchema=z.strictObject({id,actorId:id,branchId:id,baseRevision:z.number().int().nonnegative(),at,profileVersion:label,rulesVersion:z.literal(behaviorRulesVersion),causeEventIds:z.array(id).max(100),draw:z.strictObject({lineage:label,value:unit,candidateIds:z.array(label)}).nullable().default(null),contextHash:label,contextManifest:z.json(),dependencyVersions:z.record(label,z.string()),contextSections:z.array(z.strictObject({id:z.string(),category:z.string(),sourceIds:z.array(z.string())})),candidates:z.array(behaviorCandidateSchema).max(101),selectedPlanId:id.nullable(),result:z.enum(['SELECTED','WAIT','BLOCKED','INVALIDATED']),reasonCode:label,attemptId:id.nullable(),committedEventIds:z.array(id).max(100),nextControl:z.enum(['PLAYER','WORLD']),nextEvaluationAt:at,source:z.enum(['DETERMINISTIC','RECORDED_AI']),acceptedProposal:z.json().nullable(),providerReceipt:z.json().nullable().default(null),eventHash:label.nullable()});
export const npcBehaviorSchema=z.strictObject({version:z.literal(1).default(1),branchId:id.nullable().default(null),scope:z.strictObject({campaignId:id,stateVersion:z.number().int().nonnegative(),eventCursor:z.string().max(160)}).nullable().default(null),leases:z.array(z.strictObject({id,actorId:id,attemptId:id,resourceId:id,expiresAt:at,status:z.enum(['ACTIVE','RELEASED','EXPIRED']),eventId:id})).default([]),plannerInputs:z.array(z.strictObject({id,actorId:id,branchId:id,profileVersion:label,baseRevision:z.number().int(),generation:z.number().int(),contextHash:label,planIds:z.array(id).min(1).max(3),status:z.enum(['ACCEPTED','CONSUMED','STALE']),proposal:z.json(),eventId:id})).default([]),profiles:z.array(npcProfileSchema).default([]),actors:z.array(behaviorActorSchema).default([]),decisions:z.array(behaviorDecisionSchema).default([]),templates:z.array(z.strictObject({id:label,version:label,status:z.enum(['draft','validated','published','retired']),profile:npcProfileSchema,eventId:id})).default([]),interventions:z.array(z.strictObject({eventId:id,actorId:id,at,operation:label,reason:z.string().min(1).max(2000)})).default([])});
export const behaviorProposalSchema=z.strictObject({decisionId:id,requestGeneration:z.number().int().nonnegative(),branchId:id,actorId:id,baseRevision:z.number().int().nonnegative(),profileVersion:label,contextHash:label,steps:z.array(z.strictObject({stepId:label,templateId:id,parameterTokens:z.record(label,label),afterStepIds:z.array(label).max(3),goalRefs:z.array(id).max(4),abortPredicateRefs:z.array(label).max(8)})).min(1).max(3)});
export type NpcProfile=z.infer<typeof npcProfileSchema>;
export type BehaviorActor=z.infer<typeof behaviorActorSchema>;
export type BehaviorCandidate=z.infer<typeof behaviorCandidateSchema>;
export type BehaviorDecision=z.infer<typeof behaviorDecisionSchema>;
export type BehaviorGoal=z.infer<typeof behaviorGoalSchema>;
export type BehaviorAttempt=z.infer<typeof behaviorAttemptSchema>;
export type NpcBehavior=z.infer<typeof npcBehaviorSchema>;
