import {anchorFor,mappedRoute,cityBridges} from './city-geography.ts';
import {canonSources} from './canon.ts';
import {randomUUID} from 'node:crypto';
import {data,getEntity} from './model.ts';
import type {Data,Entity,State} from './model.ts';
import {calendarView,hoursOpen,weatherView} from './calendar.ts';
import {carriedBy,itemPossessor} from './items.ts';
import {transitOption,vehicleHasPermission} from './vehicle.ts';
import {cosine,embedText} from './embedding.ts';
import {needsEnabled,needsPresentation} from './policy.ts';
import {heatSignals} from './investigation.ts';
const unique=(values:string[]=[])=>([...new Set(values)].sort());
const within=(now:number,from?:string|null,until?:string|null)=>!(from&&Date.parse(from)>now)&&!(until&&Date.parse(until)<=now);
const audienceAllows=(s:State,observerId:string,audience:string[]=[])=>{if(!audience.length||audience.includes('campaign')||audience.includes(observerId))return true;const observer=data(getEntity(s,observerId,'character'),'character');return observer.factionIds.some(id=>audience.includes(id));};
const socialAllows=(disclosure:string|undefined,knownByIds:string[]|undefined,observerId:string,participants:string[]=[])=>disclosure==='public'||Boolean(knownByIds?.includes(observerId))||(['private','disputed'].includes(disclosure??'private')&&participants.includes(observerId));
export type PropositionOptions={objectId?:string|null;qualifiers?:Record<string,unknown>;source?:string;truthStatus?:'verified'|'asserted'|'disputed'|'false'|'superseded';audience?:string[];confidence?:number;observedAt?:string|null;learnedAt?:string|null;validFrom?:string|null;validUntil?:string|null;eventIds?:string[];evidenceIds?:string[];tags?:string[]};
export function observe(s:State,observerId:string,factId:string,source:string,options:{confidence?:number;observedAt?:string|null;expiresAt?:string|null;evidenceIds?:string[]}={}) {
 getEntity(s,observerId,'character');const proposition=s.facts.find(f=>f.id===factId);if(!proposition)throw new Error('fact_unavailable');if(!audienceAllows(s,observerId,proposition.audience))throw new Error('fact_audience_denied');
 if(!s.knowledge.some(k=>k.observerId===observerId&&k.factId===factId))s.knowledge.push({observerId,factId,source,at:s.clock,confidence:options.confidence??proposition.confidence??1,observedAt:options.observedAt??s.clock,expiresAt:options.expiresAt??proposition.validUntil??null,evidenceIds:unique(options.evidenceIds??proposition.evidenceIds)});
}
export function fact(s:State,subjectId:string,predicate:string,value:unknown,eventId:string,observers:string[]=[],options:PropositionOptions={}){
 const id=randomUUID();s.facts.push({id,subjectId,predicate,objectId:options.objectId??null,value,qualifiers:options.qualifiers??{},source:options.source??'simulation',truthStatus:options.truthStatus??'verified',audience:unique(options.audience),confidence:options.confidence??1,observedAt:options.observedAt??s.clock,learnedAt:options.learnedAt??null,validFrom:options.validFrom??s.clock,validUntil:options.validUntil??null,eventId,eventIds:unique([eventId,...(options.eventIds??[])]),evidenceIds:unique(options.evidenceIds),tags:unique(options.tags),at:s.clock,retiredAt:null});
 for(const observer of unique(observers))observe(s,observer,id,'witnessed:'+eventId,{observedAt:s.clock,evidenceIds:options.evidenceIds});return id;
}
export function remember(s:State,observerId:string,text:string,eventId:string,salience=0.5,options:{interpretation?:string;privacy?:'private'|'shared';recallConditions?:{entityIds?:string[];tags?:string[];locationId?:string|null;from?:string|null;until?:string|null};decayPerDay?:number;expiresAt?:string|null;eventRefs?:string[];tags?:string[]}={}){
 getEntity(s,observerId,'character');s.memories.push({id:randomUUID(),observerId,text,interpretation:options.interpretation??text,salience,decayPerDay:options.decayPerDay??0.01,eventId,eventRefs:unique([eventId,...(options.eventRefs??[])]),at:s.clock,private:(options.privacy??'private')==='private',privacy:options.privacy??'private',recallConditions:{entityIds:unique(options.recallConditions?.entityIds),tags:unique(options.recallConditions?.tags),locationId:options.recallConditions?.locationId??null,from:options.recallConditions?.from??null,until:options.recallConditions?.until??null},lastRefreshedAt:s.clock,refreshCount:0,expiresAt:options.expiresAt??null,tags:unique(options.tags)});
}
export function gossip(s:State,fromId:string,toId:string,beliefId:string,eventId:string,confidenceLoss=0.2){
 getEntity(s,fromId,'character');getEntity(s,toId,'character');const source=s.beliefs.find(row=>row.id===beliefId&&row.observerId===fromId);if(!source)throw new Error('belief_unavailable');
 const id=randomUUID();s.beliefs.push({...structuredClone(source),id,observerId:toId,confidence:Math.max(0,Math.min(1,source.confidence*(1-confidenceLoss))),source:'gossip-from:'+fromId+':'+eventId,truthStatus:'believed',audience:[toId],observedAt:null,eventIds:unique([...(source.eventIds??[]),eventId]),at:s.clock,correctedBy:null});return id;
}
export function memorySalience(s:State,memory:State['memories'][number]){const anchor=memory.lastRefreshedAt??memory.at;if(memory.expiresAt&&Date.parse(memory.expiresAt)<=Date.parse(s.clock))return 0;return Math.max(0,memory.salience-(Date.parse(s.clock)-Date.parse(anchor))/86400000*memory.decayPerDay);}
export function knows(s:State,observerId:string,subjectId:string){
 const now=Date.parse(s.clock);return s.knowledge.some(k=>k.observerId===observerId&&(!k.expiresAt||Date.parse(k.expiresAt)>now)&&s.facts.some(f=>f.id===k.factId&&f.subjectId===subjectId&&!f.retiredAt&&within(now,f.validFrom,f.validUntil)&&audienceAllows(s,observerId,f.audience)));
}
export function visible(s:State,e:Entity,observerId:string):boolean{
 if(e.archived)return false;
 const observer=data(getEntity(s,observerId,'character'),'character');
 if(e.id===observerId)return true;
 if(e.kind==='location'&&e.id===observer.locationId)return true;
 if(e.visibility==='creator')return false;
 if(e.kind==='location'&&(e.data.discoverable||(e.data.discoveredByIds as string[]??[]).includes(observerId)||(e.data.visitedByIds as string[]??[]).includes(observerId)))return true;
 if(['transition','production','socialRule','lawPosture','criminalHeat'].includes(e.kind))return false;
 if(e.kind==='account'){const account=data(e,'account');return account.ownerId===observerId||account.authorizedUserIds.includes(observerId);}
 if(e.kind==='transaction'){const transaction=data(e,'transaction');return transaction.ownerId===observerId||transaction.counterpartyIds.includes(observerId);}
 if(e.kind==='receipt'){const receipt=data(e,'receipt');return receipt.ownerId===observerId||receipt.buyerId===observerId||receipt.sellerId===observerId;}
 if(e.kind==='bill'){const bill=data(e,'bill');return bill.debtorId===observerId||bill.creditorId===observerId;}
 if(e.kind==='dispatch')return e.data.requesterId===observerId||e.data.responderId===observerId||e.data.patientId===observerId;
 if(e.kind==='crimeReport')return e.data.reporterId===observerId||e.data.recipientId===observerId;
 if(e.kind==='crime'){const crime=data(e,'crime');return crime.offenderIds.includes(observerId)||crime.victimIds.includes(observerId)||crime.witnessIds.includes(observerId)||crime.caseIds.some(caseId=>{const file=s.entities.find(candidate=>candidate.id===caseId&&candidate.kind==='case'&&!candidate.archived);return file?.data.investigatorId===observerId;});}
 if(e.kind==='informant'){const informant=data(e,'informant');return informant.characterId===observerId||informant.handlerId===observerId||informant.knownByIds.includes(observerId);}
 if(e.kind==='factionOrder'){const order=data(e,'factionOrder');return order.issuerId===observerId||order.knownByIds.includes(observerId);}
 if(e.kind==='rumor'){const rumor=data(e,'rumor');return rumor.audience.public||rumor.knownByIds.includes(observerId)||rumor.audience.characterIds.includes(observerId);}
 if(e.kind==='factionEvent'){const event=data(e,'factionEvent');return Boolean(event.publicStory)||event.knownByIds.includes(observerId);}
 if(e.kind==='estate')return e.data.executorId===observerId||e.data.beneficiaryId===observerId;
 if(e.kind==='judgment')return e.data.characterId===observerId&&!!e.data.appliedAt;
 if(e.kind==='message'){const d=data(e,'message');if(d.deletedByIds.includes(observerId)||d.hiddenFromIds.includes(observerId))return false;const access=(phoneId:string|null,participantId:string|null)=>{if(!phoneId)return false;const phone=s.entities.find(candidate=>candidate.id===phoneId&&candidate.kind==='item'&&!candidate.archived);if(!phone)return false;const item=data(phone,'item'),physical=carriedBy(s,phone,observerId)||item.authorizedUserIds.includes(observerId);return item.category==='phone'&&item.phoneState==='active'&&item.condition>0&&!item.locked&&(!item.batteryRequired||item.battery>0)&&physical&&(participantId===observerId||item.authorizedUserIds.includes(observerId)||item.stolen);};return access(d.phoneId,d.fromId)||access(d.recipientPhoneId,d.toId)&&!['draft','queued','sent','failed'].includes(d.status);}
 if(e.kind==='socialPost'){const post=data(e,'socialPost');if(post.deleted||post.hiddenFromIds.includes(observerId)||post.source==='simulation'&&!post.validated)return false;const author=data(getEntity(s,post.authorId,'character'),'character'),hasFeed=s.entities.some(candidate=>{if(candidate.kind!=='item'||candidate.archived)return false;const item=data(candidate,'item');return item.category==='phone'&&item.phoneState==='active'&&item.condition>0&&!item.locked&&(!item.batteryRequired||item.battery>0)&&(carriedBy(s,candidate,observerId)||item.authorizedUserIds.includes(observerId))&&item.phoneApps.social;});if(!hasFeed)return false;if(post.authorId===observerId)return true;if(post.privacy==='public')return true;if(post.privacy==='friends')return author.socialConnections.friendIds.includes(observerId);if(post.privacy==='followers')return author.socialConnections.followerIds.includes(observerId);if(post.privacy==='custom')return post.allowedViewerIds.includes(observerId);return false;}
 if(e.kind==='relationship'){const d=data(e,'relationship'),disclosure=d.secret?'secret':d.disclosure;return socialAllows(disclosure,d.knownByIds,observerId,[d.fromId,d.toId]);}
 if(e.kind==='reputation'||e.kind==='obligation')return false;
 if(e.kind==='injury'){const injury=data(e,'injury'),patient=data(getEntity(s,injury.characterId,'character'),'character');return injury.characterId===observerId||injury.knownByIds.includes(observerId)||injury.diagnosedByIds.includes(observerId)||injury.healthVisibility==='public'||injury.healthVisibility==='symptoms'&&patient.locationId===observer.locationId&&injury.symptoms.some(symptom=>symptom.visibility==='observable');}
 if(e.kind==='deathRecord'){const death=data(e,'deathRecord');return death.characterId===observerId||death.witnessIds.includes(observerId)||death.identifiedByIds.includes(observerId)||death.notifiedIds.includes(observerId);}
 if(e.kind==='combat'){const combat=data(e,'combat');return combat.participants.includes(observerId)||!!combat.locationId&&combat.locationId===observer.locationId;}
 if(e.kind==='chase'){const chase=data(e,'chase');return chase.participants.includes(observerId)||chase.witnessIds.includes(observerId)||chase.status==='active'&&chase.locationId===observer.locationId;}
 if(e.kind==='case')return e.data.investigatorId===observerId||(e.data.suspectIds as string[]).includes(observerId)&&['arrest','booking','jail','bail','interrogation','charged','trial','sentenced','probation','parole'].includes(String(e.data.stage));
 if(e.kind==='evidence')return (e.data.discoveredBy as string[]).includes(observerId)||(e.data.knownByIds as string[]).includes(observerId)||e.data.custodianId===observerId;
 if(e.kind==='watcher')return false;
 if(e.kind==='quest'&&(data(e,'quest').characterId===observerId||data(e,'quest').knownByIds.includes(observerId)))return true;
 if(e.kind==='character')return e.data.locationId===observer.locationId&&observer.locationId!==null||knows(s,observerId,e.id);
 if(e.kind==='item'){
  if(e.data.category==='phone'&&(e.data.authorizedUserIds as string[]??[]).includes(observerId))return true;
  if(carriedBy(s,e,observerId))return true;
  if(e.data.concealed&&!(e.data.discoveredByIds as string[]??[]).includes(observerId))return false;
  if(e.data.containerId){const container=s.entities.find(c=>c.id===e.data.containerId&&!c.archived);if(container?.kind==='vehicle'&&(container.data.locationId!==observer.locationId||!vehicleHasPermission(s,container,observerId,'trunk')))return false;return !!container&&!container.data.locked&&visible(s,container,observerId);}
  if(e.data.locationId===observer.locationId&&observer.locationId!==null)return true;
  const possessor=itemPossessor(s,e);return s.entities.some(b=>!b.archived&&b.data.locationId===observer.locationId&&observer.locationId!==null&&b.id===(possessor??e.data.ownerId)&&(b.kind==='business'&&(b.data.stock as string[]).includes(e.id)||b.kind==='character'&&e.data.equipped&&visible(s,b,observerId)));
 }
 if(e.visibility==='knowledge')return knows(s,observerId,e.id);
 if(e.visibility==='owner')return e.data.ownerId===observerId||e.data.characterId===observerId||e.data.employeeId===observerId||e.data.tenantId===observerId;
 return true;
}
export function project(s:State,e:Entity,observerId:string):Entity {
 const copy=structuredClone(e);
 if(e.kind==='media')delete copy.data.body;
 copy.data.mediaIds=((e.data.mediaIds??[]) as string[]).filter(id=>{const media=s.entities.find(e=>e.id===id&&e.kind==='media');return media&&visible(s,media,observerId);});
 if(e.kind==='case'&&e.data.investigatorId!==observerId){copy.name='Case notice';copy.data={stage:e.data.stage!,bailAmountCents:e.data.bailAmountCents??null,bookingCompletesAt:e.data.bookingCompletesAt??null,holdingUntil:e.data.holdingUntil??null,courtAt:e.data.courtAt??null,releasedAt:e.data.releasedAt??null};return copy;}
 if(e.kind==='evidence'){const evidence=data(e,'evidence');copy.data.investigationOptions=evidence.investigationOptions.filter(option=>option.completedAt).map(({creatorTruth,...option})=>option);copy.data.analyses=evidence.analyses.filter(analysis=>analysis.analystId===observerId||evidence.knownByIds.includes(observerId));}
 if(e.kind==='informant'){const informant=data(e,'informant');copy.data.tips=informant.tips.filter(tip=>tip.disclosedAt&&observerId===informant.handlerId).map(({creatorTruth,...tip})=>tip);copy.data.reliabilityHistory=observerId===informant.handlerId?informant.reliabilityHistory:[];}
 if(e.kind==='rumor'){const rumor=data(e,'rumor');delete copy.data.truthRelation;delete copy.data.knownByIds;copy.data.audience={public:rumor.audience.public,characterIds:[],factionIds:[],locationIds:[]};copy.data.spreadHistory=rumor.spreadHistory.filter(row=>row.fromId===observerId||row.toId===observerId);if(rumor.correctedByRumorId&&!s.entities.some(row=>row.id===rumor.correctedByRumorId&&visible(s,row,observerId)))copy.data.correctedByRumorId=null;}
 if(e.kind==='factionOrder'){const order=data(e,'factionOrder');copy.data.recipientIds=order.recipientIds.filter(id=>id===observerId||order.issuerId===observerId);copy.data.deliveries=order.deliveries.filter(row=>row.recipientId===observerId||order.issuerId===observerId);delete copy.data.knownByIds;}
 if(e.kind==='factionEvent'){const event=data(e,'factionEvent'),inside=event.knownByIds.includes(observerId);if(!inside)copy.data={description:event.description,tags:event.tags,sections:[],mediaIds:event.mediaIds,factionId:event.factionId,hookId:event.hookId,outcome:event.outcome,actorIds:[],targetIds:[],affectedFactionIds:[],locationId:event.locationId,orderId:null,rumorId:null,occurredAt:event.occurredAt,cooldownUntil:event.cooldownUntil,cause:{summary:'Publicly observable consequences.',goalId:null,pressure:0,resources:{},incidentIds:[]},summary:event.publicStory||event.summary,publicStory:event.publicStory,knownByIds:[]} as Entity['data'];}
 if(e.kind==='injury'){
  const injury=data(e,'injury'),medical=injury.diagnosedByIds.includes(observerId),patient=injury.characterId===observerId,assessment=[...injury.assessments].reverse().find(row=>row.sharedWithIds.includes(observerId)||row.assessorId===observerId),band=(value:number)=>value<25?'low':value<50?'moderate':value<75?'high':'severe';
  copy.data={healthSchemaVersion:injury.healthSchemaVersion,characterId:injury.characterId,bodyPart:injury.bodyPart,bodyRegion:injury.bodyRegion,side:injury.side,category:medical||assessment||injury.healthVisibility==='public'?injury.category:'condition',symptoms:injury.symptoms.filter(symptom=>medical||patient&&symptom.visibility!=='medical'||!patient&&symptom.visibility==='observable').map(symptom=>({name:symptom.name,intensity:band(symptom.severity),description:symptom.description})),assessment:assessment?{at:assessment.at,method:assessment.method,severityBand:assessment.severityBand,diagnosis:assessment.diagnosis,confidenceBand:band(assessment.confidence)}:null,treatmentStatus:injury.course.status,treated:injury.treated,stabilized:injury.stabilized,permanent:injury.permanent,expectedCourse:assessment||medical?{expectedDays:injury.course.expectedDays,requiresClinical:injury.treatmentRequirements.requiresClinical}:null,onsetAt:patient||medical?injury.onsetAt:null} as Entity['data'];return copy;
 }
 if(e.kind==='deathRecord'){
  const death=data(e,'deathRecord'),identified=death.identified||death.identifiedByIds.includes(observerId),remains=s.entities.find(entity=>entity.id===death.remainsId),evidenceIds=death.evidenceIds.filter(id=>{const evidence=s.entities.find(entity=>entity.id===id);return !!evidence&&visible(s,evidence,observerId);});copy.data={occurredAt:death.occurredAt,locationId:death.locationId,status:death.status,identified,characterId:identified?death.characterId:null,remainsId:remains&&visible(s,remains,observerId)?death.remainsId:null,evidenceIds,continuation:death.continuation} as Entity['data'];return copy;
 }
 const own=e.id===observerId||e.kind==='item'&&carriedBy(s,e,observerId)||e.data.ownerId===observerId||e.kind==='vehicle'&&vehicleHasPermission(s,e,observerId,'manage')||e.kind==='item'&&e.data.category==='phone'&&(e.data.authorizedUserIds as string[]??[]).includes(observerId);
 if(e.kind==='item'&&!own){delete copy.data.secretContents;delete copy.data.provenanceRecords;delete copy.data.eventHistory;}
 if(e.kind==='vehicle'&&!own){for(const key of ['vin','registration','keyId','keyIds','accessGrants','authorizedDriverIds','hotwiredByIds','custodianId','custodyRole','custodyHistory','theftReports','repairRecords','history'])delete copy.data[key];if(!(e.data.discoveredByIds as string[]).includes(observerId)){delete copy.data.stolen;delete copy.data.theftStatus;}}
 if(e.kind==='character'&&!own){
  const d=data(e,'character'),actor=data(getEntity(s,observerId),'character');
  const learned=knows(s,observerId,e.id),permitted=(field:string)=>{const policy=d.profileVisibility[field];return policy==='campaign'||policy==='owner'&&own||policy==='knowledge'&&learned;};
  const presentation:Record<string,unknown>={locationId:d.locationId===actor.locationId?d.locationId:null,condition:d.condition,characterSchemaVersion:d.characterSchemaVersion,sections:d.sections};
  for(const [field,value] of Object.entries(d))if(permitted(field))presentation[field]=structuredClone(value);
  const mediaIds=d.mediaIds.filter(id=>{const media=s.entities.find(candidate=>candidate.id===id&&candidate.kind==='media'&&!candidate.archived);return !!media&&visible(s,media,observerId);});
  const portrait=d.portraitMediaId?s.entities.find(candidate=>candidate.id===d.portraitMediaId&&candidate.kind==='media'&&!candidate.archived):undefined;
  presentation.mediaIds=mediaIds;
  presentation.portraitMediaId=portrait&&visible(s,portrait,observerId)?portrait.id:null;
  copy.data=presentation as Entity['data'];
 }else{
  for(const k of ['secrets','instructions','aiBehavior','hiddenSolution','embedding','pending','preferences','goals','fears','forensicFindings'])delete copy.data[k];
  if(e.kind!=='location')delete copy.data.heat;
  if(e.kind==='character'&&e.id===observerId)copy.data.attentionSignals=heatSignals(s,observerId);
  if(e.kind==='relationship'){
   const relation=data(e,'relationship'),participants=[relation.fromId,relation.toId];
   for(const k of ['attraction','desire','affection','trust','respect','attachment','familiarity','jealousy','resentment','fear','loyalty','dependency','boundaries','inertia','cooldownMinutes','movementThreshold','lastMeaningfulAt','knownByIds','pending','secret'])delete copy.data[k];
   copy.data.labelRecords=relation.labelRecords.filter(label=>socialAllows(label.disclosure,label.knownByIds,observerId,participants));
   copy.data.labels=relation.labelRecords.length?(copy.data.labelRecords as typeof relation.labelRecords).filter(label=>label.status==='active').map(label=>label.label):relation.labels;
   copy.data.history=relation.history.filter(entry=>socialAllows(entry.disclosure??'private',entry.knownByIds,observerId,participants)).map(entry=>({at:entry.at,eventId:entry.eventId,label:entry.label,kind:entry.kind??'system',reason:entry.reason??entry.label,disclosure:entry.disclosure??'private'}));
   copy.data.consentRequests=relation.consentRequests.filter(request=>request.initiatorId===observerId||request.recipientId===observerId).map(request=>({id:request.id,intent:request.intent,initiatorId:request.initiatorId,recipientId:request.recipientId,requestedAt:request.requestedAt,expiresAt:request.expiresAt,status:request.status,respondedAt:request.respondedAt,contentMode:request.contentMode,voluntary:true}));
  }
  if(!own)for(const k of ['cash','contacts','serial','registration','stock','suspectIds','custody','schedule','lastSimulated','mood','goals','fears','notes','familyBackground','cultureContext','beliefsContext','authorizedUserIds'])delete copy.data[k];
  if(e.kind==='faction'){
   const faction=data(e,'faction');copy.data.privateFacts=faction.privateFacts.filter(row=>row.knownByIds.includes(observerId));copy.data.hierarchy=faction.hierarchy.filter(row=>row.public);copy.data.memberships=faction.memberships.filter(row=>row.public||row.characterId===observerId||row.knownByIds.includes(observerId));copy.data.relations=faction.relations.filter(row=>row.public||row.knownByIds.includes(observerId));for(const k of ['memberIds','reputation','treasuryCents','resources','rules','enemyIds','allyIds','goals','knownIncidentIds','reputationAudiences','eventHooks','simulationPolicy','lastFactionAt','history','groupPolicy','lastGroupAt','dispatchPolicy'])delete copy.data[k];
  }
 if(e.kind==='quest'){const event=data(e,'quest');delete copy.data.branches;delete copy.data.hiddenSolution;delete copy.data.triggerConditions;delete copy.data.stateMachine;delete copy.data.followUpTriggers;delete copy.data.trace;copy.data.objectiveRecords=event.objectiveRecords.filter(row=>(!row.hidden||row.knownByIds.includes(observerId))&&(!row.branchId||!event.activeBranchId||row.branchId===event.activeBranchId)).map(({knownByIds,...row})=>row);copy.data.possibleOutcomes=event.possibleOutcomes.filter(row=>(!row.hidden||row.knownByIds.includes(observerId))&&(!row.branchId||!event.activeBranchId||row.branchId===event.activeBranchId)).map(({knownByIds,conditions,validActionTags,followUpWatcherIds,...row})=>row);copy.data.journal=event.journal.filter(row=>row.knownByIds.includes(observerId)&&(!row.branchId||!event.activeBranchId||row.branchId===event.activeBranchId)).map(({knownByIds,...row})=>row);delete copy.data.knownByIds;}
  if(e.kind==='character'&&!s.settings.reproductiveHealth)delete copy.data.reproductive;
  if(e.kind==='combat'){
   const combat=data(e,'combat'),allowed=new Set(combat.participants.filter(id=>id===observerId||visible(s,getEntity(s,id,'character'),observerId))),actorStates=Object.fromEntries(Object.entries(combat.actorStates).filter(([id])=>allowed.has(id)).map(([id,state])=>{const projected=structuredClone(state);if(id!==observerId)for(const key of ['goal','fear','morale','surrenderThreshold','fleeThreshold','visibleTargetIds','availableActions'] as const)delete projected[key];else projected.visibleTargetIds=projected.visibleTargetIds.filter(id=>allowed.has(id));return [id,projected];}));
   copy.data={...copy.data,participants:combat.participants.filter(id=>allowed.has(id)),sides:Object.fromEntries(Object.entries(combat.sides).filter(([id])=>allowed.has(id))),turnOrder:combat.turnOrder.filter(id=>allowed.has(id)),positions:Object.fromEntries(Object.entries(combat.positions).filter(([id])=>allowed.has(id))),cover:Object.fromEntries(Object.entries(combat.cover).filter(([id])=>allowed.has(id))),defenses:Object.fromEntries(Object.entries(combat.defenses).filter(([id])=>allowed.has(id))),actorStates,blockedLines:[]} as Entity['data'];
  }
  if(e.kind==='chase'){
   const chase=data(e,'chase'),allowed=new Set(chase.participants.filter(id=>id===observerId||visible(s,getEntity(s,id,'character'),observerId))),actorStates=Object.fromEntries(Object.entries(chase.actorStates).filter(([id])=>allowed.has(id)).map(([id,state])=>[id,id===observerId?state:{role:state.role,zoneId:state.zoneId,vehicleId:state.vehicleId,escaped:state.escaped,caught:state.caught,visibleOpponentIds:state.visibleOpponentIds.filter(targetId=>allowed.has(targetId))}]));
   copy.data={...copy.data,participants:chase.participants.filter(id=>allowed.has(id)),pursuerIds:chase.pursuerIds.filter(id=>allowed.has(id)),quarryIds:chase.quarryIds.filter(id=>allowed.has(id)),turnOrder:chase.turnOrder.filter(id=>allowed.has(id)),actorStates,witnessIds:chase.witnessIds.includes(observerId)?[observerId]:[],history:chase.history.filter(entry=>allowed.has(entry.actorId))} as Entity['data'];
  }
  if(e.kind==='character'){
   copy.data.traits=(copy.data.traits as string[]).filter(traitId=>{const trait=s.entities.find(entity=>entity.id===traitId&&entity.kind==='trait'&&!entity.archived);return !!trait&&visible(s,trait,observerId);});
   delete copy.data.plans;delete copy.data.traitEffectTrace;
  }
  if(e.kind==='location')copy.data.exits=(copy.data.exits as {to:string;interruption?:unknown}[]).filter(exit=>s.entities.some(target=>target.id===exit.to&&visible(s,target,observerId))).map(({interruption,...route})=>route) as never;
 }
 if(e.kind==='character'&&e.id===observerId){const character=data(e,'character'),band=(value:number)=>value<25?'low':value<50?'moderate':value<75?'high':'severe',needs=needsPresentation(s);copy.data.healthSummary={condition:character.condition,blood:character.blood>75?'stable':character.blood>25?'reduced':'critical',pain:band(character.pain),fatigue:band(character.fatigue),intoxication:band(character.intoxication),withdrawal:character.withdrawalEnabled?band(character.withdrawal):'not-enabled',activeEffects:character.activeSubstances.filter(exposure=>Date.parse(exposure.expiresAt)>Date.parse(s.clock)).map(exposure=>({name:exposure.name,kind:exposure.kind,expiresAt:exposure.expiresAt}))};if(needsEnabled(s)&&needs.ui==='summary'){copy.data.needsSummary={hunger:band(character.hunger),thirst:band(character.thirst),hygiene:character.hygiene>75?'clean':character.hygiene>25?'needs-attention':'poor'};for(const key of ['hunger','thirst','hygiene'])delete copy.data[key];}else if(!needsEnabled(s)||needs.ui==='hidden')for(const key of ['hunger','thirst','hygiene','needsContext'])delete copy.data[key];for(const key of ['blood','pain','intoxication','withdrawal','withdrawalEnabled','dependence','lastDoseAt','activeSubstances','restUntil'])delete copy.data[key];}
 const sections=(copy.data.sections??[]) as {id:string;parentId:string|null;visibility?:string;archived?:boolean;fields:{visibility:string;archived?:boolean}[]}[];
 // Custom section containers reveal only those fields explicitly allowed to this observer.
 const canSee=(v:string|undefined)=>v==='campaign'||v==='owner'&&own||v==='knowledge'&&knows(s,observerId,e.id);
 const sectionVisible=(section:typeof sections[number]):boolean=>!section.archived&&!!canSee(section.visibility)&&(!section.parentId||!!sections.find(p=>p.id===section.parentId&&sectionVisible(p)));
 const allowed=new Set(sections.filter(section=>sectionVisible(section)&&section.fields.some(f=>!f.archived&&canSee(f.visibility))).map(x=>x.id));
 copy.data.sections=sections.filter(section=>allowed.has(section.id)).map(section=>({...section,fields:section.fields.filter(f=>!f.archived&&(f.visibility==='campaign'||f.visibility==='owner'&&own||f.visibility==='knowledge'&&knows(s,observerId,e.id)))})) as never;
 return copy;
}
export function observerView(s:State,observerId:string){
 const entities=s.entities.filter(e=>visible(s,e,observerId)).map(e=>project(s,e,observerId)),now=Date.parse(s.clock);
 const factIds=new Set(s.knowledge.filter(k=>k.observerId===observerId&&(!k.expiresAt||Date.parse(k.expiresAt)>now)).map(k=>k.factId));
 const needs=needsPresentation(s);return {clock:s.clock,calendar:calendarView(s),weather:weatherView(s),locationBrowser:locationBrowser(s,observerId),settings:{needs:needsEnabled(s),needsPolicy:{intensity:s.settings.campaign?.needsIntensity??(s.settings.needs?'grounded':'off'),...needs},fuel:s.settings.fuel,romance:s.settings.romance,intimacy:s.settings.intimacy,intensity:s.settings.intensity,weather:s.settings.weather,rulesConfigured:s.settings.rules!==null},
 entities,facts:s.facts.filter(f=>factIds.has(f.id)&&!f.retiredAt&&within(now,f.validFrom,f.validUntil)&&audienceAllows(s,observerId,f.audience)),
 beliefs:s.beliefs.filter(b=>b.observerId===observerId&&within(now,b.validFrom,b.validUntil)&&audienceAllows(s,observerId,b.audience)),
 memories:s.memories.filter(m=>m.observerId===observerId&&(!m.expiresAt||Date.parse(m.expiresAt)>now)).map(m=>({...m,currentSalience:memorySalience(s,m)}))};
}
export function locationBrowser(s:State,observerId:string){
 const observer=data(getEntity(s,observerId,'character'),'character'),currentId=observer.locationId,visibleLocations=s.entities.filter(entity=>entity.kind==='location'&&visible(s,entity,observerId)),visibleIds=new Set(visibleLocations.map(entity=>entity.id)),carriedTags=new Set(s.entities.filter(entity=>entity.kind==='item'&&carriedBy(s,entity,observerId)).flatMap(entity=>entity.data.tags as string[])),carriedIds=new Set(s.entities.filter(entity=>entity.kind==='item'&&carriedBy(s,entity,observerId)).map(entity=>entity.id));
 const access=(location:Data<'location'>)=>{const explicitlyAllowed=location.ownerId===observerId||location.access.allowedCharacterIds.includes(observerId),configured=location.access.requiredItemIds.length+location.access.requiredTags.length>0,credentials=configured&&location.access.requiredItemIds.every(id=>carriedIds.has(id))&&location.access.requiredTags.every(tag=>observer.tags.includes(tag)||carriedTags.has(tag));return location.access.policy==='public'||location.access.policy==='restricted'&&(explicitlyAllowed||credentials)||location.access.policy==='private'&&explicitlyAllowed&&(!configured||credentials);};
 const current=currentId?s.entities.find(entity=>entity.kind==='location'&&entity.id===currentId&&!entity.archived):null,currentData=current?data(current,'location'):null;
 const routes=currentData?.exits.filter(route=>visibleIds.has(route.to)).map(route=>({...route,interruption:undefined,weatherMinutes:route.weatherPenalties?.[s.settings.weather]??0}))??[];
 const hierarchy=(locationId:string)=>{const path:string[]=[];let cursor=s.entities.find(entity=>entity.kind==='location'&&entity.id===locationId&&!entity.archived);const seen=new Set<string>();while(cursor&&visibleIds.has(cursor.id)&&!seen.has(cursor.id)){seen.add(cursor.id);path.unshift(cursor.name);const parentId=data(cursor,'location').parentId;cursor=parentId?s.entities.find(entity=>entity.kind==='location'&&entity.id===parentId&&!entity.archived):undefined;}return path;};
 const locations=visibleLocations.filter(entity=>!data(entity,'location').mapPresentation.hidden||entity.id===currentId).map(entity=>{const location=data(entity,'location'),authoredRoutes=routes.filter(route=>route.to===entity.id).map(route=>({mode:route.modes,minutes:route.minutes+(route.weatherPenalties?.[s.settings.weather]??0),baseMinutes:route.minutes,distanceKm:route.distanceKm??null,fareCents:route.fare,locked:route.locked,canUnlock:!!route.keyId&&carriedIds.has(route.keyId),serviceId:null})),serviceRoutes=currentId&&entity.id!==currentId?(['transit','taxi'] as const).flatMap(mode=>{const option=transitOption(s,currentId,entity.id,mode);return option&&visible(s,option.service,observerId)&&Number.isFinite(option.totalMinutes)?[{mode:[mode] as Array<'walk'|'drive'|'transit'|'taxi'>,minutes:option.totalMinutes,baseMinutes:option.route.minutes,distanceKm:null,fareCents:option.route.fareCents,locked:false,serviceId:option.service.id}]:[]}):[],mappedRoutes=current&&!currentData?.exits.some(e=>e.to===entity.id)?(['walk','drive'] as const).flatMap(mode=>{const route=mappedRoute(s,current,entity,mode);return route?[{...route,mode:[mode] as Array<'walk'|'drive'|'transit'|'taxi'>,baseMinutes:route.minutes,fareCents:0,locked:false,serviceId:null}]:[]}):[],routeOptions=[...authoredRoutes,...serviceRoutes,...mappedRoutes],occupants=s.entities.filter(candidate=>candidate.kind==='character'&&!candidate.archived&&candidate.data.locationId===entity.id&&visible(s,candidate,observerId)).map(candidate=>({id:candidate.id,name:candidate.name})),isOpen=hoursOpen(s,location.hours,location.closedDates,location.closedWeather),accessible=access(location),visited=entity.id===currentId||location.visitedByIds.includes(observerId)||s.facts.some(fact=>fact.subjectId===entity.id&&fact.predicate==='visited'&&s.knowledge.some(row=>row.observerId===observerId&&row.factId===fact.id));return {id:entity.id,name:location.mapPresentation.label||entity.name,description:location.description,category:location.category,parentId:location.parentId,hierarchy:hierarchy(entity.id),tags:location.tags,discovery:visited?'visited':location.discoveredByIds.includes(observerId)?'discovered':location.discoverable?'public':'learned',current:entity.id===currentId,open:isOpen,accessible,access:location.access,reasonableToGo:entity.id===currentId||routeOptions.length>0&&isOpen&&accessible,routes:routeOptions,hours:location.hours,occupants,safety:location.safety,heat:location.heat,weatherExposed:location.weatherExposed,visibilityPenalty:location.weatherExposed?(s.settings.weatherVisibilityPenalties[s.settings.weather]??0):0,mapPresentation:{...location.mapPresentation,...(anchorFor(s,entity)&&location.mapPresentation.x===null?{x:anchorFor(s,entity)!.x,y:anchorFor(s,entity)!.y}:{} )}};}).sort((left,right)=>Number(right.current)-Number(left.current)||left.mapPresentation.order-right.mapPresentation.order||left.hierarchy.length-right.hierarchy.length||left.name.localeCompare(right.name));
 return {currentLocationId:currentId,breadcrumbs:currentId?hierarchy(currentId):[],weather:weatherView(s),locations,bridges:cityBridges,mapScale:'Approximate Island County scale; fictional urban routes and bridges. Not real-world directions.'};
}
export type RetrievalFilters={entityIds?:string[];tags?:string[];from?:string|null;until?:string|null;placeIds?:string[];personIds?:string[];relationshipIds?:string[];eventIds?:string[];evidenceIds?:string[];factionIds?:string[];kinds?:Array<'lore'|'storycard'|'canon'>};
const normalizedFilters=(filters:RetrievalFilters):Required<Omit<RetrievalFilters,'from'|'until'>>&Pick<RetrievalFilters,'from'|'until'>=>({entityIds:unique(filters.entityIds),tags:unique(filters.tags?.map(tag=>tag.toLowerCase())),from:filters.from??null,until:filters.until??null,placeIds:unique(filters.placeIds),personIds:unique(filters.personIds),relationshipIds:unique(filters.relationshipIds),eventIds:unique(filters.eventIds),evidenceIds:unique(filters.evidenceIds),factionIds:unique(filters.factionIds),kinds:unique(filters.kinds) as Array<'lore'|'storycard'|'canon'>});
const overlaps=(left:string[]=[],right:string[]=[])=>!right.length||left.some(value=>right.includes(value));
const descriptors=(s:State,entity:Entity)=>{const d=data(entity,entity.kind as 'lore'|'storycard'),scope=d.scope,activation=d.activation,evidenceIds=new Set(s.entities.filter(candidate=>candidate.kind==='evidence'&&!candidate.archived).map(candidate=>candidate.id));return {entityIds:unique([entity.id,...d.links,...d.linkDetails.map(link=>link.targetId),...(d.subjectId?[d.subjectId]:[])]),tags:unique(d.tags.map(tag=>tag.toLowerCase())),placeIds:unique([...scope.placeIds,...(activation?.placeIds??[]),...(activation?.locationId?[activation.locationId]:[])]),personIds:unique([...scope.peopleIds,...(activation?.peopleIds??[]),...(activation?.characterId?[activation.characterId]:[])]),relationshipIds:unique([...scope.relationshipIds,...(activation?.relationshipIds??[])]),eventIds:unique([...scope.eventIds,...(activation?.eventIds??[])]),evidenceIds:unique([...d.links,...d.linkDetails.filter(link=>link.type.toLowerCase()==='evidence').map(link=>link.targetId)].filter(id=>evidenceIds.has(id))),factionIds:unique([...scope.factionIds,...(activation?.factionIds??[])])};};
const matchesFilters=(s:State,entity:Entity,filters:ReturnType<typeof normalizedFilters>)=>{const d=data(entity,entity.kind as 'lore'|'storycard'),x=descriptors(s,entity);return (!filters.kinds.length||filters.kinds.includes(entity.kind as 'lore'|'storycard'))&&overlaps(x.entityIds,filters.entityIds)&&filters.tags.every(tag=>x.tags.includes(tag))&&overlaps(x.placeIds,filters.placeIds)&&overlaps(x.personIds,filters.personIds)&&overlaps(x.relationshipIds,filters.relationshipIds)&&overlaps(x.eventIds,filters.eventIds)&&overlaps(x.evidenceIds,filters.evidenceIds)&&overlaps(x.factionIds,filters.factionIds)&&(!filters.from||!d.validUntil||Date.parse(d.validUntil)>=Date.parse(filters.from))&&(!filters.until||!d.validFrom||Date.parse(d.validFrom)<=Date.parse(filters.until));};
export function storyCardState(entity:Entity,s:State,observerId:string,query:string):{active:boolean;reason:'expired'|'not-yet-valid'|'scope-mismatch'|'activation-conditions-unmet'|'deactivated'|'active';activatesWhen:unknown;deactivatesWhen:unknown}{
 const d=data(entity,entity.kind as 'lore'|'storycard'),now=Date.parse(s.clock),observer=data(getEntity(s,observerId,'character'),'character'),location=observer.locationId,events=new Set(s.eventIds??s.facts.flatMap(f=>[f.eventId,...(f.eventIds??[])])),scenePeople=new Set(s.entities.filter(candidate=>candidate.kind==='character'&&candidate.data.locationId===location&&!candidate.archived).map(candidate=>candidate.id)),relations=new Set(s.entities.filter(candidate=>candidate.kind==='relationship'&&!candidate.archived&&(candidate.data.fromId===observerId||candidate.data.toId===observerId)).map(candidate=>candidate.id)),queryLower=query.toLowerCase(),queryTags=new Set(queryLower.split(/\W+/).filter(Boolean));
 if(!within(now,d.validFrom,d.validUntil))return {active:false,reason:d.validUntil&&Date.parse(d.validUntil)<=now?'expired':'not-yet-valid',activatesWhen:d.activation,deactivatesWhen:d.deactivation};
 const scope=d.scope,hasAttachment=scope.placeIds.length+scope.peopleIds.length+scope.relationshipIds.length+scope.eventIds.length+scope.factionIds.length>0,scopeChecks=[scope.placeIds.includes(location??''),scope.peopleIds.some(id=>id===observerId||scenePeople.has(id)),scope.relationshipIds.some(id=>relations.has(id)),scope.eventIds.some(id=>events.has(id)),scope.factionIds.some(id=>observer.factionIds.includes(id))];
 if(hasAttachment&&scope.campaign!==true&&!scopeChecks.some(Boolean))return {active:false,reason:'scope-mismatch',activatesWhen:d.activation,deactivatesWhen:d.deactivation};
 const activation=d.activation,checks=activation?[!activation.from||Date.parse(activation.from)<=now,!activation.until||Date.parse(activation.until)>now,!activation.locationId||activation.locationId===location,!activation.characterId||activation.characterId===observerId,!activation.placeIds.length||activation.placeIds.includes(location??''),!activation.peopleIds.length||activation.peopleIds.some(id=>id===observerId||scenePeople.has(id)),!activation.relationshipIds.length||activation.relationshipIds.some(id=>relations.has(id)),!activation.eventIds.length||activation.eventIds.some(id=>events.has(id)),!activation.factionIds.length||activation.factionIds.some(id=>observer.factionIds.includes(id)),!activation.keywords.length||activation.keywords.some(keyword=>queryLower.includes(keyword.toLowerCase())),!activation.requiredTags.length||activation.requiredTags.every(tag=>queryTags.has(tag.toLowerCase()))]:[true];
 const active=activation?.mode==='any'?checks.some(Boolean):checks.every(Boolean);if(!active)return {active:false,reason:'activation-conditions-unmet',activatesWhen:activation,deactivatesWhen:d.deactivation};
 const deactivation=d.deactivation,deactivationChecks=[!!deactivation.at&&Date.parse(deactivation.at)<=now,!!deactivation.eventIds.length&&deactivation.eventIds.some(id=>events.has(id)),!!deactivation.keywords.length&&deactivation.keywords.some(keyword=>queryLower.includes(keyword.toLowerCase())),!!deactivation.tags.length&&deactivation.tags.some(tag=>queryTags.has(tag.toLowerCase()))],configuredDeactivation=deactivationChecks.filter((_,index)=>index===0?!!deactivation.at:index===1?!!deactivation.eventIds.length:index===2?!!deactivation.keywords.length:!!deactivation.tags.length),deactivated=deactivation.mode==='any'?configuredDeactivation.some(Boolean):deactivation.mode==='all'&&configuredDeactivation.length>0&&configuredDeactivation.every(Boolean);
 return {active:!deactivated,reason:deactivated?'deactivated':'active',activatesWhen:activation,deactivatesWhen:deactivation};
}
const memoryRecallMatches=(s:State,memory:State['memories'][number],query:string,filters:ReturnType<typeof normalizedFilters>)=>{const conditions=memory.recallConditions;if(!conditions)return true;const now=Date.parse(s.clock),location=data(getEntity(s,memory.observerId,'character'),'character').locationId,queryTerms=new Set(query.toLowerCase().split(/\W+/).filter(Boolean)),filterEntities=[...filters.entityIds,...filters.placeIds,...filters.personIds,...filters.relationshipIds,...filters.evidenceIds,...filters.factionIds];return within(now,conditions.from,conditions.until)&&(!conditions.locationId||conditions.locationId===location)&&(!conditions.entityIds.length||conditions.entityIds.some(id=>filterEntities.includes(id)))&&(!conditions.tags.length||conditions.tags.some(tag=>queryTerms.has(tag.toLowerCase())||filters.tags.includes(tag.toLowerCase())));};
export function retrieve(s:State,observerId:string,query:string,limit=12,queryEmbedding:number[]=[],rawFilters:RetrievalFilters={},developer=false){
 const view=observerView(s,observerId),terms=query.toLowerCase().split(/\W+/).filter(Boolean),filters=normalizedFilters(rawFilters),localQuery=queryEmbedding.length?queryEmbedding:embedText(query),visibleIds=new Set(view.entities.map(entity=>entity.id));
 const visibleCandidates=view.entities.filter(e=>['lore','storycard'].includes(e.kind)).filter(e=>matchesFilters(s,e,filters)),rejected:Array<{id:string;reason:string;kind:string}>=[];
 const rows:Array<{id:string;name:string;text:unknown;source:string;score:number;provenance:{kind:string;revision:string|number;visibility:string;sourceRefs:unknown[];links:unknown[];validFrom:string|null;validUntil:string|null;activation:unknown;matched:{lexical:number;semantic:number;structured:number}}}>=visibleCandidates.flatMap(e=>{const source=data(getEntity(s,e.id),e.kind as 'lore'|'storycard'),state=storyCardState(e,s,observerId,query);if(!state.active){if(developer)rejected.push({id:e.id,reason:state.reason,kind:e.kind});return [];}const candidateEmbedding=source.embedding.length===localQuery.length?source.embedding:embedText(source.description+' '+source.tags.join(' '),localQuery.length),semantic=cosine(localQuery,candidateEmbedding),body=(e.name+' '+e.data.description+' '+source.tags.join(' ')).toLowerCase(),lexical=terms.filter(term=>body.includes(term)).length,structured=Object.values(filters).some(value=>Array.isArray(value)?value.length:Boolean(value))?1:0;return [{id:e.id,name:e.name,text:e.data.description,source:source.source,score:lexical+Math.max(0,semantic)+source.priority+structured,provenance:{kind:e.kind,revision:e.revision,visibility:e.visibility,sourceRefs:source.sourceRefs,links:source.linkDetails,validFrom:source.validFrom,validUntil:source.validUntil,activation:state,matched:{lexical,semantic,structured}}}];});
 if(developer)for(const entity of s.entities.filter(e=>['lore','storycard'].includes(e.kind)&&!e.archived&&!visibleIds.has(e.id)&&matchesFilters(s,e,filters)))rejected.push({id:entity.id,reason:'permission-filtered',kind:entity.kind});
 if(!filters.kinds.length||filters.kinds.includes('canon'))rows.push(...canonSources(s).filter(row=>!filters.entityIds.length||filters.entityIds.includes(row.id)).map(row=>({...row,score:terms.filter(term=>(row.name+' '+row.text).toLowerCase().includes(term)).length,provenance:{kind:'canon' as const,revision:row.source,visibility:'campaign' as const,sourceRefs:[],links:[],validFrom:null,validUntil:null,activation:{active:true,reason:'timeline-bound-canon',activatesWhen:null,deactivatesWhen:null},matched:{lexical:terms.filter(term=>(row.name+' '+row.text).toLowerCase().includes(term)).length,semantic:0,structured:filters.entityIds.length?1:0}}})));
 rows.sort((a,b)=>b.score-a.score||a.id.localeCompare(b.id));rows.splice(Math.min(limit,50));
 const beliefRows=view.beliefs.filter(b=>(!filters.personIds.length||!!b.subjectId&&filters.personIds.includes(b.subjectId))&&(!filters.entityIds.length||[b.subjectId,b.objectId].some(id=>!!id&&filters.entityIds.includes(id)))&&(!filters.eventIds.length||overlaps(b.eventIds,filters.eventIds))&&(!filters.evidenceIds.length||overlaps(b.evidenceIds,filters.evidenceIds))&&(!filters.tags.length||filters.tags.every(tag=>(b.tags??[]).map(value=>value.toLowerCase()).includes(tag)))&&(!filters.from||!b.validUntil||Date.parse(b.validUntil)>=Date.parse(filters.from))&&(!filters.until||!b.validFrom||Date.parse(b.validFrom)<=Date.parse(filters.until))&&(!terms.length||terms.some(term=>(b.proposition+' '+b.predicate+' '+JSON.stringify(b.value)).toLowerCase().includes(term)))).sort((a,b)=>b.confidence-a.confidence||a.id.localeCompare(b.id)).slice(0,limit);
 const memoryRows=view.memories.filter(m=>m.currentSalience>0&&memoryRecallMatches(s,m,query,filters)&&(!filters.eventIds.length||overlaps(m.eventRefs??[m.eventId],filters.eventIds))&&(!filters.tags.length||filters.tags.every(tag=>(m.tags??[]).map(value=>value.toLowerCase()).includes(tag)))&&(!filters.from||!m.expiresAt||Date.parse(m.expiresAt)>=Date.parse(filters.from))&&(!filters.until||Date.parse(m.at)<=Date.parse(filters.until))).map(m=>{const text=m.text+' '+(m.interpretation??''),semantic=cosine(localQuery,embedText(text,localQuery.length)),lexical=terms.filter(term=>text.toLowerCase().includes(term)).length;return {...m,retrievalScore:m.currentSalience+Math.max(0,semantic)+lexical};}).sort((a,b)=>b.retrievalScore-a.retrievalScore||a.id.localeCompare(b.id)).slice(0,limit);
 return {sources:rows,beliefs:beliefRows,memories:memoryRows,contradictions:view.beliefs.filter(b=>b.correctedBy).map(b=>({beliefId:b.id,correctedBy:b.correctedBy})),filters,rejected:developer?rejected.sort((a,b)=>a.id.localeCompare(b.id)):[]};
}
