import {createHash,randomUUID} from 'node:crypto';
import {data,getEntity,validateEntity} from './model.ts';
import type {Data,Entity,State} from './model.ts';
import {carriedBy} from './items.ts';
import {phonePowered} from './phone.ts';

type CityEffect={id:string;text:string;observers:string[];type:string;subjectId:string};
type DeliveryChannel=Data<'factionOrder'>['channel'];
const clamp=(value:number)=>Math.max(0,Math.min(100,value));
const deterministicUuid=(seed:string):ReturnType<typeof randomUUID>=>{const hex=createHash('sha256').update(seed).digest('hex');return (hex.slice(0,8)+'-'+hex.slice(8,12)+'-4'+hex.slice(13,16)+'-'+((parseInt(hex[16]!,16)&3)|8).toString(16)+hex.slice(17,20)+'-'+hex.slice(20,32)) as ReturnType<typeof randomUUID>;};
const set=(entity:Entity,value:unknown)=>{entity.data=value as Entity['data'];};
const currentMember=(status:Data<'faction'>['memberships'][number]['status'])=>['probationary','active','suspended'].includes(status);

function usablePhone(s:State,characterId:string,targetId:string){
 return s.entities.some(entity=>{if(entity.kind!=='item'||entity.archived||!carriedBy(s,entity,characterId)||!phonePowered(entity))return false;const item=data(entity,'item');return item.contacts.some(contact=>contact.characterId===targetId&&!contact.blocked&&contact.permissions.calls);});
}
function radio(s:State,characterId:string){return s.entities.some(entity=>entity.kind==='item'&&!entity.archived&&carriedBy(s,entity,characterId)&&data(entity,'item').tags.includes('radio'));}
export function factionDeliveryAvailable(s:State,fromId:string,toId:string,channel:DeliveryChannel|'media'){
 const from=data(getEntity(s,fromId,'character'),'character'),to=data(getEntity(s,toId,'character'),'character');if(from.condition!=='conscious'||to.condition!=='conscious')return false;
 if(channel==='meeting'||channel==='in-person')return !!from.locationId&&from.locationId===to.locationId;
 if(channel==='phone')return usablePhone(s,fromId,toId)&&s.entities.some(entity=>entity.kind==='item'&&!entity.archived&&carriedBy(s,entity,toId)&&phonePowered(entity,true));
 if(channel==='message')return s.entities.some(entity=>entity.kind==='message'&&!entity.archived&&entity.data.fromId===fromId&&entity.data.toId===toId&&['delivered','read'].includes(String(entity.data.status)));
 if(channel==='radio')return radio(s,fromId)&&radio(s,toId);
 return false;
}

export function deliverFactionOrder(s:State,input:{factionId:string;issuerId:string;recipientIds:string[];goalId?:string|null;summary:string;channel:DeliveryChannel;eventId:string;at?:string;expiresAt?:string|null}){
 const faction=getEntity(s,input.factionId,'faction'),f=data(faction,'faction'),issuer=getEntity(s,input.issuerId,'character'),at=input.at??s.clock,authorized=f.leaderId===issuer.id||f.memberships.some(row=>row.characterId===issuer.id&&currentMember(row.status)&&(!row.rankId||f.hierarchy.some(rank=>rank.id===row.rankId&&rank.authority>0)));if(!authorized)throw new Error('faction_order_authority_required');
 const recipients=[...new Set(input.recipientIds)].map(id=>getEntity(s,id,'character')),deliveries=recipients.filter(recipient=>factionDeliveryAvailable(s,issuer.id,recipient.id,input.channel)).map(recipient=>({recipientId:recipient.id,deliveredAt:at,locationId:data(issuer,'character').locationId,messageId:null,proof:input.channel+' delivery path validated'})),known=[issuer.id,...deliveries.map(row=>row.recipientId)],id=deterministicUuid([input.eventId,input.factionId,input.issuerId,input.goalId??'',input.summary,input.channel,at].join('|'));
 let order=s.entities.find(entity=>entity.id===id&&entity.kind==='factionOrder');if(order)return order;order=validateEntity({id,kind:'factionOrder',name:'Order: '+input.summary.slice(0,120),visibility:'knowledge',data:{factionId:faction.id,issuerId:issuer.id,recipientIds:recipients.map(row=>row.id),goalId:input.goalId??null,summary:input.summary,channel:input.channel,issuedAt:at,expiresAt:input.expiresAt??null,deliveries,status:deliveries.length===recipients.length?'delivered':deliveries.length?'partial':'pending',knownByIds:known}});s.entities.push(order);return order;
}

export function createRumor(s:State,input:{sourceCharacterId?:string|null;sourceFactionId?:string|null;subjectId?:string|null;proposition:string;confidence?:number;truthRelation?:Data<'rumor'>['truthRelation'];public?:boolean;characterIds?:string[];factionIds?:string[];locationIds?:string[];knownByIds?:string[];eventId:string;at?:string;correctsRumorId?:string|null}){
 const at=input.at??s.clock,id=deterministicUuid([input.eventId,input.sourceCharacterId??'',input.sourceFactionId??'',input.proposition,at,input.correctsRumorId??''].join('|')),known=[...new Set([...(input.knownByIds??[]),...(input.sourceCharacterId?[input.sourceCharacterId]:[])])];let entity=s.entities.find(row=>row.id===id&&row.kind==='rumor');if(entity)return entity;entity=validateEntity({id,kind:'rumor',name:'Rumor: '+input.proposition.slice(0,120),visibility:'knowledge',data:{sourceCharacterId:input.sourceCharacterId??null,sourceFactionId:input.sourceFactionId??null,subjectId:input.subjectId??null,proposition:input.proposition,confidence:clamp(input.confidence??50),truthRelation:input.truthRelation??'unknown',audience:{public:input.public??false,characterIds:input.characterIds??[],factionIds:input.factionIds??[],locationIds:input.locationIds??[]},knownByIds:known,createdAt:at,correctsRumorId:input.correctsRumorId??null}});s.entities.push(entity);return entity;
}

export function spreadRumor(s:State,input:{rumorId:string;fromId:string;toId:string;channel:DeliveryChannel;eventId:string;at?:string}){
 const entity=getEntity(s,input.rumorId,'rumor'),rumor=data(entity,'rumor'),at=input.at??s.clock;if(!rumor.knownByIds.includes(input.fromId))throw new Error('rumor_unknown');if(!factionDeliveryAvailable(s,input.fromId,input.toId,input.channel))throw new Error('rumor_delivery_unavailable');const from=data(getEntity(s,input.fromId,'character'),'character');getEntity(s,input.toId,'character');const confidence=clamp(rumor.confidence*.8);if(!rumor.knownByIds.includes(input.toId))rumor.knownByIds.push(input.toId);rumor.spreadHistory.push({at,fromId:input.fromId,toId:input.toId,channel:input.channel,locationId:from.locationId,messageId:null,confidence});set(entity,rumor);
 if(!s.beliefs.some(belief=>belief.observerId===input.toId&&belief.source==='rumor:'+entity.id))s.beliefs.push({id:deterministicUuid(input.eventId+'|belief|'+entity.id+'|'+input.toId),observerId:input.toId,proposition:rumor.proposition,subjectId:rumor.subjectId,predicate:'rumor',confidence:confidence/100,source:'rumor:'+entity.id,truthStatus:'believed',eventIds:[input.eventId],at,correctedBy:null});return entity;
}

export function correctRumor(s:State,input:{rumorId:string;fromId:string;toId:string;channel:DeliveryChannel;proposition:string;truthRelation?:Data<'rumor'>['truthRelation'];eventId:string;at?:string}){
 const original=getEntity(s,input.rumorId,'rumor'),old=data(original,'rumor');if(!old.knownByIds.includes(input.fromId))throw new Error('rumor_unknown');const correction=createRumor(s,{sourceCharacterId:input.fromId,sourceFactionId:old.sourceFactionId,subjectId:old.subjectId,proposition:input.proposition,confidence:80,truthRelation:input.truthRelation??'unknown',knownByIds:[input.fromId],eventId:input.eventId,at:input.at,correctsRumorId:original.id});spreadRumor(s,{rumorId:correction.id,fromId:input.fromId,toId:input.toId,channel:input.channel,eventId:input.eventId,at:input.at});old.status='corrected';old.correctedByRumorId=correction.id;set(original,old);for(const belief of s.beliefs.filter(row=>row.observerId===input.toId&&row.source==='rumor:'+original.id)){belief.truthStatus='doubted';belief.correctedBy=null;}return correction;
}

function causeText(faction:Data<'faction'>,hook:Data<'faction'>['eventHooks'][number]){const goal=hook.goalId?faction.goals.find(row=>row.id===hook.goalId):null,incidents=faction.knownIncidentIds.length+' known incident'+(faction.knownIncidentIds.length===1?'':'s'),resources=Object.entries(faction.resources).map(([key,value])=>key+' '+value).join(', ')||'no configured resource pool';return (goal?'Goal “'+goal.summary+'”; ':'')+'pressure '+faction.pressure+'; '+incidents+'; resources '+resources+'.';}
function eligibleHook(s:State,faction:Data<'faction'>,at:number){return [...faction.eventHooks].filter(hook=>hook.enabled&&faction.pressure>=hook.minimumPressure&&faction.pressure<=hook.maximumPressure&&(!hook.lastFiredAt||at-Date.parse(hook.lastFiredAt)>=hook.cooldownMinutes*60000)&&(!hook.goalId||faction.goals.some(goal=>goal.id===hook.goalId&&goal.status==='active'))&&hook.treasuryCostCents<=faction.treasuryCents&&Object.entries(hook.resourceCosts).every(([key,cost])=>(faction.resources[key]??0)>=cost)&&(!hook.locationId||faction.territoryIds.includes(hook.locationId))&&(!hook.targetFactionId||s.entities.some(entity=>entity.id===hook.targetFactionId&&entity.kind==='faction'&&!entity.archived))).sort((a,b)=>b.priority-a.priority||a.id.localeCompare(b.id))[0]??null;}

export function advanceFactions(s:State,start:number,end:number,eventId:string,effects:CityEffect[]){
 for(const entity of s.entities.filter(row=>row.kind==='faction'&&!row.archived).sort((a,b)=>a.id.localeCompare(b.id))){const faction=data(entity,'faction'),policy=faction.simulationPolicy;if(!policy?.enabled||!faction.leaderId)continue;const previous=faction.lastFactionAt?Date.parse(faction.lastFactionAt):start,total=Math.floor((end-previous)/(policy.intervalMinutes*60000)),steps=Math.min(total,policy.maxEventsPerAdvance);if(!faction.lastFactionAt)faction.lastFactionAt=new Date(start).toISOString();if(steps<1){set(entity,faction);continue;}let processed=0;
  for(let index=1;index<=steps;index++){const at=previous+index*policy.intervalMinutes*60000,atIso=new Date(at).toISOString(),hook=eligibleHook(s,faction,at);processed++;if(!hook)continue;const leader=getEntity(s,faction.leaderId,'character'),leaderData=data(leader,'character');if(leaderData.playable||leaderData.condition!=='conscious')continue;const target=hook.targetCharacterId?s.entities.find(row=>row.id===hook.targetCharacterId&&row.kind==='character'&&!row.archived):faction.memberships.filter(row=>currentMember(row.status)&&row.characterId!==leader.id).map(row=>s.entities.find(candidate=>candidate.id===row.characterId&&candidate.kind==='character'&&!candidate.archived)).filter((row):row is Entity=>!!row&&row.data.condition==='conscious'&&!row.data.playable).sort((a,b)=>a.id.localeCompare(b.id))[0]??null;let order:Entity|null=null,deliveredIds:string[]=[];
   if(hook.requiresOrder){if(hook.delivery==='media'||!target)continue;order=deliverFactionOrder(s,{factionId:entity.id,issuerId:leader.id,recipientIds:[target.id],goalId:hook.goalId,summary:hook.summary,channel:hook.delivery,eventId,at:atIso,expiresAt:new Date(at+hook.cooldownMinutes*60000).toISOString()});const orderData=data(order,'factionOrder');deliveredIds=orderData.deliveries.map(row=>row.recipientId);if(!deliveredIds.length)continue;}else if(target&&factionDeliveryAvailable(s,leader.id,target.id,hook.delivery))deliveredIds=[target.id];
   faction.treasuryCents-=hook.treasuryCostCents;for(const [key,cost] of Object.entries(hook.resourceCosts))faction.resources[key]=clamp((faction.resources[key]??0)-cost);faction.pressure=clamp(faction.pressure+hook.pressureDelta);faction.cohesion=clamp(faction.cohesion+hook.cohesionDelta);const known=[...new Set([...hook.knownByIds,leader.id,...deliveredIds])],targetIds=[...(target?[target.id]:[]),...(hook.businessId?[hook.businessId]:[])],affectedFactionIds=hook.targetFactionId?[hook.targetFactionId]:[];let rumor:Entity|null=null;
   if(hook.outcome==='recruitment'&&target&&!faction.memberships.some(row=>row.characterId===target.id))faction.memberships.push({characterId:target.id,rankId:null,status:'invited',public:false,joinedAt:null,endedAt:null,knownByIds:[leader.id,target.id],note:hook.summary});
   if(hook.outcome==='rumor'){rumor=createRumor(s,{sourceCharacterId:leader.id,sourceFactionId:entity.id,subjectId:hook.targetCharacterId??hook.targetFactionId,proposition:hook.rumorText||hook.summary,confidence:70,truthRelation:hook.rumorTruth,public:hook.delivery==='media',factionIds:[entity.id],locationIds:hook.locationId?[hook.locationId]:[],knownByIds:known,eventId,at:atIso});for(const recipientId of deliveredIds)if(recipientId!==leader.id&&!data(rumor,'rumor').spreadHistory.some(row=>row.toId===recipientId))spreadRumor(s,{rumorId:rumor.id,fromId:leader.id,toId:recipientId,channel:hook.delivery as DeliveryChannel,eventId,at:atIso});}
   if(['feud-escalation','retaliation'].includes(hook.outcome)&&hook.targetFactionId){let relation=faction.relations.find(row=>row.factionId===hook.targetFactionId);if(!relation){relation={factionId:hook.targetFactionId,status:'rival',trust:0,tension:0,favorBalance:0,public:false,knownByIds:known,lastChangedAt:null,reason:''};faction.relations.push(relation);}relation.tension=clamp(relation.tension+(hook.relationTensionDelta||10));relation.status=relation.tension>=70?'feud':relation.tension>=40?'hostile':'rival';relation.lastChangedAt=atIso;relation.reason=hook.summary;relation.knownByIds=[...new Set([...relation.knownByIds,...known])];}
   if(hook.outcome==='retreat'&&hook.locationId)faction.territoryIds=faction.territoryIds.filter(id=>id!==hook.locationId);
   if(hook.outcome==='business-change'&&hook.businessId&&hook.treasuryCostCents>0){const business=getEntity(s,hook.businessId,'business'),b=data(business,'business');b.cash+=hook.treasuryCostCents;set(business,b);}
   hook.lastFiredAt=atIso;const cause=causeText(faction,hook),eventEntity=validateEntity({id:deterministicUuid([eventId,entity.id,hook.id,atIso].join('|')),kind:'factionEvent',name:entity.name+': '+hook.outcome,visibility:hook.publicStory?'campaign':'knowledge',data:{factionId:entity.id,hookId:hook.id,outcome:hook.outcome,actorIds:[leader.id,...deliveredIds],targetIds,affectedFactionIds,locationId:hook.locationId??leaderData.locationId,orderId:order?.id??null,rumorId:rumor?.id??null,occurredAt:atIso,cooldownUntil:new Date(at+hook.cooldownMinutes*60000).toISOString(),cause:{summary:cause,goalId:hook.goalId,pressure:faction.pressure,resources:{...faction.resources},incidentIds:[...faction.knownIncidentIds]},summary:hook.summary,publicStory:hook.publicStory,knownByIds:known}});if(!s.entities.some(row=>row.id===eventEntity.id))s.entities.push(eventEntity);faction.history.push({at:atIso,eventId,hookId:hook.id,outcome:hook.outcome,summary:hook.summary,cause,locationId:hook.locationId??leaderData.locationId,targetIds});if(faction.history.length>5000)faction.history.splice(0,faction.history.length-5000);if(hook.publicStory){const observers=s.entities.filter(row=>row.kind==='character'&&!row.archived&&row.data.locationId===eventEntity.data.locationId).map(row=>row.id);effects.push({id:deterministicUuid(eventEntity.id+'|effect'),text:hook.publicStory,observers,type:'faction.'+hook.outcome,subjectId:eventEntity.id});}}
  faction.lastFactionAt=new Date(previous+processed*policy.intervalMinutes*60000).toISOString();set(entity,faction);
 }
}
