import {informationExtensionFields} from './information-extensions.ts';
import {z} from 'zod';

const id=z.uuid(),ids=z.array(id).max(10000),text=z.string().max(16000),at=z.iso.datetime(),unit=z.number().min(0).max(1);
export const informationPurposeSchema=z.enum(['narration','npc-planner','dialogue','input-parser','knowledge-query','recap','research','investigation','memory-consolidation','validator','creator']);
export type InformationPurpose=z.infer<typeof informationPurposeSchema>;
export const propositionSchema=z.strictObject({id,subjectId:id.nullable(),predicate:z.string().min(1).max(160),value:z.json(),qualifiers:z.record(z.string(),z.json()).default({}),validFrom:at,validTo:at.nullable().default(null),truth:z.enum(['true','false','unknown','disputed','partial','historical']),authority:z.number().int().min(0).max(100).default(0),intentionallyDisputed:z.boolean().default(false),secrecy:z.enum(['public','character','group','institution','faction','private','creator','system','spoiler']).default('private'),sourceIds:ids.default([])});
export const informationEntrySchema=z.strictObject({id,characterId:id,propositionId:id,type:z.enum(['knowledge','belief','suspicion','rumor','inference']),confidence:unit,acquisition:z.enum(['observation','testimony','overheard','rumor','record','research','recognition','inference','player-belief','briefing','background','creator']),sourceId:id,originIds:ids,acquiredAt:at,informationAt:at,lastConfirmedAt:at.nullable(),freshness:z.enum(['current','recent','last_known','stale','historical','superseded']),status:z.enum(['active','superseded','abandoned','invalidated']),secrecyAwareness:z.enum(['unknown','sensitive','secret']),supersedesId:id.nullable(),text});
export const observationSchema=z.strictObject({id,observerId:id,eventId:id,at,locationId:id.nullable(),channel:z.enum(['vision','hearing','smell','touch','taste','bodily','reading','technical','recording']),targetId:id.nullable(),raw:text,clarity:unit,confidence:unit,attention:z.enum(['focused','normal','divided','distracted','overwhelmed','unaware']),conditions:z.record(z.string(),z.json()),recognition:z.enum(['unidentified','familiar','likely','recognized','confident']),recognizedAsId:id.nullable(),salience:unit,propositionIds:ids});
export const transmissionSchema=z.strictObject({id,senderId:id.nullable(),intendedRecipientIds:ids,propositionIds:ids,text,channel:z.enum(['face-to-face','overheard','phone','voicemail','sms','email','letter','social','speech','broadcast','dispatch','briefing','record','rumor']),at,secrecy:z.boolean(),parentId:id.nullable(),originIds:ids,mutation:text,sourceEntryIds:ids.default([]),artifactId:id.nullable(),recipients:z.array(z.strictObject({characterId:id,deliveredAt:at.nullable(),exposedAt:at.nullable(),comprehension:unit,acceptance:unit})).max(10000)});
export const informationRecordSchema=z.strictObject({id,title:z.string().max(200),text,propositionIds:ids,createdAt:at,informationAt:at,validUntil:at.nullable(),scope:z.enum(['public','private','institution','faction']),allowedCharacterIds:ids,requiredItemIds:ids,requiredTags:z.array(z.string().max(100)).max(100),locationId:id.nullable(),supersedesId:id.nullable(),sourceIds:ids,misuseCharacterIds:ids.default([]),custodyItemId:id.nullable().default(null),sealed:z.boolean().default(false)});
export const activeInformationSchema=z.strictObject({id,characterId:id,kind:z.enum(['question','promise','threat','message','lead','plan','meeting','injury','thread','hypothesis','note','ooc-note']),text,status:z.enum(['open','pending','waiting','resolved','failed','canceled','expired','verified','disproved','stale']),sourceIds:ids,contradictsIds:ids,entityIds:ids,confidence:unit,at,updatedAt:at,exact:z.boolean(),history:z.array(z.strictObject({at,status:z.string(),confidence:unit,sourceIds:ids,contradictsIds:ids})).optional()});
export const informationSummarySchema=z.strictObject({id,viewerId:id,level:z.enum(['scene','thread','relationship','character','campaign','location','storyline','period']),key:z.string().max(200),sourceIds:ids,sourceHash:z.string(),version:z.number().int(),eventCursor:z.string(),generatedAt:at,text,anchors:ids});
export const informationConflictSchema=z.strictObject({id,a:id,b:id,type:z.enum(['truth','temporal','perspective','belief','source','identity','memory','canon','timeline','integrity']),status:z.enum(['open','disputed','resolved']),at,resolutionSourceId:id.nullable()});
export const informationStateSchema=z.strictObject({...informationExtensionFields,version:z.literal(1).default(1),generation:z.number().int().nonnegative().default(0),propositions:z.array(propositionSchema).default([]),entries:z.array(informationEntrySchema).default([]),observations:z.array(observationSchema).default([]),transmissions:z.array(transmissionSchema).default([]),records:z.array(informationRecordSchema).default([]),active:z.array(activeInformationSchema).default([]),summaries:z.array(informationSummarySchema).default([]),conflicts:z.array(informationConflictSchema).default([]),attempts:z.array(z.strictObject({key:z.string(),observerId:id,eventId:id,at})).default([]),accessLog:z.array(z.strictObject({id,characterId:id,recordIds:ids,query:text,at,unauthorized:z.boolean(),minutes:z.number()})).default([]),cohorts:z.array(z.strictObject({id,label:z.string().max(200),transmissionIds:ids,exposure:unit})).default([]),canaries:z.array(z.strictObject({id,text,aliases:z.array(text)})).default([])});
export type InformationState=z.infer<typeof informationStateSchema>;
export type InformationEntry=z.infer<typeof informationEntrySchema>;
