import type {BankEntry,PriceBasis} from './master-bank-types.ts';

const SOURCE_URL='https://www.atf.gov/firearms/firearms-guides-importation-verification-firearms-ammunition-gun-control-act-definition';
const SOURCE={label:'Period manufacturer specifications and US firearm reference data',url:SOURCE_URL,recordId:'model-specification',notes:'Model identity, action, cartridge and standard capacity follow period specifications. Prices are representative 2012 US retail or used-market values, not a claim of local availability or legality.'};
type Firearm={slug:string;name:string;family:'Firearms: handguns'|'Firearms: rifles'|'Firearms: shotguns';caliber:string;capacity:number;price:number;year:number;weight:number;range:number;damage:number;accuracy:number;recoil:number;action:'single-shot'|'bolt-action'|'lever-action'|'pump-action'|'revolver'|'semi-automatic'|'select-fire'|'automatic';velocity:number;magazineFamily:string;basis?:PriceBasis;tags?:string[]};

const firearms:Firearm[]=[
 {slug:'glock-17-gen3',name:'Glock 17 Gen3',family:'Firearms: handguns',caliber:'9x19mm',capacity:17,price:49900,year:1988,weight:.625,range:50,damage:14,accuracy:3,recoil:3,action:'semi-automatic',velocity:375,magazineFamily:'Glock-17'},
 {slug:'glock-19-gen3',name:'Glock 19 Gen3',family:'Firearms: handguns',caliber:'9x19mm',capacity:15,price:49900,year:1988,weight:.595,range:45,damage:14,accuracy:2,recoil:4,action:'semi-automatic',velocity:365,magazineFamily:'Glock-19'},
 {slug:'glock-21-gen3',name:'Glock 21 Gen3',family:'Firearms: handguns',caliber:'.45 ACP',capacity:13,price:54900,year:1990,weight:.745,range:45,damage:18,accuracy:1,recoil:7,action:'semi-automatic',velocity:260,magazineFamily:'Glock-21'},
 {slug:'glock-22-gen3',name:'Glock 22 Gen3',family:'Firearms: handguns',caliber:'.40 S&W',capacity:15,price:49900,year:1990,weight:.65,range:50,damage:16,accuracy:2,recoil:6,action:'semi-automatic',velocity:320,magazineFamily:'Glock-22'},
 {slug:'glock-26-gen3',name:'Glock 26 Gen3',family:'Firearms: handguns',caliber:'9x19mm',capacity:10,price:52900,year:1994,weight:.56,range:35,damage:14,accuracy:0,recoil:6,action:'semi-automatic',velocity:350,magazineFamily:'Glock-26'},
 {slug:'beretta-92fs',name:'Beretta 92FS',family:'Firearms: handguns',caliber:'9x19mm',capacity:15,price:65000,year:1984,weight:.945,range:50,damage:14,accuracy:4,recoil:3,action:'semi-automatic',velocity:381,magazineFamily:'Beretta-92'},
 {slug:'sig-p226',name:'SIG Sauer P226',family:'Firearms: handguns',caliber:'9x19mm',capacity:15,price:90000,year:1984,weight:.964,range:50,damage:14,accuracy:5,recoil:3,action:'semi-automatic',velocity:350,magazineFamily:'SIG-P226'},
 {slug:'sig-p229',name:'SIG Sauer P229',family:'Firearms: handguns',caliber:'.40 S&W',capacity:12,price:95000,year:1992,weight:.905,range:45,damage:16,accuracy:4,recoil:6,action:'semi-automatic',velocity:320,magazineFamily:'SIG-P229'},
 {slug:'cz-75b',name:'CZ 75 B',family:'Firearms: handguns',caliber:'9x19mm',capacity:16,price:60000,year:1993,weight:1,range:50,damage:14,accuracy:5,recoil:3,action:'semi-automatic',velocity:360,magazineFamily:'CZ-75'},
 {slug:'m1911a1',name:'M1911A1-pattern pistol',family:'Firearms: handguns',caliber:'.45 ACP',capacity:7,price:70000,year:1924,weight:1.1,range:50,damage:18,accuracy:4,recoil:7,action:'semi-automatic',velocity:253,magazineFamily:'M1911'},
 {slug:'hk-usp-45',name:'Heckler & Koch USP45',family:'Firearms: handguns',caliber:'.45 ACP',capacity:12,price:85000,year:1995,weight:.887,range:50,damage:18,accuracy:4,recoil:6,action:'semi-automatic',velocity:260,magazineFamily:'HK-USP45'},
 {slug:'fn-five-seven',name:'FN Five-seveN USG',family:'Firearms: handguns',caliber:'5.7x28mm',capacity:20,price:100000,year:2004,weight:.617,range:75,damage:13,accuracy:6,recoil:2,action:'semi-automatic',velocity:650,magazineFamily:'FN-Five-seveN'},
 {slug:'ruger-lcp',name:'Ruger LCP',family:'Firearms: handguns',caliber:'.380 ACP',capacity:6,price:30000,year:2008,weight:.266,range:25,damage:11,accuracy:-2,recoil:6,action:'semi-automatic',velocity:290,magazineFamily:'Ruger-LCP'},
 {slug:'walther-ppk',name:'Walther PPK',family:'Firearms: handguns',caliber:'.380 ACP',capacity:6,price:60000,year:1931,weight:.59,range:30,damage:11,accuracy:0,recoil:5,action:'semi-automatic',velocity:290,magazineFamily:'Walther-PPK'},
 {slug:'smith-wesson-642',name:'Smith & Wesson Model 642',family:'Firearms: handguns',caliber:'.38 Special',capacity:5,price:40000,year:1993,weight:.425,range:25,damage:13,accuracy:-1,recoil:7,action:'revolver',velocity:260,magazineFamily:''},
 {slug:'smith-wesson-686',name:'Smith & Wesson Model 686',family:'Firearms: handguns',caliber:'.357 Magnum',capacity:6,price:70000,year:1981,weight:1.25,range:55,damage:19,accuracy:5,recoil:9,action:'revolver',velocity:440,magazineFamily:''},
 {slug:'ruger-gp100',name:'Ruger GP100',family:'Firearms: handguns',caliber:'.357 Magnum',capacity:6,price:60000,year:1985,weight:1.27,range:55,damage:19,accuracy:4,recoil:9,action:'revolver',velocity:440,magazineFamily:''},
 {slug:'ruger-mark-iii',name:'Ruger Mark III',family:'Firearms: handguns',caliber:'.22 LR',capacity:10,price:35000,year:2004,weight:1.08,range:50,damage:7,accuracy:7,recoil:1,action:'semi-automatic',velocity:330,magazineFamily:'Ruger-Mark-III'},
 {slug:'colt-le6920',name:'Colt LE6920',family:'Firearms: rifles',caliber:'5.56x45mm',capacity:30,price:120000,year:1998,weight:2.95,range:500,damage:24,accuracy:7,recoil:4,action:'semi-automatic',velocity:900,magazineFamily:'STANAG-5.56'},
 {slug:'ruger-mini-14',name:'Ruger Mini-14 Ranch Rifle',family:'Firearms: rifles',caliber:'5.56x45mm',capacity:20,price:75000,year:1973,weight:3.17,range:400,damage:24,accuracy:4,recoil:4,action:'semi-automatic',velocity:900,magazineFamily:'Ruger-Mini-14'},
 {slug:'akm-pattern',name:'AKM-pattern semiautomatic rifle',family:'Firearms: rifles',caliber:'7.62x39mm',capacity:30,price:60000,year:1959,weight:3.5,range:350,damage:25,accuracy:1,recoil:7,action:'semi-automatic',velocity:715,magazineFamily:'AK-7.62'},
 {slug:'ruger-10-22',name:'Ruger 10/22',family:'Firearms: rifles',caliber:'.22 LR',capacity:10,price:25000,year:1964,weight:2.3,range:100,damage:8,accuracy:6,recoil:1,action:'semi-automatic',velocity:390,magazineFamily:'Ruger-10-22'},
 {slug:'remington-700',name:'Remington Model 700',family:'Firearms: rifles',caliber:'.308 Winchester',capacity:4,price:65000,year:1962,weight:3.8,range:800,damage:30,accuracy:10,recoil:10,action:'bolt-action',velocity:820,magazineFamily:''},
 {slug:'winchester-model-70',name:'Winchester Model 70',family:'Firearms: rifles',caliber:'.30-06 Springfield',capacity:5,price:80000,year:1936,weight:3.6,range:800,damage:32,accuracy:9,recoil:11,action:'bolt-action',velocity:850,magazineFamily:''},
 {slug:'marlin-336',name:'Marlin Model 336',family:'Firearms: rifles',caliber:'.30-30 Winchester',capacity:6,price:50000,year:1948,weight:3.18,range:200,damage:25,accuracy:5,recoil:7,action:'lever-action',velocity:730,magazineFamily:''},
 {slug:'springfield-m1a',name:'Springfield Armory M1A',family:'Firearms: rifles',caliber:'7.62x51mm NATO',capacity:20,price:140000,year:1974,weight:4.1,range:700,damage:30,accuracy:7,recoil:10,action:'semi-automatic',velocity:850,magazineFamily:'M14-M1A'},
 {slug:'sks',name:'SKS carbine',family:'Firearms: rifles',caliber:'7.62x39mm',capacity:10,price:35000,year:1945,weight:3.85,range:350,damage:25,accuracy:3,recoil:7,action:'semi-automatic',velocity:735,magazineFamily:'',basis:'2012-used-value'},
 {slug:'mosin-nagant-91-30',name:'Mosin-Nagant M91/30',family:'Firearms: rifles',caliber:'7.62x54mmR',capacity:5,price:12000,year:1930,weight:4,range:600,damage:31,accuracy:4,recoil:12,action:'bolt-action',velocity:865,magazineFamily:'',basis:'2012-used-value'},
 {slug:'barrett-m82a1',name:'Barrett M82A1',family:'Firearms: rifles',caliber:'.50 BMG',capacity:10,price:850000,year:1989,weight:13.5,range:1800,damage:50,accuracy:8,recoil:18,action:'semi-automatic',velocity:853,magazineFamily:'Barrett-M82'},
 {slug:'remington-870',name:'Remington Model 870',family:'Firearms: shotguns',caliber:'12 gauge',capacity:4,price:35000,year:1950,weight:3.2,range:75,damage:26,accuracy:1,recoil:12,action:'pump-action',velocity:400,magazineFamily:''},
 {slug:'mossberg-500',name:'Mossberg 500',family:'Firearms: shotguns',caliber:'12 gauge',capacity:5,price:30000,year:1961,weight:3.3,range:75,damage:26,accuracy:1,recoil:12,action:'pump-action',velocity:400,magazineFamily:''},
 {slug:'mossberg-590',name:'Mossberg 590',family:'Firearms: shotguns',caliber:'12 gauge',capacity:8,price:45000,year:1987,weight:3.4,range:75,damage:26,accuracy:1,recoil:12,action:'pump-action',velocity:400,magazineFamily:''},
 {slug:'benelli-m4',name:'Benelli M4',family:'Firearms: shotguns',caliber:'12 gauge',capacity:5,price:160000,year:1999,weight:3.82,range:80,damage:26,accuracy:3,recoil:10,action:'semi-automatic',velocity:400,magazineFamily:''},
 {slug:'winchester-1300',name:'Winchester Model 1300',family:'Firearms: shotguns',caliber:'12 gauge',capacity:5,price:30000,year:1978,weight:3.06,range:75,damage:26,accuracy:1,recoil:12,action:'pump-action',velocity:400,magazineFamily:'',basis:'2012-used-value'},
 {slug:'saiga-12',name:'Saiga-12',family:'Firearms: shotguns',caliber:'12 gauge',capacity:5,price:70000,year:1997,weight:3.6,range:75,damage:26,accuracy:2,recoil:11,action:'semi-automatic',velocity:400,magazineFamily:'Saiga-12'},
 {slug:'mp5a3-transferable',name:'Heckler & Koch MP5A3 (transferable)',family:'Firearms: rifles',caliber:'9x19mm',capacity:30,price:2000000,year:1971,weight:2.88,range:150,damage:14,accuracy:6,recoil:3,action:'select-fire',velocity:400,magazineFamily:'HK-MP5',basis:'2012-used-value',tags:['nfa-restricted','automatic']},
 {slug:'uzi-transferable',name:'Uzi submachine gun (transferable)',family:'Firearms: rifles',caliber:'9x19mm',capacity:32,price:1200000,year:1954,weight:3.5,range:150,damage:14,accuracy:3,recoil:4,action:'select-fire',velocity:400,magazineFamily:'Uzi-9mm',basis:'2012-used-value',tags:['nfa-restricted','automatic']},
 {slug:'mac-10-transferable',name:'MAC-10 (transferable)',family:'Firearms: handguns',caliber:'.45 ACP',capacity:30,price:400000,year:1970,weight:2.84,range:60,damage:18,accuracy:-4,recoil:12,action:'automatic',velocity:280,magazineFamily:'MAC-10-45',basis:'2012-used-value',tags:['nfa-restricted','automatic']}
];

const ammunition:{caliber:string;types:string[];box:number;price:number;year:number}[]=[
 {caliber:'9x19mm',types:['FMJ','JHP'],box:50,price:1200,year:1902},{caliber:'.45 ACP',types:['FMJ','JHP'],box:50,price:1800,year:1905},{caliber:'.40 S&W',types:['FMJ','JHP'],box:50,price:1600,year:1990},{caliber:'.380 ACP',types:['FMJ','JHP'],box:50,price:1600,year:1908},{caliber:'.38 Special',types:['lead-round-nose','JHP'],box:50,price:1700,year:1898},{caliber:'.357 Magnum',types:['FMJ','JHP'],box:50,price:2200,year:1935},{caliber:'.22 LR',types:['lead-round-nose','hollow-point'],box:100,price:700,year:1887},{caliber:'5.7x28mm',types:['FMJ','JHP'],box:50,price:2400,year:1990},{caliber:'5.56x45mm',types:['FMJ','soft-point'],box:20,price:900,year:1963},{caliber:'7.62x39mm',types:['FMJ','soft-point'],box:20,price:700,year:1943},{caliber:'.308 Winchester',types:['FMJ','soft-point'],box:20,price:1800,year:1952},{caliber:'.30-06 Springfield',types:['FMJ','soft-point'],box:20,price:1900,year:1906},{caliber:'.30-30 Winchester',types:['flat-point','soft-point'],box:20,price:1700,year:1895},{caliber:'7.62x51mm NATO',types:['FMJ','match'],box:20,price:1800,year:1954},{caliber:'7.62x54mmR',types:['FMJ','soft-point'],box:20,price:900,year:1891},{caliber:'.50 BMG',types:['FMJ','match'],box:10,price:4500,year:1921},{caliber:'12 gauge',types:['00 buckshot','rifled slug','birdshot'],box:25,price:1800,year:1870}
];

const melee=[
 {slug:'baseball-bat',name:'Wood baseball bat',price:2999,year:1850,weight:.9,range:2,damage:10,accuracy:1,recoil:3},
 {slug:'aluminum-bat',name:'Aluminum baseball bat',price:6999,year:1970,weight:.85,range:2,damage:10,accuracy:2,recoil:2},
 {slug:'crowbar-weapon',name:'Steel crowbar',price:2999,year:1900,weight:2.4,range:2,damage:12,accuracy:-1,recoil:6},
 {slug:'kitchen-knife',name:'Kitchen knife',price:2499,year:1800,weight:.2,range:1.5,damage:9,accuracy:2,recoil:1},
 {slug:'folding-knife',name:'Folding pocket knife',price:3999,year:1900,weight:.12,range:1.2,damage:7,accuracy:1,recoil:1},
 {slug:'police-baton',name:'Expandable baton',price:5999,year:1980,weight:.55,range:2,damage:9,accuracy:3,recoil:2},
 {slug:'machete',name:'Machete',price:2999,year:1800,weight:.6,range:2,damage:13,accuracy:0,recoil:5},
 {slug:'pepper-spray',name:'Pocket pepper spray',price:1299,year:1980,weight:.08,range:3,damage:3,accuracy:2,recoil:0},
 {slug:'civilian-stun-gun',name:'Civilian stun gun',price:4999,year:1983,weight:.25,range:1,damage:5,accuracy:0,recoil:0}
];

const ammoTypes=(caliber:string)=>ammunition.find(row=>row.caliber===caliber)?.types??[];
const introduced=(year:number)=>String(year).padStart(4,'0')+'-01-01';
const firearmEntries:BankEntry[]=firearms.map(spec=>{const id='weapon:'+spec.slug,basis=spec.basis??'2012-typical-retail';return {id,kind:'weapon',category:'firearm',name:spec.name,variant:spec.caliber+' · '+spec.action,introducedOn:introduced(spec.year),price2012Cents:spec.price,priceBasis:basis,priceConfidence:'medium',source:SOURCE,template:{kind:'item',name:spec.name,visibility:'creator',data:{description:spec.name+' in '+spec.caliber+' with period-standard '+spec.capacity+'-round capacity.',tags:['2012-master-bank','firearm',...(spec.tags??[])],bankId:id,introducedOn:introduced(spec.year),price:spec.price,priceBasis:basis,priceSource:SOURCE.url,priceConfidence:'medium',category:'firearm',weight:spec.weight,caliber:spec.caliber,magazine:spec.capacity,loaded:0,weaponFamily:spec.family,ammoType:'',compatibleAmmoTypes:ammoTypes(spec.caliber),magazineFamily:spec.magazineFamily,compatibleMagazineFamilies:spec.magazineFamily?[spec.magazineFamily]:[],chamberState:'empty',damage:spec.damage,accuracyModifier:spec.accuracy,recoilPenalty:spec.recoil,actionType:spec.action,fireModes:spec.action==='select-fire'?['semi-automatic','automatic']:spec.action==='automatic'?['automatic']:[spec.action],muzzleVelocityMps:spec.velocity,rangeMeters:spec.range}}};});

const ammoEntries:BankEntry[]=ammunition.flatMap(spec=>spec.types.map(type=>{const slug=(spec.caliber+'-'+type).toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,''),id='weapon:ammo-'+slug,unit=Math.max(1,Math.round(spec.price/spec.box));return {id,kind:'weapon',category:'ammo',name:spec.caliber+' '+type,variant:spec.box+' rounds',introducedOn:introduced(spec.year),price2012Cents:spec.price,priceBasis:'2012-typical-retail',priceConfidence:'medium',source:SOURCE,template:{kind:'item',name:spec.caliber+' '+type+' ('+spec.box+')',visibility:'creator',data:{description:spec.box+'-round 2012 retail box.',tags:['2012-master-bank','ammunition'],bankId:id,introducedOn:introduced(spec.year),price:unit,priceBasis:'2012-typical-retail',priceSource:SOURCE.url,priceConfidence:'medium',category:'ammo',quantity:spec.box,caliber:spec.caliber,ammoType:type}}};}));

const magazineEntries:BankEntry[]=firearms.filter(spec=>spec.magazineFamily).map(spec=>{const id='weapon:magazine-'+spec.slug,price=Math.min(8000,Math.max(2000,Math.round(spec.price*.06)));return {id,kind:'weapon',category:'magazine',name:spec.name+' magazine',variant:spec.capacity+' rounds',introducedOn:introduced(spec.year),price2012Cents:price,priceBasis:'2012-typical-retail',priceConfidence:'medium',source:SOURCE,template:{kind:'item',name:spec.name+' magazine',visibility:'creator',data:{description:'Detachable '+spec.capacity+'-round magazine for '+spec.name+'.',tags:['2012-master-bank','magazine'],bankId:id,introducedOn:introduced(spec.year),price,priceBasis:'2012-typical-retail',priceSource:SOURCE.url,priceConfidence:'medium',category:'magazine',quantity:1,caliber:spec.caliber,magazineFamily:spec.magazineFamily,magazine:spec.capacity,loaded:0}}};});

const meleeEntries:BankEntry[]=melee.map(spec=>{const id='weapon:'+spec.slug;return {id,kind:'weapon',category:'weapon',name:spec.name,variant:'melee',introducedOn:introduced(spec.year),price2012Cents:spec.price,priceBasis:'2012-typical-retail',priceConfidence:'medium',source:SOURCE,template:{kind:'item',name:spec.name,visibility:'creator',data:{description:'Common pre-2012 hand weapon or improvised weapon.',tags:['2012-master-bank','melee-weapon'],bankId:id,introducedOn:introduced(spec.year),price:spec.price,priceBasis:'2012-typical-retail',priceSource:SOURCE.url,priceConfidence:'medium',category:'weapon',weight:spec.weight,weaponFamily:'Melee',damage:spec.damage,accuracyModifier:spec.accuracy,recoilPenalty:spec.recoil,actionType:'none',rangeMeters:spec.range}}};});

export const weaponBank=[...firearmEntries,...ammoEntries,...magazineEntries,...meleeEntries];
if(new Set(weaponBank.map(entry=>entry.id)).size!==weaponBank.length)throw new Error('duplicate_master_bank_weapon_id');
