import {z} from 'zod';
import type {FastifyInstance,FastifyRequest} from 'fastify';
import {Game} from './engine.ts';
import {dataSchemas,kinds,actionSchema} from './model.ts';
import {id,name,Fault} from '../contracts.ts';
import type {Actor} from '../contracts.ts';
import {NarrativeGateway,GroundedProvider,JsonGatewayProvider} from './ai.ts';
export function gameRoutes(app:FastifyInstance,game:Game,actor:(r:object)=>Actor,key:(headers:Record<string,unknown>)=>string){
 const providers=[new GroundedProvider(),...(process.env.AI_GATEWAY_URL&&process.env.AI_GATEWAY_SECRET?[new JsonGatewayProvider(process.env.AI_GATEWAY_URL,process.env.AI_GATEWAY_SECRET)]:[])];
 const ai=new NarrativeGateway(game,providers);
 const timeline=(r:FastifyRequest)=>z.object({id}).parse(r.params).id;
 const bodyRevision=z.number().int().positive();
 const wrap=(fn:()=>unknown)=>{try{return fn();}catch(error){if(error instanceof Fault||error instanceof z.ZodError)throw error;if(error instanceof Error&&/^[a-z_]+$/.test(error.message))throw new Fault(400,error.message);throw error;}};
 app.get('/game/catalog',async r=>{actor(r);return {kinds,schemas:Object.fromEntries(kinds.map(k=>[k,z.toJSONSchema(dataSchemas[k])])),actions:actionSchema.options.map(option=>z.toJSONSchema(option)),providers:providers.map(p=>p.id)};});
 app.get('/game/campaigns/:id/timelines',async r=>game.list(actor(r),timeline(r)));
 app.post('/game/campaigns/:id/timelines',async r=>game.initialize(actor(r),timeline(r)));
 app.get('/game/timelines/:id/roster',async r=>game.roster(actor(r),timeline(r)));
 app.get('/game/timelines/:id/view',async r=>{const query=z.strictObject({characterId:id}).parse(r.query);return wrap(()=>game.view(actor(r),timeline(r),query.characterId));});
 app.get('/game/timelines/:id/creator',async r=>game.creator(actor(r),timeline(r)));
 app.post('/game/timelines/:id/entities',async r=>{const input=z.strictObject({revision:bodyRevision,entity:z.unknown()}).parse(r.body);return wrap(()=>game.edit(actor(r),timeline(r),input,key(r.headers)));});
 app.post('/game/timelines/:id/settings',async r=>{const b=z.strictObject({revision:bodyRevision,settings:z.unknown()}).parse(r.body);return wrap(()=>game.configure(actor(r),timeline(r),b.revision,b.settings,key(r.headers)));});
 app.post('/game/timelines/:id/epistemic',async r=>{
  const b=z.strictObject({revision:bodyRevision,layer:z.enum(['truth','knowledge','belief','memory','correct-belief','retire-truth','refresh-memory']),subjectId:id,text:z.string().max(16000),factId:id.optional(),confidence:z.number().min(0).max(1).optional(),recordId:id.optional(),salience:z.number().min(0).max(1).optional(),decayPerDay:z.number().min(0).max(1).optional()}).parse(r.body);
  return wrap(()=>game.epistemic(actor(r),timeline(r),b.revision,b,key(r.headers)));
 });
 app.post('/game/timelines/:id/parse',async r=>{const b=z.strictObject({characterId:id,text:z.string().min(1).max(1000)}).parse(r.body);return wrap(()=>game.parse(actor(r),timeline(r),b.characterId,b.text));});
 app.post('/game/timelines/:id/turns',async r=>{const b=z.strictObject({revision:bodyRevision,characterId:id,action:actionSchema,text:z.string().max(1000).optional()}).parse(r.body);return wrap(()=>game.turn(actor(r),timeline(r),b,key(r.headers)));});
 app.post('/game/timelines/:id/narrate',async r=>{const b=z.strictObject({turnId:id,provider:z.string().max(100).default('grounded')}).parse(r.body);return ai.narrate(actor(r),timeline(r),b.turnId,b.provider);});
 app.get('/game/timelines/:id/saves',async r=>game.saves(actor(r),timeline(r)));
 app.post('/game/timelines/:id/saves',async r=>game.save(actor(r),timeline(r),z.strictObject({name}).parse(r.body).name));
 app.post('/game/timelines/:id/branch',async r=>{const b=z.strictObject({saveId:id,name}).parse(r.body);return wrap(()=>game.branch(actor(r),timeline(r),b.saveId,b.name));});
 app.get('/game/timelines/:id/export',async r=>game.export(actor(r),timeline(r)));
 app.post('/game/timelines/:id/import',{bodyLimit:8*1024*1024},async r=>{const b=z.strictObject({name,bundle:z.unknown(),dryRun:z.boolean().default(true)}).parse(r.body);return wrap(()=>game.import(actor(r),timeline(r),b.name,b.bundle,b.dryRun));});
 app.post('/game/timelines/:id/template',async r=>game.template(actor(r),timeline(r),z.strictObject({name}).parse(r.body).name));
 app.get('/game/timelines/:id/templates',async r=>game.templates(actor(r),timeline(r)));
 app.post('/game/timelines/:id/templates/use',async r=>{const b=z.strictObject({templateId:id,name}).parse(r.body);return wrap(()=>game.instantiateTemplate(actor(r),timeline(r),b.templateId,b.name));});
 app.post('/game/timelines/:id/catalog',async r=>{const b=z.strictObject({revision:bodyRevision}).parse(r.body);return game.installCatalog(actor(r),timeline(r),b.revision,key(r.headers));});
 app.get('/game/timelines/:id/history',async r=>game.history(actor(r),timeline(r)));
 app.get('/game/timelines/:id/context',async r=>{const q=z.strictObject({characterId:id,query:z.string().max(1000)}).parse(r.query);return wrap(()=>game.context(actor(r),timeline(r),q.characterId,q.query));});
 app.get('/game/timelines/:id/ai-usage',async r=>{game.access(actor(r),timeline(r),true);return game.store.all('SELECT provider,reserved_tokens,used_tokens,status,created_at FROM ai_usage WHERE timeline_id=? ORDER BY rowid DESC LIMIT 100',timeline(r));});
}
