import {test} from 'node:test';
import assert from 'node:assert/strict';
import {chromium} from '@playwright/test';
import {AxeBuilder} from '@axe-core/playwright';
import {randomUUID} from 'node:crypto';
import {Game} from '../src/game/engine.ts';
import {validateEntity} from '../src/game/model.ts';
import {fixture,password} from './helpers.ts';
test('iPad shell, keyboard login, Creator form, long prose, reduced motion and offline shell',async()=>{
 const f=await fixture(),browser=await chromium.launch({headless:true});
 const context=await browser.newContext({viewport:{width:820,height:1180},isMobile:true,hasTouch:true,reducedMotion:'reduce'});
 const page=await context.newPage();const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 try{
  const address=await f.app.listen({host:'127.0.0.1',port:0});
  // Origin is deployment configuration, not a header supplied by browser code.
  f.settings.origin=address;
  await page.goto(address+'/app');
  await page.getByLabel('Email address').fill('creator@example.test');
  await page.getByLabel('Password',{exact:true}).fill(password);
  await page.getByRole('button',{name:'Enter Valor'}).click();
  await page.getByRole('heading',{name:'Choose your story.'}).waitFor();
  await page.getByRole('button',{name:'Open campaign'}).click();
  await page.getByRole('button',{name:'Open Creator'}).click();
  await page.getByRole('heading',{name:'Creator.'}).waitFor();
  await page.getByLabel('Record type',{exact:true}).selectOption('location');
  await page.getByRole('button',{name:'New record',exact:true}).click();
  await page.getByLabel('Name',{exact:true}).fill('Browser-authored room');
  await page.getByLabel('Visibility',{exact:true}).first().selectOption('campaign');
  await page.getByRole('button',{name:'Save record',exact:true}).click();
  await page.getByRole('button',{name:'Browser-authored room'}).waitFor();
  const accessibility=await new AxeBuilder({page}).analyze();
  assert.deepEqual(accessibility.violations.map(v=>({id:v.id,impact:v.impact,description:v.description})),[]);
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
  await page.screenshot({path:'artifacts/ipad-creator.png',fullPage:true});
  await page.setViewportSize({width:1180,height:820});
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
  await page.screenshot({path:'artifacts/ipad-landscape.png',fullPage:true});
  const game=new Game(f.store),timeline=f.store.get<{id:string}>('SELECT id FROM timelines LIMIT 1')!;
  const room=game.load(timeline.id).entities.find(e=>e.kind==='location')!;
  room.data.description=Array.from({length:45},()=> 'This is synthetic test prose, used only to verify long-form Chronicle layout.').join('\n\n');
  game.edit(f.creator,timeline.id,{revision:game.access(f.creator,timeline.id).t.revision,entity:room},randomUUID());
  const character=validateEntity({id:randomUUID(),kind:'character',name:'Browser test character',visibility:'campaign',data:{playable:true,controllerUserId:f.creator.id,locationId:room.id}});
  game.edit(f.creator,timeline.id,{revision:game.access(f.creator,timeline.id).t.revision,entity:character},randomUUID());
  await page.getByRole('button',{name:'Chronicle',exact:true}).click();
  await page.getByRole('button',{name:'Continue as Browser test character'}).click();
  await page.getByRole('button',{name:'Look around',exact:true}).click();
  await page.locator('.turn .prose').waitFor();
  assert.ok((await page.locator('.turn .prose').textContent())!.length>3000);
  assert.deepEqual((await new AxeBuilder({page}).analyze()).violations.map(v=>v.id),[]);
  await page.screenshot({path:'artifacts/chronicle.png'});
  await page.setViewportSize({width:390,height:844});
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
  await page.getByRole('button',{name:'Toggle navigation'}).click();
  await page.getByRole('button',{name:'Sign out',exact:true}).click();
  await page.getByRole('button',{name:'Enter Valor'}).waitFor();
  await page.keyboard.press('Tab');
  assert.ok(await page.evaluate(()=>document.activeElement!==document.body));
  await page.evaluate(()=>navigator.serviceWorker.ready);
  await context.setOffline(true);
  await page.reload();
  await page.getByRole('heading',{name:'Every choice leaves a trace.'}).waitFor();
  assert.ok(await page.getByText('Offline — reconnect to sign in.').isVisible());
  await context.setOffline(false);
  await page.reload();
  await page.getByRole('button',{name:'Enter Valor'}).waitFor();
  assert.deepEqual(errors,[]);
 }finally{await context.close();await browser.close();await f.close();}
});
