import {test} from 'node:test';
import assert from 'node:assert/strict';
import {chromium} from '@playwright/test';
import {AxeBuilder} from '@axe-core/playwright';
import {randomUUID} from 'node:crypto';
import {Game} from '../src/game/engine.ts';
import {validateEntity} from '../src/game/model.ts';
import {fixture,password} from './helpers.ts';
test('iPad shell, keyboard login, Creator form, long prose, reduced motion and offline shell',async()=>{
 const f=await fixture(),browser=await chromium.launch({headless:true});
 const context=await browser.newContext({viewport:{width:820,height:1180},isMobile:true,hasTouch:true,reducedMotion:'reduce'});
 const page=await context.newPage();const errors:string[]=[];let developerSnapshotRequests=0;page.on('pageerror',e=>errors.push(e.message));page.on('request',request=>{if(request.url().includes('/developer/overview'))developerSnapshotRequests++;});
 let narrationRequests=0;
 await page.route('**/game/catalog',async route=>{const response=await route.fetch(),catalog=await response.json();catalog.providers=['grounded','gemini'];catalog.defaultProvider='gemini';await route.fulfill({response,json:catalog});});
 await page.route('**/narrate',async route=>{assert.equal(route.request().postDataJSON().provider,'gemini');narrationRequests++;await route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:'test_provider_unavailable'})});});
 await page.route('**/story/resolve',async route=>{const body=route.request().postDataJSON();if(body.text==='Take the unknown object.')await route.fulfill({json:{action:null,clarification:'Which object did you mean?'}});else await route.continue();});
 await page.route('**/narrate/stream',async route=>{await new Promise(resolve=>setTimeout(resolve,300));try{await route.fulfill({status:200,contentType:'application/x-ndjson',body:JSON.stringify({type:'paragraph',text:'This must stay buffered.'})+'\n'+JSON.stringify({type:'complete',status:'validated'})+'\n'});}catch{/* The browser intentionally canceled this request. */}});
 try{
  const navAction=async(name:string)=>{const control=page.locator('.rail').getByRole('button',{name,exact:true});if(!await control.isVisible())await page.getByRole('button',{name:'Toggle navigation'}).click();await control.click();};
  const address=await f.app.listen({host:'127.0.0.1',port:0});
  // Origin is deployment configuration, not a header supplied by browser code.
  f.settings.origin=address;
  await page.goto(address+'/app');
  await page.getByLabel('Email address').fill('creator@example.test');
  await page.getByLabel('Password',{exact:true}).fill(password);
  await page.getByRole('button',{name:'Enter Valor'}).click();
  await page.getByRole('heading',{name:'VALOR',exact:true}).waitFor();
  assert.deepEqual(await page.getByRole('navigation',{name:'Main menu',exact:true}).getByRole('button').allTextContents(),['New Life','Load Life','About Valor']);
  assert.equal(await page.locator('.game-menu-hero button').count(),3);
  assert.equal(await page.getByRole('button',{name:'Phone',exact:true}).count(),0);
  const aestheticTheme=await page.evaluate(()=>document.documentElement.dataset.theme);
  await navAction('Enable emergency high-visibility display');
  assert.equal(await page.evaluate(()=>document.documentElement.dataset.accessibility),'emergency');
  assert.equal(await page.evaluate(()=>document.documentElement.dataset.theme),aestheticTheme,'accessibility override does not replace saved aesthetic');
  await navAction('Restore theme display');
  await page.getByRole('button',{name:'New Life',exact:true}).click();
  await page.getByRole('button',{name:'Choose a start',exact:true}).click();
  await page.getByRole('heading',{name:'Begin a life.',exact:true}).waitFor();
  assert.equal(developerSnapshotRequests,0,'Player Mode does not preload the Developer snapshot');
  await navAction('Creation Studio');
  await page.getByRole('heading',{name:'Enter Developer Mode?'}).waitFor();
  await page.getByRole('button',{name:'Confirm Developer Mode'}).click();
  await page.getByRole('heading',{name:'Creation Studio.'}).waitFor();
  await page.getByRole('button',{name:/^Places Build/}).click();
  await page.getByRole('heading',{name:'Places',exact:true}).waitFor();
  await page.getByText('Developer Mode is active',{exact:true}).waitFor();
  const portraitPlacement=await page.evaluate(()=>{const rect=document.querySelector('.mode-switch')!.getBoundingClientRect();return {top:rect.top,gap:innerHeight-rect.bottom};});assert.ok(portraitPlacement.top>=0&&portraitPlacement.gap>=8,'portrait switch respects bottom safe spacing: '+JSON.stringify(portraitPlacement));
  await page.getByLabel('Record type',{exact:true}).selectOption('location');
  await page.getByRole('button',{name:'New record',exact:true}).click();
  await page.getByLabel('Name',{exact:true}).fill('Browser-authored room');
  await page.getByLabel('Visibility',{exact:true}).first().selectOption('campaign');
  await page.getByRole('button',{name:'Review & publish',exact:true}).click();
  await page.getByRole('heading',{name:'Publish Browser-authored room?'}).waitFor();
  const confirmHit=await page.evaluate(()=>{const button=[...document.querySelectorAll('button')].find(node=>node.textContent==='Confirm audited publish')!,dialog=document.querySelector('dialog.developer-confirm')!,rect=button.getBoundingClientRect(),dialogRect=dialog.getBoundingClientRect(),hit=document.elementFromPoint(rect.left+rect.width/2,rect.top+rect.height/2);return {button:{left:rect.left,top:rect.top,right:rect.right,bottom:rect.bottom},dialog:{left:dialogRect.left,top:dialogRect.top,right:dialogRect.right,bottom:dialogRect.bottom},hit:hit?.tagName+'.'+hit?.className};});assert.match(confirmHit.hit,/^BUTTON\./,'confirmation touch target: '+JSON.stringify(confirmHit));
  await page.getByRole('button',{name:'Confirm audited publish',exact:true}).click({force:true});
  await page.getByRole('button',{name:'Browser-authored room'}).waitFor();
  await page.getByRole('button',{name:'All creation areas',exact:true}).click();
  await page.getByRole('button',{name:/^People Create/}).click();
  await page.getByLabel('Record type',{exact:true}).selectOption('character');
  await page.getByRole('button',{name:'New record',exact:true}).click();
  await page.getByText('NPC JOB-SHEET PROFILE',{exact:true}).waitFor();
  await page.getByLabel('Number of occupations',{exact:true}).selectOption('3');
  assert.equal(await page.locator('.npc-occupation-card').count(),3);
  assert.equal(await page.getByLabel('Place of work',{exact:true}).count(),3);
  const accessibility=await new AxeBuilder({page}).analyze();
  assert.deepEqual(accessibility.violations.map(v=>({id:v.id,impact:v.impact,description:v.description,nodes:v.nodes.map(n=>({target:n.target,summary:n.failureSummary}))})),[]);
  await page.screenshot({path:'artifacts/creation-layout.png',fullPage:true});
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,JSON.stringify(await page.evaluate(()=>[...document.querySelectorAll('main *')].filter(node=>node.getBoundingClientRect().right>innerWidth+1).slice(0,12).map(node=>({tag:node.tagName,cls:node.className,width:node.getBoundingClientRect().width,right:node.getBoundingClientRect().right})))));
  await page.screenshot({path:'artifacts/ipad-creator.png',fullPage:true});
  await page.setViewportSize({width:1180,height:820});
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
  const landscapePlacement=await page.evaluate(()=>{const rect=document.querySelector('.mode-switch')!.getBoundingClientRect();return {top:rect.top,gap:innerHeight-rect.bottom};});assert.ok(landscapePlacement.top>=0&&landscapePlacement.gap>=8,'landscape switch respects bottom safe spacing: '+JSON.stringify(landscapePlacement));
  await page.screenshot({path:'artifacts/ipad-landscape.png',fullPage:true});
  assert.ok(developerSnapshotRequests>0,'Developer snapshot loads only after confirmed entry');
  const switchHit=await page.evaluate(()=>{const button=document.querySelector('.mode-switch')!,rect=button.getBoundingClientRect(),hit=document.elementFromPoint(rect.left+rect.width/2,rect.top+rect.height/2);return {rect:{left:rect.left,top:rect.top,right:rect.right,bottom:rect.bottom},hit:hit?.tagName+'.'+hit?.className};});assert.match(switchHit.hit,/^(BUTTON\.mode-switch|SPAN\.mode-switch-icon)/,'mode switch touch target: '+JSON.stringify(switchHit));
  await page.getByRole('button',{name:'Exit Developer Mode'}).click({force:true});
  await page.getByRole('heading',{name:'Exit Developer Mode?'}).waitFor();
  await page.getByRole('button',{name:'Confirm Player Mode'}).click({force:true});
  await page.locator('.mode-badge').getByText('PLAYER MODE',{exact:true}).waitFor();
  await page.setViewportSize({width:820,height:1180});
  const requestsAfterExit=developerSnapshotRequests;
  assert.equal(await page.getByRole('button',{name:'Phone',exact:true}).count(),0,'no gameplay sidebar before choosing a character');
  await page.getByRole('button',{name:'Toggle navigation'}).click();
  const settingsHit=await page.evaluate(()=>{const button=[...document.querySelectorAll('.rail nav button')].find(node=>node.textContent==='Settings')!,rect=button.getBoundingClientRect(),hit=document.elementFromPoint(rect.left+rect.width/2,rect.top+rect.height/2);return {rect:{left:rect.left,top:rect.top,right:rect.right,bottom:rect.bottom},hit:hit?.textContent};});assert.equal(settingsHit.hit,'Settings','Settings navigation touch target: '+JSON.stringify(settingsHit));
  await page.getByRole('button',{name:'Settings',exact:true}).click({force:true});
  await page.getByRole('heading',{name:'Settings.'}).waitFor();
  await navAction('Style');await page.locator('.style-dialog').getByRole('button',{name:'Stars',exact:true}).click();await page.locator('.style-dialog').getByLabel('Animate hearts & stars',{exact:true}).uncheck();await page.getByRole('button',{name:'Done',exact:true}).click();
  await page.locator('.style-dialog').waitFor({state:'detached'});assert.equal(await page.locator('main').getByRole('button',{name:'Stars',exact:true}).getAttribute('aria-pressed'),'true','Settings reflects choices made in the Style dialog');assert.equal(await page.locator('main').getByLabel('Animate hearts & stars',{exact:true}).isChecked(),false);
  assert.equal(developerSnapshotRequests,requestsAfterExit,'Player Settings does not reload hidden Developer state');
  assert.equal(await page.getByRole('button',{name:'Open Developer Studio'}).count(),0);
  const game=new Game(f.store),timeline=(await f.store.get<{id:string}>('SELECT id FROM timelines LIMIT 1'))!;
  const room=(await game.load(timeline.id)).entities.find(e=>e.kind==='location')!;
  room.data.description=Array.from({length:45},()=> 'This is synthetic test prose, used only to verify long-form Chronicle layout.').join('\n\n');
  (await game.edit(f.creator,timeline.id,{revision:(await game.access(f.creator,timeline.id)).t.revision,entity:room},randomUUID()));
  const character=validateEntity({id:randomUUID(),kind:'character',name:'Browser test character',visibility:'campaign',data:{playable:true,controllerUserId:f.creator.id,locationId:room.id}});
  (await game.edit(f.creator,timeline.id,{revision:(await game.access(f.creator,timeline.id)).t.revision,entity:character},randomUUID()));
  await page.getByRole('button',{name:'Toggle navigation'}).click();
  await page.getByRole('button',{name:'Load Life',exact:true}).click();
  await page.getByRole('button',{name:'Continue as Browser test character'}).waitFor();
  const rosterHit=await page.evaluate(()=>{const button=document.querySelector('.roster-copy button.primary')!,portrait=document.querySelector('.roster-portrait')!,copy=document.querySelector('.roster-copy')!,card=document.querySelector('.roster-card')!,rect=button.getBoundingClientRect(),toBox=(node:Element)=>{const box=node.getBoundingClientRect();return {left:box.left,top:box.top,right:box.right,bottom:box.bottom,width:box.width,height:box.height,z:getComputedStyle(node).zIndex};},hit=document.elementFromPoint(rect.left+rect.width/2,rect.top+rect.height/2);return {button:toBox(button),portrait:toBox(portrait),copy:toBox(copy),card:toBox(card),hit:hit?.tagName+'.'+hit?.className};});assert.match(rosterHit.hit,/^BUTTON\./,'roster Continue touch target: '+JSON.stringify(rosterHit));
  await page.getByRole('button',{name:'Continue as Browser test character'}).click({force:true});
  await page.getByLabel('Continue the story',{exact:true}).fill('Look around');
  await page.getByLabel('Continue the story',{exact:true}).press('Enter');
  await page.waitForFunction(()=>document.querySelector('.turn .prose')?.textContent?.includes('synthetic test prose'));
  await page.waitForFunction(()=>!document.querySelector('[aria-busy="true"]'));
  assert.ok((await page.locator('.turn .prose').textContent())!.length>3000);
  await page.locator('.story-tools summary').first().click();
  const originalProse=await page.locator('.turn .prose').first().textContent();await page.getByRole('button',{name:'Rebuild narration without rerolling',exact:true}).first().click();await page.getByRole('button',{name:'Cancel rebuild',exact:true}).click();await page.getByText('Narration rebuild canceled. The previous prose remains displayed.',{exact:true}).waitFor();assert.equal(await page.locator('.turn .prose').first().textContent(),originalProse);
  await page.locator('.composer').scrollIntoViewIfNeeded();
  assert.equal(await page.evaluate(()=>{const composer=document.querySelector('.composer'),switcher=document.querySelector('.mode-switch');if(!composer||!switcher)return false;const a=composer.getBoundingClientRect(),b=switcher.getBoundingClientRect();return !(a.right>b.left&&a.left<b.right&&a.bottom>b.top&&a.top<b.bottom);}),true,'bottom-edge switch does not cover the composer');
  const beforeProposal=(await game.access(f.creator,timeline.id)).t.revision;
  const draft='I pause at the window.\nI listen for footsteps.';await page.getByLabel('Continue the story',{exact:true}).fill(draft);
  await page.getByRole('button',{name:'Open phone',exact:true}).click();
  await page.locator('[data-pocket-app="Inventory"]').click();await page.getByRole('heading',{name:'Inventory.'}).waitFor();
  await page.getByRole('button',{name:'Put away ↘'}).click();
  assert.equal(await page.getByLabel('Continue the story',{exact:true}).inputValue(),draft);
  assert.equal(await page.getByRole('button',{name:'Ask Gemini to interpret',exact:true}).count(),0);
  assert.equal(await page.getByRole('button',{name:'Confirm this action',exact:true}).count(),0);
  await page.getByLabel('Continue the story',{exact:true}).fill('wait 1');await page.getByLabel('Continue the story',{exact:true}).press('Enter');
  await page.locator('.turn').nth(1).waitFor();
  await page.waitForFunction(()=>!document.querySelector('[aria-busy="true"]'));
  assert.equal((await game.access(f.creator,timeline.id)).t.revision,beforeProposal+1);
  assert.equal(narrationRequests,2,'each committed turn tries the selected provider once; failures do not reroll');
  const beforeAI=(await game.access(f.creator,timeline.id)).t.revision;
  await page.getByLabel('Continue the story',{exact:true}).fill('Take the unknown object.');await page.getByLabel('Continue the story',{exact:true}).press('Enter');
  await page.getByText('Which object did you mean?',{exact:true}).waitFor();
  assert.equal((await game.access(f.creator,timeline.id)).t.revision,beforeAI,'ambiguous targets do not mutate the world');
  assert.equal(await page.locator('.story-combat').count(),0,'combat stays hidden outside an encounter');
  assert.deepEqual((await new AxeBuilder({page}).analyze()).violations.map(v=>v.id),[]);
  await page.screenshot({path:'artifacts/chronicle.png'});
  for(const [width,height] of [[390,844],[820,1180],[1440,1000]]){
   await page.setViewportSize({width:width!,height:height!});
   assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,'Chronicle fits '+width);
   await page.getByRole('button',{name:'Open phone',exact:true}).click();
   await page.getByRole('dialog',{name:'Your phone'}).waitFor();
   assert.equal(await page.locator('.pocket-app').count(),15);
   assert.deepEqual((await new AxeBuilder({page}).analyze()).violations.map(v=>v.id),[]);
   await page.screenshot({path:'artifacts/phone-'+width+'.png'});
   await page.locator('[data-pocket-app="Character"]').click();
   await page.getByRole('heading',{name:'Character.',exact:true}).waitFor();
   const phoneFit=await page.locator('.pocket-content').evaluate(node=>node.scrollWidth<=node.clientWidth+1);
   assert.equal(phoneFit,true,'Character app fits phone at '+width);
   await page.getByRole('button',{name:'Put away ↘'}).click();
  }
  const opponent=validateEntity({id:randomUUID(),kind:'character',name:'Encounter participant',visibility:'campaign',data:{locationId:room.id}}),encounter=validateEntity({id:randomUUID(),kind:'combat',name:'Test encounter',visibility:'campaign',data:{locationId:room.id,participants:[character.id,opponent.id]}});
  await game.bulkEdit(f.creator,timeline.id,{revision:(await game.access(f.creator,timeline.id)).t.revision,entities:[opponent,encounter]},randomUUID());
  await page.getByRole('button',{name:'Open phone',exact:true}).click();await page.getByRole('button',{name:'Put away ↘'}).click();await page.getByRole('heading',{name:'In combat',exact:true}).waitFor();
  encounter.data.active=false;encounter.data.phase='ended';await game.edit(f.creator,timeline.id,{revision:(await game.access(f.creator,timeline.id)).t.revision,entity:encounter},randomUUID());
  await page.getByRole('button',{name:'Open phone',exact:true}).click();await page.getByRole('button',{name:'Put away ↘'}).click();await page.locator('.story-combat').waitFor({state:'detached'});
  const reconnectDraft='This draft survives a reconnect.\nIt is still not an action.';await page.getByLabel('Continue the story',{exact:true}).fill(reconnectDraft);await page.reload();await page.getByRole('heading',{name:'VALOR',exact:true}).waitFor();assert.equal(await page.evaluate(()=>Object.entries(sessionStorage).find(([key])=>key.startsWith('valor.draft.'))?.[1]),reconnectDraft);
  await page.setViewportSize({width:390,height:844});
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
  await page.getByRole('button',{name:'Toggle navigation'}).click();
  await page.getByRole('button',{name:'Sign out',exact:true}).click();
  await page.getByRole('button',{name:'Enter Valor'}).waitFor();
  await page.keyboard.press('Tab');
  assert.ok(await page.evaluate(()=>document.activeElement!==document.body));
  await page.evaluate(()=>navigator.serviceWorker.ready);
  await context.setOffline(true);
  await page.reload();
  await page.getByRole('heading',{name:'Every choice leaves a trace.'}).waitFor();
  assert.ok(await page.getByText('Offline — reconnect to sign in.').isVisible());
  await context.setOffline(false);
  await page.reload();
  await page.getByRole('button',{name:'Enter Valor'}).waitFor();
  assert.deepEqual(errors,[]);
 }finally{await context.close();await browser.close();await f.close();}
});
