import {test} from 'node:test';
import assert from 'node:assert/strict';
import {chromium} from '@playwright/test';
import {AxeBuilder} from '@axe-core/playwright';
import {randomUUID} from 'node:crypto';
import {Game} from '../src/game/engine.ts';
import {validateEntity} from '../src/game/model.ts';
import {fixture,password,key} from './helpers.ts';
import {themeIds} from '../src/theme.ts';

test('Creation Studio preserves exact ratings, hidden notes and jobs across themes and reviewed saves',async()=>{
 const f=await fixture(),browser=await chromium.launch({headless:true});
 const context=await browser.newContext({viewport:{width:1536,height:1100},reducedMotion:'reduce'}),page=await context.newPage(),errors:string[]=[];page.on('pageerror',error=>errors.push(error.message));
 try{
  const navAction=async(name:string)=>{const selector='.rail button';if(!await page.locator('.rail').getByRole('button',{name,exact:true}).isVisible())await page.getByRole('button',{name:'Toggle navigation'}).click();await page.waitForFunction(({selector,name})=>[...document.querySelectorAll(selector)].some(node=>node.textContent?.trim()===name),{selector,name});await page.evaluate(({selector,name})=>{const node=[...document.querySelectorAll(selector)].find(node=>node.textContent?.trim()===name) as HTMLButtonElement|undefined;if(!node)throw new Error('navigation unavailable');node.click();},{selector,name});};
  const game=new Game(f.store),timeline=await game.initialize(f.creator,f.campaign.id),id=randomUUID(),skillId=randomUUID();
  await game.configure(f.creator,timeline.id,1,{attributeScale:{min:-10,max:200,step:.25}},key());
  await game.edit(f.creator,timeline.id,{revision:2,entity:validateEntity({id:skillId,kind:'skill',name:'Driving',visibility:'campaign',data:{category:'skill',scale:{min:0,max:30,step:.25,unit:'rating'}}})},key());
  await game.edit(f.creator,timeline.id,{revision:3,entity:validateEntity({id,kind:'character',name:'UI preservation subject',visibility:'creator',data:{legalName:'Alex Morgan',ageYears:26,pronouns:'They / them',nationality:'Canadian',originNeighborhood:'Downtown',background:{option1:'Former art student',option2:'Preserved optional history'},attributes:{Strength:125.5,Agility:-2,Endurance:30,Intellect:45,Perception:50,Presence:20,Will:60},skills:{[skillId]:22.5},secrets:'Keep this private',instructions:'Never replace this instruction',occupations:[{id:randomUUID(),placeOfWork:'Cafe',position:'Barista',days:['Monday'],shift:'day'}]}})},key());
  await game.edit(f.creator,timeline.id,{revision:4,entity:validateEntity({id:randomUUID(),kind:'location',name:'Routine test cafe',visibility:'campaign',data:{}})},key());
  const address=await f.app.listen({host:'127.0.0.1',port:0});f.settings.origin=address;
  await page.goto(address+'/app');await page.getByLabel('Email address').fill('creator@example.test');await page.getByLabel('Password',{exact:true}).fill(password);await page.getByRole('button',{name:'Enter Valor'}).click();await page.getByRole('heading',{name:'VALOR',exact:true}).waitFor();
  await navAction('Style');await page.getByRole('button',{name:/Neon Purple Night/}).click();await page.getByRole('button',{name:'Done',exact:true}).click();
  await page.screenshot({path:'artifacts/valor-menu-pastel.png',fullPage:true});
  await page.getByRole('button',{name:'About Valor',exact:true}).click();await page.getByRole('heading',{name:'ABOUT VALOR',exact:true}).waitFor();await page.getByRole('button',{name:'Back to main menu'}).click();
  await page.getByRole('button',{name:'New Life',exact:true}).click();await page.getByRole('button',{name:'Choose a start',exact:true}).click();await navAction('Creation Studio');await page.getByRole('button',{name:'Confirm Developer Mode'}).click();await page.getByRole('button',{name:/^People Create/}).click();
  await page.getByRole('button',{name:'UI preservation subject character',exact:true}).click();
  assert.equal(await page.getByLabel('Primary background',{exact:true}).evaluate(node=>node.tagName),'SELECT');assert.equal(await page.getByLabel('Background 2 (optional)',{exact:true}).inputValue(),'Preserved optional history');
  assert.equal(await page.getByLabel('Strength exact value',{exact:true}).inputValue(),'125.5');assert.equal(await page.getByLabel('Agility exact value',{exact:true}).inputValue(),'-2');
  assert.equal(await page.getByLabel('Driving exact value',{exact:true}).inputValue(),'22.5');
  assert.deepEqual(await page.locator('.oc-attributes .attribute-column').evaluateAll(columns=>columns.map(column=>column.querySelectorAll('.rating-control').length)),[6,6]);
  assert.equal(await page.locator('.oc-descriptive').count(),0);
  assert.equal(await page.getByText('FULL NPC / HIDDEN REGISTRY',{exact:true}).count(),0);
  assert.equal(await page.locator('.registry-column > aside').getByRole('button',{name:'All creation areas',exact:true}).count(),0);
  assert.deepEqual(await page.locator('.oc-sheet > .sheet-section > .sheet-heading h3').allTextContents(),['Overview','Stats','Skills','Traits','Personality','Appearance']);
  await page.getByLabel('Overview notes',{exact:true}).fill('A carefully authored overview.');
  await page.getByLabel('Height (feet & inches)',{exact:true}).selectOption('162.56');await page.getByLabel('Body build',{exact:true}).selectOption('Muscular');
  await page.getByLabel('Neighborhood',{exact:true}).selectOption('North Crowns');assert.equal(await page.getByLabel('Residence',{exact:true}).inputValue(),'The Sync');
  assert.equal(await page.getByLabel('Residence floor',{exact:true}).locator('option').count(),7);await page.getByLabel('Residence floor',{exact:true}).selectOption('3');
  assert.equal(await page.getByLabel('Apartment number',{exact:true}).locator('option[value="301"]').count(),0);await page.getByLabel('Apartment number',{exact:true}).selectOption('302');
  await page.getByLabel('Aliases (comma separated)',{exact:true}).fill('Alex, AM');
  await page.getByLabel('Personality notes',{exact:true}).fill('Quiet and observant');
  await page.getByLabel('Psychology notes',{exact:true}).fill('Authored context, not a diagnosis');
  await page.getByLabel('Background history',{exact:true}).fill('A longer personal history');
  await page.getByLabel('Loyalty',{exact:true}).fill('7');
  const advanced=page.locator('details').filter({has:page.locator('summary').filter({hasText:/^More details · simulation/})}).first();assert.equal(await advanced.getAttribute('open'),null);
  await advanced.locator(':scope > summary').click();
  assert.equal(await advanced.getByText('Not sure where to start?',{exact:true}).isVisible(),true);
  const money=advanced.locator('[data-creation-group="Starting place & money"]');await money.locator(':scope > summary').click();
  assert.match(await money.locator('[data-field=cash] .field-help').innerText(),/2500 means \$25.00/);
  await money.getByLabel('Cash on hand (cents)',{exact:true}).fill('2500');
  const health=advanced.locator('[data-creation-group="Health & daily needs"]');await health.locator(':scope > summary').click();
  assert.equal(await health.getByLabel('Blood level',{exact:true}).inputValue(),'100');await health.getByLabel('Tiredness',{exact:true}).fill('6');
  const writing=advanced.locator('[data-creation-group="Personality, goals & AI writing"]');await writing.locator(':scope > summary').click();
  assert.equal(await writing.getByLabel('Narration guidance',{exact:true}).inputValue(),'Never replace this instruction');
  await writing.getByLabel('Speaking style',{exact:true}).fill('Short sentences and dry humor.');
  const routines=advanced.locator('[data-creation-group="Daily routine & automatic actions"]');await routines.locator(':scope > summary').click();await routines.getByText('Daily routine',{exact:true}).click();
  const schedule=routines.locator('details').filter({has:page.locator('summary').filter({hasText:/^Daily routine$/})});
  await schedule.getByRole('button',{name:'Add entry',exact:true}).click();await schedule.getByLabel('Time of day',{exact:true}).fill('09:30');await schedule.getByLabel('Current location',{exact:true}).selectOption({index:1});await schedule.getByLabel('Current activity',{exact:true}).fill('Morning work shift');await schedule.getByLabel('Sunday',{exact:true}).uncheck();
  assert.equal(await advanced.locator('[data-creation-group=system]').getAttribute('open'),null);
  await page.locator('.guided-character-details').screenshot({path:'artifacts/valor-guided-details.png'});
  await money.screenshot({path:'artifacts/valor-starting-details.png'});await writing.screenshot({path:'artifacts/valor-ai-writing-details.png'});
  assert.deepEqual((await new AxeBuilder({page}).include('.guided-character-details').analyze()).violations.map(v=>({id:v.id,nodes:v.nodes.map(n=>n.target)})),[]);
  await advanced.locator(':scope > summary').click();
  const help=page.getByRole('button',{name:'Help: Overview',exact:true});await help.hover();assert.equal(await page.getByRole('tooltip').filter({hasText:'Authored identity'}).isVisible(),true);await help.focus();await page.keyboard.press('Escape');assert.equal(await page.getByRole('tooltip').filter({hasText:'Authored identity'}).isVisible(),false);
  await page.getByLabel('Strength visual scale',{exact:true}).focus();await page.keyboard.press('Home');await page.keyboard.press('ArrowRight');assert.equal(await page.getByLabel('Strength exact value',{exact:true}).inputValue(),'-9.75');await page.getByLabel('Strength exact value',{exact:true}).fill('125.5');
  await page.getByLabel('Driving exact value',{exact:true}).fill('23.75');await page.getByLabel('Place of work',{exact:true}).selectOption('The Café');
  await page.locator('.creation-studio').screenshot({path:'artifacts/valor-creation-pastel.png'});
  await navAction('Style');await page.getByRole('button',{name:/Soft Baby Pink/}).click();await page.getByRole('button',{name:'Done',exact:true}).click();assert.equal(await page.getByLabel('Driving exact value',{exact:true}).inputValue(),'23.75','theme selection does not discard the draft');
  await page.locator('.creation-studio').screenshot({path:'artifacts/valor-creation-soft.png'});
  assert.deepEqual((await new AxeBuilder({page}).analyze()).violations.map(v=>({id:v.id,nodes:v.nodes.map(n=>n.target)})),[]);
  for(const themeId of themeIds){await page.evaluate(async id=>{const path='/theme.js';const theme=await import(path);theme.applyTheme(id);},themeId);assert.deepEqual((await new AxeBuilder({page}).include('.creation-studio').analyze()).violations.map(v=>({id:v.id,nodes:v.nodes.map(n=>n.target)})),[],themeId);}
  await page.evaluate(async()=>{const path='/theme.js';(await import(path)).applyTheme('soft-baby-pink');});
  await page.setViewportSize({width:390,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,'mobile page fits');
  const registry=page.locator('.registry-column');const searchBox=await registry.locator('aside').boundingBox(),returnBox=await registry.getByRole('button',{name:'All creation areas',exact:true}).boundingBox();assert.ok(searchBox&&returnBox&&returnBox.y>=searchBox.y+searchBox.height);
  const columns=await page.locator('.attribute-column').evaluateAll(nodes=>nodes.map(node=>{const r=node.getBoundingClientRect();return {x:r.x,y:r.y,height:r.height};}));assert.equal(columns.length,2);assert.ok(columns[1]!.x>columns[0]!.x);assert.ok(Math.abs(columns[0]!.y-columns[1]!.y)<1);assert.ok(Math.abs(columns[0]!.height-columns[1]!.height)<1);
  await page.locator('.oc-attributes').screenshot({path:'artifacts/valor-twelve-attributes-phone.png'});
  assert.equal(await page.locator('.oc-sheet .sheet-heading').first().evaluate(node=>getComputedStyle(node,'::after').content),'none');
  await help.click();assert.equal(await help.getAttribute('aria-expanded'),'true');assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,'help stays inside phone viewport');await page.keyboard.press('Escape');
  await page.locator('.creation-studio').screenshot({path:'artifacts/valor-creation-mobile.png'});
  for(const width of [820,1180,1536]){await page.setViewportSize({width,height:1100});for(const jobs of ['1','2','3']){await page.getByLabel('Number of occupations',{exact:true}).selectOption(jobs);assert.equal(await page.locator('.npc-occupation-card').count(),Number(jobs));assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,'sheet fits '+width+'px with '+jobs+' jobs');}if(width===1536){const psychology=page.locator('.oc-psychology'),notes=await psychology.getByLabel('Psychology notes',{exact:true}).boundingBox(),ratings=await psychology.locator('.oc-personality-ratings').boundingBox();assert.ok(notes&&ratings&&notes.width>=ratings.width*.8,'psychology notes have room beside compact labels');await psychology.screenshot({path:'artifacts/valor-psychology-wide.png'});}await page.locator('.creation-studio').screenshot({path:'artifacts/valor-sheet-'+width+'.png'});}
  await page.getByLabel('Number of occupations',{exact:true}).selectOption('1');
  await page.getByRole('button',{name:'Review & publish',exact:true}).click();await page.getByRole('button',{name:'Confirm audited publish',exact:true}).click();await page.getByRole('heading',{name:'Developer studio',exact:true}).waitFor();
  const saved=(await game.load(timeline.id)).entities.find(row=>row.id===id)!;
  assert.equal(saved.data.heightCm,162.56);assert.equal(saved.data.build,'Muscular');assert.equal((saved.data.residence as {apartment:string}).apartment,'302');assert.ok(saved.data.homeId);
  assert.equal(saved.data.cash,2500);assert.equal(saved.data.fatigue,6);assert.equal(saved.data.voice,'Short sentences and dry humor.');
  const savedRoutine=(saved.data.schedule as Array<{minute:number;days:number[];activity:string}>)[0]!;assert.equal(savedRoutine.minute,570);assert.deepEqual(savedRoutine.days,[1,2,3,4,5,6]);assert.equal(savedRoutine.activity,'Morning work shift');
  assert.equal((saved.data.attributes as Record<string,number>).Strength,125.5);assert.equal((saved.data.attributes as Record<string,number>).Agility,-2);assert.equal((saved.data.skills as Record<string,number>)[skillId],23.75);assert.equal(saved.data.secrets,'Keep this private');assert.equal(saved.data.instructions,'Never replace this instruction');assert.equal((saved.data.background as Record<string,string>).option2,'Preserved optional history');assert.equal((saved.data.occupations as Array<{placeOfWork:string}>)[0]!.placeOfWork,'The Café');
  assert.equal(saved.data.description,'A carefully authored overview.');assert.deepEqual(saved.data.aliases,['Alex','AM']);assert.equal((saved.data.personalityProfile as Record<string,unknown>).summary,'Quiet and observant');assert.equal(saved.data.psychologyNotes,'Authored context, not a diagnosis');assert.equal((saved.data.background as Record<string,string>).history,'A longer personal history');assert.equal((saved.data.dossierRatings as Record<string,number>).loyalty,7);
  await page.reload();await page.getByRole('heading',{name:'VALOR',exact:true}).waitFor();assert.equal(await page.evaluate(()=>document.documentElement.dataset.theme),'soft-baby-pink');
  await page.getByRole('button',{name:'New Life',exact:true}).click();await page.getByRole('button',{name:'Choose a start',exact:true}).click();await page.getByLabel('Playable character name').fill('New Life sheet subject');await page.getByLabel('Overview notes',{exact:true}).fill('Playable overview');await page.getByRole('textbox',{name:'Full legal name',exact:true}).fill('Jamie Morgan');await page.getByLabel('Number of occupations',{exact:true}).selectOption('2');await page.getByLabel('Place of work',{exact:true}).nth(1).selectOption('Liberty Bank');await page.getByLabel('Strength exact value',{exact:true}).fill('70.25');
  await page.getByRole('button',{name:'Start freeform life',exact:true}).click();await page.getByRole('button',{name:'Confirm canonical start',exact:true}).click();await page.getByRole('heading',{name:'Chronicle.',exact:true}).waitFor();
  assert.equal(await page.getByRole('button',{name:'Phone',exact:true}).count(),1);
  const playable=(await game.load(timeline.id)).entities.find(row=>row.name==='New Life sheet subject')!;assert.equal(playable.data.legalName,'Jamie Morgan');assert.equal(playable.data.description,'Playable overview');assert.equal((playable.data.attributes as Record<string,number>).Strength,70.25);assert.equal((playable.data.occupations as Array<{placeOfWork:string}>)[1]!.placeOfWork,'Liberty Bank');
  await navAction('Main menu');await page.getByRole('heading',{name:'VALOR',exact:true}).waitFor();assert.equal(await page.getByRole('button',{name:'Phone',exact:true}).count(),0);await page.getByRole('button',{name:'Load Life',exact:true}).click();await page.getByRole('button',{name:'Continue as New Life sheet subject',exact:true}).click();await page.getByRole('heading',{name:'Chronicle.',exact:true}).waitFor();
  await navAction('Main menu');await page.getByRole('heading',{name:'VALOR',exact:true}).waitFor();await page.getByRole('button',{name:'Load Life',exact:true}).click();await page.getByRole('button',{name:'Open lives',exact:true}).click();await page.getByRole('button',{name:'Open roster',exact:true}).click();await page.getByRole('button',{name:'Continue as New Life sheet subject',exact:true}).click();await page.getByRole('heading',{name:'Chronicle.',exact:true}).waitFor();
  assert.deepEqual(errors,[]);
 }finally{await browser.close();await f.close();}
});
