import {test} from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {actionSchema,data,settingsSchema,validateEntity,validateState} from '../src/game/model.ts';
import type {Entity,State} from '../src/game/model.ts';
import {advance} from '../src/game/simulation.ts';
import {resolveAction} from '../src/game/actions.ts';
import {observerView} from '../src/game/epistemics.ts';
import {correctRumor,createRumor,spreadRumor} from '../src/game/factions.ts';

const eventId='29292929-2929-4292-8292-292929292929',seed='29'.repeat(32);
const make=(kind:Entity['kind'],name:string,raw:Record<string,unknown>={},visibility:Entity['visibility']='campaign')=>validateEntity({id:randomUUID(),kind,name,visibility,data:raw});
const state=(entities:Entity[]):State=>({clock:'2012-06-01T12:00:00.000Z',settings:settingsSchema.parse({timezone:'America/New_York',deterministicCatchup:true,npcBudget:2000}),entities,facts:[],knowledge:[],beliefs:[],memories:[],eventIds:[]});
const act=(s:State,actorId:string,raw:unknown)=>resolveAction(s,actorId,actionSchema.parse(raw),eventId,seed);

test('player absence does not stop faction events, but membership alone cannot deliver an order',()=>{
 const hall=make('location','Union hall'),remote=make('location','Remote apartment'),player=make('character','Player',{playable:true,locationId:remote.id},'owner'),leader=make('character','Organizer',{locationId:hall.id}),member=make('character','Steward',{locationId:remote.id}),hookId=randomUUID(),faction=make('faction','Neighborhood union',{leaderId:leader.id,memberIds:[leader.id,member.id],territoryIds:[hall.id],resources:{influence:60},simulationPolicy:{enabled:true,intervalMinutes:60,maxEventsPerAdvance:10},eventHooks:[{id:hookId,outcome:'party-event',priority:10,cooldownMinutes:180,delivery:'meeting',requiresOrder:true,locationId:hall.id,summary:'Hold the annual neighborhood supper.',publicStory:'The union hall hosts its annual supper.'}]});
 const s=state([hall,remote,player,leader,member,faction]);advance(s,60,eventId,[],player.id);assert.equal(s.entities.filter(entity=>entity.kind==='factionEvent').length,0);assert.equal(s.entities.filter(entity=>entity.kind==='factionOrder').length,1);assert.equal(data(s.entities.find(entity=>entity.kind==='factionOrder')!,'factionOrder').status,'pending');
 member.data.locationId=hall.id;advance(s,60,eventId,[],player.id);const events=s.entities.filter(entity=>entity.kind==='factionEvent');assert.equal(events.length,1);assert.equal(data(events[0]!,'factionEvent').outcome,'party-event');assert.match(data(events[0]!,'factionEvent').cause.summary,/pressure 0.*resources influence 60/);assert.equal(data(faction,'faction').history.length,1);validateState(s);
});

test('authored pressure and relations escalate a feud once, then respect cooldown',()=>{
 const room=make('location','Back office'),remote=make('location','Remote'),player=make('character','Player',{playable:true,locationId:remote.id},'owner'),leader=make('character','Crew leader',{locationId:room.id}),member=make('character','Crew member',{locationId:room.id}),other=make('faction','Other crew',{}),hookId=randomUUID(),faction=make('faction','Dock crew',{leaderId:leader.id,memberIds:[leader.id,member.id],territoryIds:[room.id],pressure:70,relations:[{factionId:other.id,status:'hostile',tension:65,knownByIds:[leader.id,member.id]}],simulationPolicy:{enabled:true,intervalMinutes:60,maxEventsPerAdvance:10},eventHooks:[{id:hookId,outcome:'feud-escalation',priority:10,cooldownMinutes:180,delivery:'meeting',requiresOrder:true,locationId:room.id,targetFactionId:other.id,minimumPressure:60,relationTensionDelta:10,summary:'Answer repeated incursions at the docks.'}]});
 const s=state([room,remote,player,leader,member,other,faction]);advance(s,60,eventId,[],player.id);let relation=data(faction,'faction').relations[0]!;assert.equal(relation.status,'feud');assert.equal(relation.tension,75);assert.equal(s.entities.filter(entity=>entity.kind==='factionEvent').length,1);advance(s,60,eventId,[],player.id);relation=data(faction,'faction').relations[0]!;assert.equal(relation.tension,75);assert.equal(s.entities.filter(entity=>entity.kind==='factionEvent').length,1);validateState(s);
});

test('hidden affiliations and private faction facts remain audience-scoped',()=>{
 const room=make('location','Office'),member=make('character','Quiet member',{playable:true,locationId:room.id},'owner'),observer=make('character','Observer',{locationId:room.id}),secretId=randomUUID(),faction=make('faction','Civic circle',{publicIdentity:{summary:'A neighborhood service club.',values:['mutual aid'],contact:'public desk'},memberships:[{characterId:member.id,status:'active',public:false,knownByIds:[member.id],note:'Confidential affiliation'}],privateFacts:[{id:secretId,text:'The circle shelters a whistleblower.',knownByIds:[member.id]}]});
 const s=state([room,member,observer,faction]),memberFaction=observerView(s,member.id).entities.find(entity=>entity.id===faction.id)!,observerFaction=observerView(s,observer.id).entities.find(entity=>entity.id===faction.id)!;assert.equal((memberFaction.data.memberships as unknown[]).length,1);assert.equal((memberFaction.data.privateFacts as unknown[]).length,1);assert.equal((observerFaction.data.memberships as unknown[]).length,0);assert.equal((observerFaction.data.privateFacts as unknown[]).length,0);assert.match(String(observerFaction.data.publicIdentity&&JSON.stringify(observerFaction.data.publicIdentity)),/service club/);validateState(s);
});

test('rumor correction preserves provenance, updates recipient belief, and hides creator truth',()=>{
 const room=make('location','Cafe'),source=make('character','Source',{playable:true,locationId:room.id},'owner'),recipient=make('character','Recipient',{locationId:room.id}),outsider=make('character','Outsider',{locationId:room.id}),s=state([room,source,recipient,outsider]),rumor=createRumor(s,{sourceCharacterId:source.id,subjectId:recipient.id,proposition:'The clinic is closing.',confidence:80,truthRelation:'inaccurate',knownByIds:[source.id],eventId});
 spreadRumor(s,{rumorId:rumor.id,fromId:source.id,toId:recipient.id,channel:'in-person',eventId});const correction=correctRumor(s,{rumorId:rumor.id,fromId:source.id,toId:recipient.id,channel:'in-person',proposition:'The clinic is only changing its Friday hours.',truthRelation:'accurate',eventId});assert.equal(data(rumor,'rumor').status,'corrected');assert.equal(data(rumor,'rumor').correctedByRumorId,correction.id);assert.equal(s.beliefs.find(row=>row.observerId===recipient.id&&row.source==='rumor:'+rumor.id)?.truthStatus,'doubted');assert.equal(s.beliefs.find(row=>row.observerId===recipient.id&&row.source==='rumor:'+correction.id)?.truthStatus,'believed');
 const view=observerView(s,recipient.id),visibleRumor=view.entities.find(entity=>entity.id===rumor.id)!;assert.equal('truthRelation' in visibleRumor.data,false);assert.equal(view.entities.some(entity=>entity.id===correction.id),true);assert.equal(observerView(s,outsider.id).entities.some(entity=>entity.kind==='rumor'),false);validateState(s);
});

test('recruitment creates an invitation and only explicit acceptance grants membership',()=>{
 const room=make('location','Community center'),leader=make('character','Coordinator',{locationId:room.id}),candidate=make('character','Candidate',{playable:true,locationId:room.id},'owner'),hookId=randomUUID(),faction=make('faction','Mutual aid group',{leaderId:leader.id,territoryIds:[room.id],simulationPolicy:{enabled:true,intervalMinutes:60,maxEventsPerAdvance:10},eventHooks:[{id:hookId,outcome:'recruitment',priority:10,cooldownMinutes:1440,delivery:'in-person',requiresOrder:true,locationId:room.id,targetCharacterId:candidate.id,summary:'Invite the candidate to volunteer.'}]});
 const s=state([room,leader,candidate,faction]);advance(s,60,eventId,[],candidate.id);let membership=data(faction,'faction').memberships.find(row=>row.characterId===candidate.id)!;assert.equal(membership.status,'invited');assert.equal(data(candidate,'character').factionIds.includes(faction.id),false);assert.equal(data(faction,'faction').memberIds.includes(candidate.id),false);act(s,candidate.id,{type:'faction-membership',factionId:faction.id,operation:'accept'});membership=data(faction,'faction').memberships.find(row=>row.characterId===candidate.id)!;assert.equal(membership.status,'active');assert.equal(data(candidate,'character').factionIds.includes(faction.id),true);validateState(s);
});
