import {test} from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {actionSchema,data,settingsSchema,validateEntity,validateState} from '../src/game/model.ts';
import type {Entity,State} from '../src/game/model.ts';
import {resolveAction} from '../src/game/actions.ts';
import {observerView,project,visible} from '../src/game/epistemics.ts';
import {fixture,key} from './helpers.ts';
import {Game} from '../src/game/engine.ts';

const eventId='eeeeeeee-eeee-4eee-8eee-eeeeeeeeeeee',seed='5'.repeat(64);
const make=(kind:Entity['kind'],name:string,raw:Record<string,unknown>={},visibility:Entity['visibility']='campaign')=>validateEntity({id:randomUUID(),kind,name,visibility,data:raw});
const rules={dieSides:6,threshold:50,damage:10,treatmentMinutes:10,recoveryPerDay:1,unfamiliarPenalty:0,bleedPerMinute:0,formula:'additive-no-die' as const,outcomeMode:'legacy-binary' as const,outcomeBands:{criticalMargin:10,successAtCostMargin:2,partialFailureMargin:-2,failureInformationMargin:-10}};
const healthRules={infectionPerDay:2,untreatedSeverityPerDay:2,withdrawalPerDay:5,soberingPerHour:10,assessmentDifficulty:50,assessmentMinutes:5,firstAidDifficulty:50,firstAidQuality:80,restRecoveryMultiplier:2,bloodRecoveryPerDay:10,overdoseThreshold:100,unconsciousBloodThreshold:20,deathBloodThreshold:0};
const state=(entities:Entity[],settings:Record<string,unknown>={}):State=>({clock:'2012-06-01T12:00:00.000Z',settings:settingsSchema.parse(settings),entities,facts:[],knowledge:[],beliefs:[],memories:[],eventIds:[]});
const act=(s:State,actorId:string,raw:unknown,id=eventId)=>resolveAction(s,actorId,actionSchema.parse(raw),id,seed);

test('conditions preserve authored clinical detail while player views expose symptoms and assessment bands only',()=>{
 const room=make('location','Exam room'),patient=make('character','Patient',{locationId:room.id,blood:62,pain:73,intoxication:12}),clinician=make('character','Clinician',{locationId:room.id}),outsider=make('character','Outsider',{locationId:room.id}),wound=make('injury','Deep laceration',{characterId:patient.id,bodyPart:'left forearm',bodyRegion:'arm',side:'left',category:'laceration',severity:73,bleeding:41,pain:80,infection:17,startedAt:'2012-06-01T11:30:00.000Z',onsetAt:'2012-06-01T11:30:00.000Z',cause:{kind:'accident',sourceEntityId:null,sourceEventId:eventId,description:'Broken glass'},symptoms:[{name:'pain',severity:80,visibility:'patient',description:'Sharp pain'},{name:'redness',severity:40,visibility:'medical',description:'Possible infection'}],mechanicalImpact:{attributeModifiers:{Agility:-15},fatiguePerDay:5,movementPenalty:10,perceptionPenalty:0,incapacitateAtSeverity:null},treatmentRequirements:{requiredItemTags:['sterile-dressing'],minimumQuality:50,requiresClinical:false,stabilizationMinutes:10},course:{expectedDays:14,recoveryPerDay:4,deteriorationPerDay:2,infectionRisk:3,fatalAtSeverity:null,leavesScar:true,status:'acute',resolvedAt:null},healthVisibility:'hidden',knownByIds:[patient.id],eventLinks:[eventId]},'owner'),s=state([room,patient,clinician,outsider,wound],{rules,healthRules});
 validateState(s);assert.equal(visible(s,wound,patient.id),true);assert.equal(visible(s,wound,outsider.id),false);
 const patientProjection=project(s,wound,patient.id);assert.equal(patientProjection.data.category,'condition');assert.deepEqual((patientProjection.data.symptoms as Array<{name:string;intensity:string}>).map(row=>[row.name,row.intensity]),[['pain','severe']]);for(const hidden of ['severity','bleeding','infection','pain','mechanicalImpact','treatmentRequirements'])assert.equal(hidden in patientProjection.data,false);
 const characterProjection=project(s,patient,patient.id);assert.deepEqual(characterProjection.data.healthSummary,{condition:'conscious',blood:'reduced',pain:'high',fatigue:'low',intoxication:'low',withdrawal:'not-enabled',activeEffects:[]});for(const hidden of ['blood','pain','intoxication','withdrawal','withdrawalEnabled','activeSubstances'])assert.equal(hidden in characterProjection.data,false);
 const before=Date.parse(s.clock);act(s,patient.id,{type:'assess-health',injuryId:wound.id,method:'self'});assert.equal(Date.parse(s.clock)-before,5*60000);const assessed=project(s,wound,patient.id);assert.equal((assessed.data.assessment as {severityBand:string;diagnosis:string}).severityBand,'serious');assert.equal((assessed.data.assessment as {severityBand:string;diagnosis:string}).diagnosis,'Symptoms only');assert.equal('severity' in assessed.data,false);assert.ok(!observerView(s,outsider.id).entities.some(entity=>entity.id===wound.id));
});

test('first aid conserves supplies, costs authored time, enforces requirements, and records uncertain outcomes',()=>{
 const room=make('location','Kitchen'),patient=make('character','Patient',{locationId:room.id,attributes:{Strength:50,Agility:50,Endurance:50,Intellect:100,Perception:50,Presence:50,Will:50}}),wound=make('injury','Cut',{characterId:patient.id,bodyPart:'hand',bodyRegion:'hand',category:'cut',severity:45,bleeding:20,startedAt:'2012-06-01T12:00:00.000Z',treatmentRequirements:{requiredItemTags:['sterile-dressing'],minimumQuality:50,requiresClinical:false,stabilizationMinutes:15}},'owner'),wrong=make('item','Pain tablets',{category:'medicine',ownerId:patient.id,quantity:2,tags:['analgesic']}),kit=make('item','First-aid kit',{category:'medicine',ownerId:patient.id,quantity:2,tags:['sterile-dressing']}),s=state([room,patient,wound,wrong,kit],{rules,healthRules});
 assert.throws(()=>act(s,patient.id,{type:'treat',injuryId:wound.id,medicineId:wrong.id}),/treatment_requirement_unmet/);assert.equal(data(wrong,'item').quantity,2);
 const before=Date.parse(s.clock),result=act(s,patient.id,{type:'treat',injuryId:wound.id,medicineId:kit.id});assert.equal(Date.parse(s.clock)-before,15*60000);assert.equal(data(kit,'item').quantity,1);const treated=data(wound,'injury');assert.equal(treated.treated,true);assert.equal(treated.stabilized,true);assert.equal(treated.bleeding,0);assert.equal(treated.treatments.length,1);assert.equal(treated.treatments[0]!.outcome,'stabilized');assert.ok(result.checks.some(check=>check.context==='first-aid'));validateState(s);
});

test('rest and elapsed time follow authored recovery courses, restore blood gradually, and leave configured scars',()=>{
 const room=make('location','Bedroom'),patient=make('character','Patient',{locationId:room.id,blood:80}),wound=make('injury','Healing burn',{characterId:patient.id,bodyPart:'right arm',bodyRegion:'arm',side:'right',category:'burn',severity:48,bleeding:0,pain:30,treated:true,stabilized:true,startedAt:'2012-05-31T12:00:00.000Z',course:{expectedDays:2,recoveryPerDay:24,deteriorationPerDay:0,infectionRisk:0,fatalAtSeverity:null,leavesScar:true,status:'recovering',resolvedAt:null}},'owner'),s=state([room,patient,wound],{rules,healthRules});
 act(s,patient.id,{type:'sleep',minutes:720});assert.equal(data(wound,'injury').severity,24);assert.equal(data(patient,'character').blood,85);assert.equal(wound.archived,false);
 act(s,patient.id,{type:'sleep',minutes:720},'ffffffff-ffff-4fff-8fff-ffffffffffff');assert.equal(data(wound,'injury').severity,0);assert.equal(wound.archived,true);assert.ok(data(patient,'character').scars.includes('right arm scar'));validateState(s);
});

test('authored substances alter numeric capability without inventing conduct and expire with time',()=>{
 const room=make('location','Room'),patient=make('character','Patient',{locationId:room.id,attributes:{Strength:50,Agility:50,Endurance:50,Intellect:50,Perception:50,Presence:50,Will:50}}),dose=make('item','Authored sedative',{category:'drug',ownerId:patient.id,quantity:1,dose:20,substanceProfile:{kind:'medication',durationMinutes:30,intoxicationDelta:20,capabilityModifiers:{Perception:-15},painRelief:10,fatigueDelta:5,dependenceDelta:10,overdoseThreshold:90,withdrawalEnabled:false}}),s=state([room,patient,dose],{rules,healthRules});
 const consumed=act(s,patient.id,{type:'consume',itemId:dose.id});assert.equal(data(dose,'item').quantity,0);assert.ok(Math.abs(data(patient,'character').intoxication-(20-10/60))<1e-9);assert.equal(data(patient,'character').activeSubstances.length,1);assert.deepEqual(consumed.effects.map(effect=>effect.text),['Authored sedative consumed.']);
 const checked=act(s,patient.id,{type:'check',attribute:'Perception',skillId:null,checkId:null,context:'observation'},'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa');assert.ok(checked.checks[0]!.modifiers.some(modifier=>modifier.name==='Authored substance effect: Authored sedative'&&modifier.value===-15));const playerView=project(s,patient,patient.id);assert.equal('intoxication' in playerView.data,false);assert.equal((playerView.data.healthSummary as {intoxication:string}).intoxication,'low');
 act(s,patient.id,{type:'wait',minutes:1440},'bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb');assert.equal(data(patient,'character').activeSubstances.length,0);assert.equal(data(patient,'character').withdrawal,0);validateState(s);
});

test('death closes ordinary turns and persists remains, property, evidence, witnesses, and a protected continuation branch',async()=>{
 const f=await fixture(),game=new Game(f.store);try{
  const timeline=await game.initialize(f.creator,f.campaign.id),room=make('location','Scene'),player=make('character','Canonical player',{playable:true,controllerUserId:f.player.id,locationId:room.id},'owner'),witness=make('character','Witness',{locationId:room.id}),keepsake=make('item','Keepsake',{ownerId:player.id,possessorId:player.id,equipped:true},'owner'),fatal=make('injury','Fatal internal injury',{characterId:player.id,bodyPart:'torso',bodyRegion:'torso',category:'internal',severity:100,startedAt:'2012-06-01T12:00:00.000Z',cause:{kind:'accident',sourceEntityId:null,sourceEventId:eventId,description:'Authored fatal trauma'},course:{expectedDays:0,recoveryPerDay:0,deteriorationPerDay:0,infectionRisk:0,fatalAtSeverity:100,leavesScar:false,status:'acute',resolvedAt:null},knownByIds:[player.id],eventLinks:[eventId]},'owner');
  await game.bulkEdit(f.creator,timeline.id,{revision:1,entities:[room,player,witness,keepsake,fatal]},key());let revision=(await game.access(f.creator,timeline.id)).t.revision;await game.configure(f.creator,timeline.id,revision,settingsSchema.parse({rules,healthRules}),key());revision=(await game.access(f.player,timeline.id)).t.revision;
  const response=await game.turn(f.player,timeline.id,{revision,characterId:player.id,action:actionSchema.parse({type:'wait',minutes:1})},key()),transition=response.deathTransition;assert.ok(transition);assert.equal(transition!.mode,'load-or-branch');assert.ok(transition!.branchId);assert.deepEqual(transition!.options,['load-protected-branch','roster']);
  const current=await game.load(timeline.id),dead=data(current.entities.find(entity=>entity.id===player.id)!,'character'),record=current.entities.find(entity=>entity.kind==='deathRecord')!,death=data(record,'deathRecord'),remains=current.entities.find(entity=>entity.id===death.remainsId)!;assert.equal(dead.condition,'dead');assert.equal(dead.deathRecordId,record.id);assert.equal(data(entityFrom(current,keepsake.id),'item').containerId,remains.id);assert.ok(death.propertyIds.includes(keepsake.id));assert.ok(death.witnessIds.includes(witness.id));assert.ok(death.causeInjuryIds.includes(fatal.id));assert.ok(current.entities.some(entity=>entity.kind==='evidence'&&death.evidenceIds.includes(entity.id)));
  revision=(await game.access(f.player,timeline.id)).t.revision;await assert.rejects(()=>game.turn(f.player,timeline.id,{revision,characterId:player.id,action:actionSchema.parse({type:'look'})},key()),/character_cannot_act/);
  const protectedState=await game.load(transition!.branchId!);assert.equal(data(protectedState.entities.find(entity=>entity.id===player.id)!,'character').condition,'conscious');assert.equal(protectedState.entities.filter(entity=>entity.kind==='deathRecord').length,0);validateState(current);validateState(protectedState);
 }finally{await f.close();}
});

function entityFrom(s:State,id:string){return s.entities.find(entity=>entity.id===id)!;}
