import {test} from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {actionSchema,data,settingsSchema,validateEntity,validateState} from '../src/game/model.ts';
import type {Entity,State} from '../src/game/model.ts';
import {resolveAction} from '../src/game/actions.ts';
import {project} from '../src/game/epistemics.ts';
import {vehicleState} from '../src/game/vehicle.ts';
import {fixture,key} from './helpers.ts';
import {Game} from '../src/game/engine.ts';

const eventId='dddddddd-dddd-4ddd-8ddd-dddddddddddd',seed='4'.repeat(64);
const make=(kind:Entity['kind'],name:string,raw:Record<string,unknown>={},visibility:Entity['visibility']='campaign')=>validateEntity({id:randomUUID(),kind,name,visibility,data:raw});
const state=(entities:Entity[],settings:Record<string,unknown>={}):State=>({clock:'2012-06-01T12:00:00.000Z',settings:settingsSchema.parse(settings),entities,facts:[],knowledge:[],beliefs:[],memories:[],eventIds:[]});
const act=(s:State,actorId:string,raw:unknown)=>resolveAction(s,actorId,actionSchema.parse(raw),eventId,seed);
const rules={dieSides:6,threshold:1,damage:10,treatmentMinutes:1,recoveryPerDay:1,unfamiliarPenalty:0,bleedPerMinute:0,formula:'additive-no-die' as const,outcomeMode:'legacy-binary' as const,outcomeBands:{criticalMargin:10,successAtCostMargin:2,partialFailureMargin:-2,failureInformationMargin:-10}};

test('keys, shared grants, custody, forced entry, and hotwiring produce durable access and evidence state',()=>{
 const lot=make('location','Parking lot'),owner=make('character','Owner',{locationId:lot.id}),shared=make('character','Shared driver',{locationId:lot.id}),intruder=make('character','Intruder',{locationId:lot.id,attributes:{Strength:100,Agility:50,Endurance:50,Intellect:100,Perception:50,Presence:50,Will:50}}),witness=make('character','Witness',{locationId:lot.id}),garage=make('business','Garage',{locationId:lot.id}),keyItem=make('item','Car key',{category:'key',ownerId:owner.id,possessorId:owner.id}),vehicle=make('vehicle','Blue sedan',{ownerId:owner.id,registeredOwnerId:owner.id,locationId:lot.id,keyId:keyItem.id,plate:'VAL-220',vin:'VIN22',make:'Valor',model:'Sedan',color:'blue',accessGrants:[{characterId:shared.id,permissions:['enter','drive','trunk'],note:'shared permission'}]}),s=state([lot,owner,shared,intruder,witness,garage,keyItem,vehicle],{rules,vehicles:{hotwireDifficulty:1,forcedEntryDifficulty:1}});
 act(s,shared.id,{type:'vehicle-access',vehicleId:vehicle.id,operation:'unlock'});assert.equal(data(vehicle,'vehicle').locked,false);act(s,shared.id,{type:'vehicle-access',vehicleId:vehicle.id,operation:'enter'});assert.ok(data(vehicle,'vehicle').occupants.includes(shared.id));act(s,shared.id,{type:'vehicle-access',vehicleId:vehicle.id,operation:'leave'});act(s,shared.id,{type:'vehicle-access',vehicleId:vehicle.id,operation:'lock'});
 assert.throws(()=>act(s,intruder.id,{type:'vehicle-access',vehicleId:vehicle.id,operation:'unlock'}),/vehicle_access_denied/);act(s,intruder.id,{type:'vehicle-access',vehicleId:vehicle.id,operation:'force-entry'});act(s,intruder.id,{type:'vehicle-access',vehicleId:vehicle.id,operation:'hotwire'});
 assert.equal(data(vehicle,'vehicle').theftStatus,'stolen');assert.ok(data(vehicle,'vehicle').hotwiredByIds.includes(intruder.id));assert.ok(data(vehicle,'vehicle').damageRecords.length>=2);assert.ok(data(vehicle,'vehicle').witnessDescriptions.some(row=>row.witnessId===witness.id));assert.ok(s.entities.filter(entity=>entity.kind==='evidence'&&entity.data.objectId===vehicle.id).length>=2);
 act(s,owner.id,{type:'vehicle-custody',vehicleId:vehicle.id,operation:'assign',holderId:garage.id,role:'repair',note:'repair intake'});assert.equal(data(vehicle,'vehicle').custodyRole,'repair');act(s,owner.id,{type:'vehicle-custody',vehicleId:vehicle.id,operation:'return',note:'returned'});assert.equal(data(vehicle,'vehicle').custodianId,null);validateState(s);
});

test('driving consumes authored time, fuel, and condition while moving occupants and preserving trunk containment',()=>{
 const start=make('location','Start'),end=make('location','End'),driver=make('character','Driver',{locationId:start.id}),passenger=make('character','Passenger',{locationId:start.id}),vehicle=make('vehicle','Truck',{ownerId:driver.id,locationId:start.id,locked:false,occupants:[driver.id,passenger.id],fuel:50,condition:100,trunkCapacity:100}),cargo=make('item','Sealed cargo',{ownerId:driver.id,containerId:vehicle.id,weight:5}),origin=data(start,'location');origin.exits.push({to:end.id,minutes:10,modes:['drive'],locked:false,keyId:null,fare:0,interruption:null,terrainPenalty:0,trafficPenalty:0});start.data=origin as Entity['data'];const s=state([start,end,driver,passenger,vehicle,cargo],{fuel:true,vehicles:{fuelPerMinute:.2,conditionPerMinute:.1}});
 act(s,driver.id,{type:'travel',destinationId:end.id,mode:'drive',vehicleId:vehicle.id});const v=data(vehicle,'vehicle');assert.equal(s.clock,'2012-06-01T12:10:00.000Z');assert.equal(v.locationId,end.id);assert.equal(v.routeState,null);assert.equal(v.fuel,48);assert.equal(v.condition,99);assert.equal(v.odometerKm,5);assert.equal(data(driver,'character').locationId,end.id);assert.equal(data(passenger,'character').locationId,end.id);assert.equal(data(cargo,'item').containerId,vehicle.id);assert.deepEqual(v.history.slice(-2).map(row=>row.action),['departed','arrived']);assert.deepEqual(vehicleState(s,vehicle).trunkItemIds,[cargo.id]);validateState(s);
});

test('scheduled public transit is a service, charges fare, and includes schedule wait in travel time',()=>{
 const stop=make('location','Stop'),terminal=make('location','Terminal'),rider=make('character','Rider',{locationId:stop.id,cash:500}),operator=make('business','Transit authority',{locationId:stop.id}),service=make('transportService','Route 22',{operatorId:operator.id,mode:'bus',scheduleMode:'fixed',routes:[{fromId:stop.id,toId:terminal.id,departures:[485],minutes:20,fareCents:250}]}),s=state([stop,terminal,rider,operator,service]);
 act(s,rider.id,{type:'travel',destinationId:terminal.id,mode:'transit',vehicleId:null});assert.equal(s.clock,'2012-06-01T12:25:00.000Z');assert.equal(data(rider,'character').locationId,terminal.id);assert.equal(data(rider,'character').cash,250);assert.equal(s.entities.filter(entity=>entity.kind==='vehicle').length,0);validateState(s);
});

test('theft reports create cases and assigned searches discover stolen status as evidence without global disclosure',()=>{
 const street=make('location','Street'),owner=make('character','Owner',{locationId:street.id}),investigator=make('character','Investigator',{locationId:street.id,attributes:{Strength:50,Agility:50,Endurance:50,Intellect:50,Perception:100,Presence:50,Will:50}}),outsider=make('character','Outsider',{locationId:street.id}),agency=make('faction','Police',{memberIds:[investigator.id],jurisdictionIds:[street.id]}),vehicle=make('vehicle','Reported coupe',{ownerId:owner.id,registeredOwnerId:owner.id,locationId:street.id,stolen:true,theftStatus:'stolen',plate:'HOT-22',vin:'VIN-HIDDEN',color:'red'}),s=state([street,owner,investigator,outsider,agency,vehicle]);
 act(s,owner.id,{type:'report-vehicle-theft',vehicleId:vehicle.id,agencyId:agency.id,investigatorId:investigator.id});const report=data(vehicle,'vehicle').theftReports[0]!;assert.equal(report.status,'open');assert.ok(s.entities.some(entity=>entity.id===report.caseId&&entity.kind==='case'));const before=project(s,vehicle,outsider.id);assert.equal('vin' in before.data,false);assert.equal('stolen' in before.data,false);
 act(s,investigator.id,{type:'search',targetId:vehicle.id,method:'thorough',minutes:5,acceptRisk:true});assert.ok(data(vehicle,'vehicle').discoveredByIds.includes(investigator.id));assert.ok(s.entities.some(entity=>entity.kind==='evidence'&&data(entity,'evidence').objectId===vehicle.id&&data(entity,'evidence').discoveredBy.includes(investigator.id)));const investigatorView=project(s,vehicle,investigator.id);assert.equal(investigatorView.data.stolen,true);validateState(s);
});

test('vehicle repair and towing use authored services and persist records',()=>{
 const shop=make('location','Repair shop'),yard=make('location','Tow yard'),owner=make('character','Owner',{locationId:shop.id,cash:5000}),business=make('business','Auto service',{locationId:shop.id}),vehicle=make('vehicle','Damaged car',{ownerId:owner.id,locationId:shop.id,locked:false,condition:40,components:{engine:30},damageRecords:[{id:randomUUID(),at:'2012-05-31T12:00:00.000Z',eventId:null,kind:'mechanical',component:'engine',severity:60,description:'Engine fault',repairedAt:null}]}),repair=make('service','Engine repair',{businessId:business.id,category:'vehicle-repair',minutes:60,costCents:1000,vehicleConditionRestore:30,vehicleComponent:'engine'}),tow=make('service','Tow to yard',{businessId:business.id,category:'towing',minutes:15,costCents:500,destinationId:yard.id}),s=state([shop,yard,owner,business,vehicle,repair,tow]);
 act(s,owner.id,{type:'vehicle-service',vehicleId:vehicle.id,serviceId:repair.id});assert.equal(data(vehicle,'vehicle').condition,70);assert.equal(data(vehicle,'vehicle').components.engine,60);assert.ok(data(vehicle,'vehicle').damageRecords[0]!.repairedAt);assert.equal(data(vehicle,'vehicle').repairRecords.length,1);act(s,owner.id,{type:'vehicle-service',vehicleId:vehicle.id,serviceId:tow.id});assert.equal(data(vehicle,'vehicle').locationId,yard.id);assert.equal(data(owner,'character').cash,3500);assert.ok(data(vehicle,'vehicle').history.some(row=>row.action==='towed'));validateState(s);
});

test('vehicle identity, trunk contents, theft state, and travel history survive save and branch restoration',async()=>{
 const f=await fixture(),game=new Game(f.store);try{const timeline=await game.initialize(f.creator,f.campaign.id),start=make('location','Start'),end=make('location','End'),driver=make('character','Driver',{playable:true,controllerUserId:f.player.id,locationId:start.id},'owner'),vehicle=make('vehicle','Persistent car',{ownerId:driver.id,registeredOwnerId:driver.id,locationId:start.id,locked:false,occupants:[driver.id],plate:'SAVE-22',vin:'VIN-SAVE-22',stolen:true,theftStatus:'stolen'},'owner'),cargo=make('item','Trunk evidence',{ownerId:driver.id,containerId:vehicle.id},'owner'),origin=data(start,'location');origin.exits.push({to:end.id,minutes:10,modes:['drive'],locked:false,keyId:null,fare:0,interruption:null,terrainPenalty:0,trafficPenalty:0});start.data=origin as Entity['data'];await game.bulkEdit(f.creator,timeline.id,{revision:1,entities:[start,end,driver,vehicle,cargo]},key());const revision=(await game.access(f.player,timeline.id)).t.revision;await game.turn(f.player,timeline.id,{revision,characterId:driver.id,action:actionSchema.parse({type:'travel',destinationId:end.id,mode:'drive',vehicleId:vehicle.id})},key());const save=await game.save(f.player,timeline.id,'Vehicle persistence'),branch=await game.branch(f.player,timeline.id,save.id,'Vehicle branch'),restored=await game.load(branch.id),restoredVehicle=restored.entities.find(entity=>entity.id===vehicle.id)!;assert.equal(data(restoredVehicle,'vehicle').vin,'VIN-SAVE-22');assert.equal(data(restoredVehicle,'vehicle').locationId,end.id);assert.equal(data(restoredVehicle,'vehicle').theftStatus,'stolen');assert.ok(data(restoredVehicle,'vehicle').history.some(row=>row.action==='arrived'));assert.equal(restored.entities.find(entity=>entity.id===cargo.id)!.data.containerId,vehicle.id);validateState(restored);}finally{await f.close();}
});
