import {test} from 'node:test';
import assert from 'node:assert/strict';
import {performance} from 'node:perf_hooks';
import {data,settingsSchema,validateEntity,type State} from '../src/game/model.ts';
import {npcProfileSchema} from '../src/game/behavior-contracts.ts';
import {behaviorActor,behaviorId,behaviorHash,behaviorProfile,publishBehaviorProfile,bindBehaviorTimeline,decideNpcBehavior,addBehaviorGoal,buildNpcBehaviorContext,finishNpcBehavior,wakeBehavior,updateBehaviorConflict,promoteBehavior} from '../src/game/behavior.ts';
import {reserveBehaviorResources,releaseBehaviorLeases,expireBehaviorLeases,applyBehaviorDevelopments,bypassBehaviorCooldown,validateProviderActions} from '../src/game/behavior-extensions.ts';
import {advance,type Effect} from '../src/game/simulation.ts';
import {recordObservation,information,addProposition,acquireInformation} from '../src/game/information.ts';
import {withTurnRuntime} from '../src/game/turn-runtime.ts';
import {NpcBehaviorPlanner} from '../src/game/behavior-planner.ts';
import {Game} from '../src/game/engine.ts';
import {TurnKernel} from '../src/game/turn-kernel.ts';
import {resolveAction} from '../src/game/actions.ts';
import {fixture,key,login} from './helpers.ts';
const id=(value:string)=>behaviorId('system05-completion-v1',value);
function fixtureState(){
 const room=validateEntity({id:id('room'),kind:'location',name:'Shop',visibility:'campaign',data:{}}),pc=validateEntity({id:id('pc'),kind:'character',name:'Pat',visibility:'campaign',data:{playable:true,locationId:room.id}}),npc=validateEntity({id:id('npc'),kind:'character',name:'Clerk',visibility:'campaign',data:{locationId:room.id,plans:[{id:id('plan'),type:'domain',targetId:id('item'),cooldownMinutes:15}]}}),item=validateEntity({id:id('item'),kind:'item',name:'Key',visibility:'campaign',data:{locationId:room.id}});
 const s:State={clock:'2012-06-01T12:00:00.000Z',entities:[room,pc,npc,item],settings:settingsSchema.parse({contextTokens:8000}),facts:[],knowledge:[],beliefs:[],memories:[]};
 const p=npcProfileSchema.parse({actorId:npc.id,version:'v1',traits:{caution:500},motives:[{id:'duty',description:'Keep the shop'}],providerActions:[{planId:id('plan'),action:{type:'take',itemId:item.id},durationSeconds:60,resourceIds:[item.id]}]});publishBehaviorProfile(s,p,id('publish'));bindBehaviorTimeline(s,id('branch'));information(s).memoryTimelineId=id('branch');return {s,room,pc,npc,item,p};
}
function run(s:State,pcId:string,minutes:number,key='tick'){const effects:Effect[]=[];withTurnRuntime(key,id(key),s,'spacetime',()=>advance(s,minutes,id(key),effects,pcId));return effects;}
function evidence(s:State,actorId:string,kind:string,n=0){const ref=id(kind+':'+n);recordObservation(s,{id:ref,observerId:actorId,eventId:id('source:'+kind+':'+n),at:s.clock,locationId:id('room'),channel:'vision',targetId:null,raw:'Observed '+kind,clarity:1,confidence:1,attention:'focused',conditions:{kind},recognition:'unidentified',recognizedAsId:null,salience:1,propositionIds:[]});return ref;}

test('S05 frozen pending actions cannot transfer ownership; resumed actions revalidate expired leases',()=>{
 const {s,npc,pc,item}=fixtureState();run(s,pc.id,15);const a=behaviorActor(s,npc.id);a.frozen=true;run(s,pc.id,10,'frozen');assert.equal(item.data.possessorId,null);assert.ok(a.pendingDomain);a.frozen=false;run(s,pc.id,1,'resume');assert.equal(item.data.possessorId,null);assert.equal(a.pendingDomain,null);assert.equal(a.attempts[0]!.status,'FAILED');
});

test('S05 equivalent ISO timestamps consume one due wake and recover once',()=>{
 const {s,npc}=fixtureState();s.clock='2012-06-01T12:00:00Z';const a=behaviorActor(s,npc.id);wakeBehavior(s,npc.id,id('timestamp-wake'),'observed',true);s.clock='2012-06-01T12:00:00.000Z';decideNpcBehavior(s,npc.id,id('timestamp-decision'));assert.equal(a.wakes.length,0);assert.equal(a.recoveredAt,s.clock);
});

test('S05 T004 a provider configuration failure rolls back the entire coordinated attempt',async()=>{
 const f=await fixture();try{const game=new Game(f.store),t=await game.initialize(f.creator,f.campaign.id),{s,p,pc}=fixtureState();await game.bulkEdit(f.creator,t.id,{revision:1,entities:s.entities},key());await game.mutate(f.creator,t.id,2,key(),{},'creator.npc-behavior',true,(state,eventId)=>{publishBehaviorProfile(state,{...p,providerActions:[{...p.providerActions[0],durationSeconds:1}]},eventId);return {result:{ok:true}};});const before=behaviorHash(await game.load(t.id));await assert.rejects(game.mutate(f.creator,t.id,3,key(),{},'creator.npc-behavior',true,(state,eventId)=>{withTurnRuntime('failure',eventId,state,'spacetime',()=>advance(state,16,eventId,[],pc.id));return {result:{ok:true}};}),/behavior_duration_insufficient/);assert.equal(behaviorHash(await game.load(t.id)),before);
 }finally{await f.close();}
});

test('S05 T066 T069 planner outage has bounded attempts, no time advance, and a replayable deterministic fallback',async()=>{
 const f=await fixture();try{const game=new Game(f.store),t=await game.initialize(f.creator,f.campaign.id),{s,p,pc,npc}=fixtureState();pc.data.controllerUserId=f.player.id;await game.bulkEdit(f.creator,t.id,{revision:1,entities:s.entities},key());await game.mutate(f.creator,t.id,2,key(),{},'creator.npc-behavior',true,(state,eventId)=>{state.settings.contextTokens=8000;state.settings.tokenBudget=100000;state.settings.userTokenBudget=100000;publishBehaviorProfile(state,{...p,planner:{enabled:true,provider:'outage'}},eventId);return {result:{ok:true}};});let calls=0;const planner=new NpcBehaviorPlanner(game,[{id:'outage',complete:async()=>{calls++;throw new Error('provider_unavailable');}}]),commandId=id('outage'),before=behaviorHash(await game.load(t.id));assert.deepEqual(await planner.prepare(f.player,t.id,pc.id,3,commandId),[]);assert.ok(calls>=1&&calls<=2);const original=calls;assert.deepEqual(await planner.prepare(f.player,t.id,pc.id,3,commandId),[]);assert.equal(calls,original);assert.equal(behaviorHash(await game.load(t.id)),before);const result=await new TurnKernel(game,undefined,planner).execute(f.player,{commandId,sessionId:t.id,actorId:pc.id,expectedRevision:3,mode:'GAME',input:{kind:'action',action:{type:'wait',minutes:16}}});assert.equal(result.revision,4);const after=await game.load(t.id);assert.equal(after.entities.find(e=>e.id===id('item'))!.data.possessorId,npc.id);assert.ok(after.npcBehavior!.decisions.every(d=>d.source==='DETERMINISTIC'));assert.equal(calls,original);
 }finally{await f.close();}
});

test('S05 T067 concurrent and late planner responses cannot duplicate a call or escape its deadline',async()=>{
 const f=await fixture();try{const game=new Game(f.store),t=await game.initialize(f.creator,f.campaign.id),{s,p,pc}=fixtureState();pc.data.controllerUserId=f.player.id;await game.bulkEdit(f.creator,t.id,{revision:1,entities:s.entities},key());await game.mutate(f.creator,t.id,2,key(),{},'creator.npc-behavior',true,(state,eventId)=>{state.settings.contextTokens=8000;state.settings.tokenBudget=100000;state.settings.userTokenBudget=100000;publishBehaviorProfile(state,{...p,planner:{enabled:true,provider:'late'}},eventId);return {result:{ok:true}};});let calls=0,started!:()=>void,finish!:(value:any)=>void,traceId='';const begun=new Promise<void>(resolve=>{started=resolve;}),planner=new NpcBehaviorPlanner(game,[{id:'late',complete:async request=>{calls++;traceId=request.traceId;started();return new Promise(resolve=>{finish=resolve;});}}]),commandId=id('late-request'),before=behaviorHash(await game.load(t.id)),began=performance.now(),first=planner.prepare(f.player,t.id,pc.id,3,commandId);await begun;assert.deepEqual(await planner.prepare(f.player,t.id,pc.id,3,commandId),[]);assert.deepEqual(await first,[]);assert.ok(performance.now()-began<3500);finish({traceId,output:{planIds:[id('plan')]},usage:{inputTokens:1,outputTokens:1},toolCalls:[]});await Promise.resolve();assert.deepEqual(await planner.prepare(f.player,t.id,pc.id,3,commandId),[]);assert.equal(calls,1);assert.equal(behaviorHash(await game.load(t.id)),before);
 }finally{await f.close();}
});

test('S05 T073 T113 owner acquisition is delayed, contended, conserved and idempotently reserved',()=>{
 const {s,npc,item,pc,p}=fixtureState(),other=validateEntity({...npc,id:id('other'),name:'Other',data:{...npc.data,plans:[{...data(npc,'character').plans[0],id:id('other-plan')}]}});s.entities.push(other);publishBehaviorProfile(s,{...p,actorId:other.id,providerActions:[{...p.providerActions[0],planId:id('other-plan')}]},id('other-publish'));
 run(s,pc.id,15);assert.equal(item.data.possessorId,null);assert.equal(s.npcBehavior!.leases.filter(l=>l.status==='ACTIVE').length,1);const before=s.entities.filter(e=>e.kind==='item').reduce((n,e)=>n+Number(e.data.quantity),0);run(s,pc.id,1,'finish');assert.ok([npc.id,other.id].includes(String(item.data.possessorId)));assert.equal(s.entities.filter(e=>e.kind==='item').reduce((n,e)=>n+Number(e.data.quantity),0),before);assert.equal(s.npcBehavior!.actors.flatMap(a=>a.attempts).filter(a=>a.status==='SUCCEEDED').length,1);
});
test('S05 T074 expired reservations release without transferring the resource',()=>{
 const {s,npc,pc,item,p}=fixtureState();publishBehaviorProfile(s,{...p,version:'short-lease',providerActions:[{...p.providerActions[0],reservationSeconds:1}]},id('short'));run(s,pc.id,16);assert.equal(item.data.possessorId,null);assert.ok(s.npcBehavior!.leases.some(l=>l.status==='EXPIRED'));assert.equal(behaviorActor(s,npc.id).attempts[0]!.status,'FAILED');
});
test('S05 T016 T003 a believed-unlocked door is attempted and failure is learned through its owner',()=>{
 const {s,npc,pc,item,p}=fixtureState();item.data=validateEntity({...item,data:{...item.data,locked:true,mechanism:{kind:'door'}}}).data;
 publishBehaviorProfile(s,{...p,version:'door',providerActions:[{planId:id('plan'),action:{type:'physical',operation:'open',targetId:item.id},durationSeconds:60}]},id('door-profile'));run(s,pc.id,15);assert.ok(behaviorActor(s,npc.id).pendingDomain);run(s,pc.id,1,'door-finish');assert.equal(item.data.locked,true);assert.equal(behaviorActor(s,npc.id).attempts[0]!.status,'FAILED');assert.ok(s.information!.observations.some(o=>o.observerId===npc.id&&/locked/.test(o.raw)));
});
test('S05 T058 incapacity before a delayed domain step invalidates acquisition',()=>{
 const {s,npc,pc,item}=fixtureState();run(s,pc.id,15);npc.data.condition='unconscious';npc.data.restrainedBy=pc.id;run(s,pc.id,1,'incapacitated');assert.equal(item.data.possessorId,null);assert.equal(behaviorActor(s,npc.id).attempts[0]!.status,'FAILED');
});
test('S05 T006 T047 migrated permissions cancel a pending domain step and release all leases',()=>{
 const {s,npc,pc,item,p}=fixtureState();run(s,pc.id,15);publishBehaviorProfile(s,{...p,version:'revoked',boundaryPolicies:[{id:'closed',action:'domain',permission:'refuse',reason:'Permission withdrawn'}]},id('revoke'));run(s,pc.id,1,'revoked');assert.equal(item.data.possessorId,null);assert.equal(behaviorActor(s,npc.id).pendingDomain,null);assert.equal(s.npcBehavior!.leases.filter(l=>l.status==='ACTIVE').length,0);
});
test('S05 T049 new evidence bypass is scoped, causal, and consumed once',()=>{
 const {s,npc,p}=fixtureState();publishBehaviorProfile(s,{...p,version:'bypass',cooldownBypasses:[{id:'new-key',planId:id('plan'),observationKind:'key-delivered'}]},id('bypass-profile'));const started=s.clock;s.clock='2012-06-01T12:01:00.000Z';evidence(s,npc.id,'key-delivered');const a=behaviorActor(s,npc.id),profile=behaviorProfile(s,npc.id)!;assert.equal(bypassBehaviorCooldown(s,profile,a,id('plan'),started),true);assert.equal(bypassBehaviorCooldown(s,profile,a,id('plan'),started),false);assert.equal(a.bypasses.length,1);
});
test('S05 T044 published milestone permits bounded major development with immutable causal history',()=>{
 const {s,npc,p}=fixtureState(),goal=addBehaviorGoal(s,{id:id('goal'),actorId:npc.id,motiveRef:'duty',planId:id('plan'),priority:100,createdByEventId:id('goal-source')});publishBehaviorProfile(s,{...p,version:'milestone',milestones:[{id:'earned-trust',trait:'caution',delta:-150,requiredGoalIds:[goal.id],minimumEvidence:1}]},id('milestone-profile'));applyBehaviorDevelopments(s,npc.id,id('not-yet'));assert.equal(behaviorProfile(s,npc.id)!.traits.caution,500);goal.status='SATISFIED';goal.evidenceEventIds=[id('owner-outcome')];applyBehaviorDevelopments(s,npc.id,id('milestone-met'));assert.equal(behaviorProfile(s,npc.id)!.traits.caution,350);assert.equal(behaviorActor(s,npc.id).milestoneHistory.length,1);applyBehaviorDevelopments(s,npc.id,id('duplicate'));assert.equal(behaviorProfile(s,npc.id)!.traits.caution,350);assert.ok(s.npcBehavior!.profiles.some(p=>p.version==='milestone'&&p.traits.caution===500));
});
test('S05 T042 T043 causal ordinary development applies only unlocked rules and cannot reuse evidence',()=>{
 const {s,npc,p}=fixtureState();publishBehaviorProfile(s,{...p,version:'develop',adaptation:{unlocked:['caution']},developments:[{id:'practice',trait:'caution',observationKind:'kept-promise',delta:-20}]},id('develop-profile'));for(let i=0;i<3;i++)evidence(s,npc.id,'kept-promise',i);applyBehaviorDevelopments(s,npc.id,id('develop'));assert.equal(behaviorProfile(s,npc.id)!.traits.caution,480);applyBehaviorDevelopments(s,npc.id,id('develop2'));assert.equal(behaviorProfile(s,npc.id)!.traits.caution,480);
});
test('S05 T054 T022 authored bias and relationship modifiers require perceived recognized scope',()=>{
 const {s,npc,pc,p}=fixtureState();const c=data(npc,'character');c.plans[0]!.type='socialize';c.plans[0]!.targetId=pc.id;npc.data=c;pc.data.tags=['approved-cue'];pc.data.profileVisibility={...(pc.data.profileVisibility as Record<string,string>),tags:'campaign'};publishBehaviorProfile(s,{...p,version:'bias',providerActions:[],biases:[{id:'authored',attribute:'tags',equals:'approved-cue',action:'socialize',feature:'S',delta:-100,rationale:'Specific authored character belief',approval:'APPROVED',sourceEventId:id('approval')}]},id('bias'));s.clock='2012-06-01T12:15:00.000Z';const normal=structuredClone(s),concealed=structuredClone(s);concealed.entities.find(e=>e.id===pc.id)!.data.identityDisclosure={concealed:true,label:'a stranger',knownByIds:[]};const a=decideNpcBehavior(normal,npc.id,id('bias-case')),b=decideNpcBehavior(concealed,npc.id,id('bias-case'));assert.equal(b.candidates[0]!.features.S-a.candidates[0]!.features.S,100);
});
test('S05 T064 seeded weighted near-tie variation records the draw and survives replay',()=>{
 const {s,npc,p}=fixtureState();publishBehaviorProfile(s,{...p,version:'variation',policy:{...p.policy,variation:{enabled:true,band:1000}}},id('variation'));s.clock='2012-06-01T12:15:00.000Z';const clone=structuredClone(s),a=decideNpcBehavior(s,npc.id,id('variation-draw')),b=decideNpcBehavior(clone,npc.id,id('variation-draw'));assert.ok(a.draw);assert.deepEqual(a,b);assert.equal(decideNpcBehavior(s,npc.id,id('variation-draw')),a);
});
test('S05 T075 T079 routine checkpoints do not replay completed acquisition after a question handoff',()=>{
 const {s,npc,pc,p,item}=fixtureState(),c=data(npc,'character');c.plans.push({...c.plans[0]!,id:id('question'),type:'speak',targetId:pc.id,text:'Would you like directions?',speechRequiresResponse:true});npc.data=c;publishBehaviorProfile(s,{...p,version:'routine',routines:[{id:'shop',planIds:[id('plan'),id('question')]}],preferences:[{planId:id('plan'),features:{G:1000,N:0,V:1000,O:0,S:0,R:0,E:0,P:0}}]},id('routine'));run(s,pc.id,17);assert.equal(item.data.possessorId,npc.id);assert.equal(behaviorActor(s,npc.id).attempts.filter(a=>a.planId===id('plan')&&a.status==='SUCCEEDED').length,1);assert.ok(s.npcBehavior!.decisions.some(d=>d.nextControl==='PLAYER'));
});
test('S05 T055 unsupported or uncaused violence fails before execution even with maximum anger',()=>{
 const {s,npc,p,pc}=fixtureState();assert.throws(()=>publishBehaviorProfile(s,{...p,version:'attack',providerActions:[{planId:id('plan'),action:{type:'attack',targetId:pc.id},durationSeconds:60}]},id('bad-attack')),/violence_policy/);behaviorActor(s,npc.id).emotion.anger=1000;assert.equal(s.entities.filter(e=>e.kind==='injury').length,0);
});

test('S05 T056 T071 T072 caused combat uses owner checks and yields the real initiative turn',()=>{
 const {s,npc,pc,p}=fixtureState();s.settings=settingsSchema.parse({...s.settings,rules:{dieSides:6,threshold:50,damage:2,treatmentMinutes:10,recoveryPerDay:1,unfamiliarPenalty:0,bleedPerMinute:0,formula:'additive-no-die',outcomeMode:'legacy-binary'}});npc.data.attributes={...(npc.data.attributes as object),Strength:100,Agility:100};pc.data.attributes={...(pc.data.attributes as object),Agility:1};const c=data(npc,'character');c.plans[0]!.targetId=pc.id;npc.data=c;publishBehaviorProfile(s,{...p,version:'combat-owner',providerActions:[{planId:id('plan'),action:{type:'attack',targetId:pc.id,bodyPart:'torso'},durationSeconds:60,violence:'defense',causeKinds:['threat']}]},id('combat-profile'));
 withTurnRuntime('combat',id('start-combat'),s,'conflict',()=>resolveAction(s,npc.id,{type:'combat',targetId:pc.id},id('start-combat'),'24'.repeat(32),{coordinatedNpc:true}));s.clock='2012-06-01T12:15:00.000Z';evidence(s,npc.id,'threat');const effects=run(s,pc.id,5,'combat-step');assert.equal(s.clock,'2012-06-01T12:16:00.000Z');assert.ok(s.entities.some(e=>e.kind==='injury'&&e.data.characterId===pc.id));const combat=data(s.entities.find(e=>e.kind==='combat')!,'combat');assert.equal(combat.turnOrder[combat.turnIndex],pc.id);assert.equal(combat.actorStates[pc.id]!.actionPoints,1);assert.ok(effects.some(e=>e.requiresPlayerResponse&&e.observers.includes(pc.id)));const receipt=s.npcBehavior!.decisions.find(d=>d.selectedPlanId===id('plan'))!;assert.equal(receipt.nextControl,'PLAYER');assert.ok((receipt.providerReceipt as any).checks.length);assert.equal(behaviorActor(s,npc.id).attempts[0]!.status,'SUCCEEDED');
 const injuryCount=s.entities.filter(e=>e.kind==='injury').length;npc.data.goals=['attack'];publishBehaviorProfile(s,{...behaviorProfile(s,npc.id)!,version:'combat-refusal',anchors:[{id:'no-force',kind:'HARD',action:'domain',allow:false}]},id('refuse-force'));withTurnRuntime('defend',id('player-defense'),s,'conflict',()=>resolveAction(s,pc.id,{type:'defend',defense:'dodge'},id('player-defense'),'25'.repeat(32)));assert.equal(s.entities.filter(e=>e.kind==='injury').length,injuryCount);assert.equal(data(s.entities.find(e=>e.kind==='combat')!,'combat').turnOrder[data(s.entities.find(e=>e.kind==='combat')!,'combat').turnIndex],pc.id);
});
test('S05 T068 action adapters reject invented actions, participant control and cyclic routine IDs',()=>{
 const {s,p}=fixtureState();for(const action of [{type:'teleport',targetId:id('unknown')},{type:'persuade',targetId:id('pc'),goal:'confess',approach:'order'}])assert.throws(()=>publishBehaviorProfile(s,{...p,version:'invalid',providerActions:[{planId:id('plan'),action,durationSeconds:60}]},id('invalid')));assert.throws(()=>publishBehaviorProfile(s,{...p,version:'cycle',routines:[{id:'cycle',planIds:[id('plan'),id('plan')]}]},id('cycle')),/routine/);
});

test('S05 T066 T067 T069 optional live adapter proposal is persisted, replayable and bounded by revision',async()=>{
 const f=await fixture();try{const game=new Game(f.store),t=await game.initialize(f.creator,f.campaign.id),{s,npc,pc,p}=fixtureState();pc.data.controllerUserId=f.player.id;await game.bulkEdit(f.creator,t.id,{revision:1,entities:s.entities},key());await game.mutate(f.creator,t.id,2,key(),{},'creator.npc-behavior',true,(state,eventId)=>{state.settings.contextTokens=8000;state.settings.tokenBudget=100000;state.settings.userTokenBudget=100000;publishBehaviorProfile(state,{...p,planner:{enabled:true,provider:'test-npc'}},eventId);return {result:{published:true}};});
 let calls=0;const planner=new NpcBehaviorPlanner(game,[{id:'test-npc',complete:async request=>{calls++;return {traceId:request.traceId,output:{planIds:[id('plan')]},usage:{inputTokens:100,outputTokens:20},toolCalls:[]};}}]);const commandId=id('network-plan'),before=(await game.load(t.id)).clock,first=await planner.prepare(f.player,t.id,pc.id,3,commandId);assert.equal(first.length,1);assert.equal(calls,1);assert.equal((await game.load(t.id)).clock,before);assert.deepEqual(await planner.prepare(f.player,t.id,pc.id,3,commandId),first);assert.equal(calls,1);
 const kernel=new TurnKernel(game,undefined,planner),command={commandId,sessionId:t.id,actorId:pc.id,expectedRevision:3,mode:'GAME',input:{kind:'action',action:{type:'wait',minutes:16}}};const result=await kernel.execute(f.player,command);assert.deepEqual(await kernel.execute(f.player,command),result);assert.equal(calls,1);const committed=await game.load(t.id);assert.ok(committed.npcBehavior!.decisions.some(d=>d.source==='RECORDED_AI'));assert.equal(committed.entities.find(e=>e.id===id('item'))!.data.possessorId,npc.id);
 }finally{await f.close();}
});

test('S05 T114 bounded wake and decision histories fail explicitly instead of dropping critical work',()=>{
 const {s,npc}=fixtureState(),a=behaviorActor(s,npc.id);a.wakes=Array.from({length:1000},(_,n)=>({key:String(n),causeId:id('wake'+n),dueAt:s.clock,mandatory:true,kind:'threat'}));const snapshot=behaviorHash(s);assert.throws(()=>wakeBehavior(s,npc.id,id('overflow-wake'),'threat',true),/wake_queue_full/);assert.equal(behaviorHash(s),snapshot);s.npcBehavior!.decisions=Array.from({length:10000},(_,n)=>({id:id('historic'+n)})) as any;assert.throws(()=>decideNpcBehavior(s,npc.id,id('overflow')),/history_capacity/);assert.equal(a.wakes.length,1000);
});
test('S05 T109 T110 resource outcomes and pending tasks are invariant under fractional interval partitions',()=>{
 const {s,npc,pc}=fixtureState(),whole=structuredClone(s),parts=structuredClone(s);run(whole,pc.id,16,'partition');withTurnRuntime('partition',id('partition'),parts,'spacetime',()=>{for(const n of [0.25,0.75,4,3,1.5,6.5])advance(parts,n,id('partition'),[],pc.id);});assert.equal(whole.clock,parts.clock);console.log('SYSTEM05_DETERMINISM '+JSON.stringify({fixture:'system05-completion-v1',behaviorHash:behaviorHash(whole.npcBehavior),partitionedBehaviorHash:behaviorHash(parts.npcBehavior),itemHash:behaviorHash(whole.entities.find(e=>e.id===id('item'))),partitionedItemHash:behaviorHash(parts.entities.find(e=>e.id===id('item')))}));assert.deepEqual(behaviorActor(whole,npc.id),behaviorActor(parts,npc.id));assert.deepEqual(whole.npcBehavior!.decisions,parts.npcBehavior!.decisions);assert.deepEqual(data(whole.entities.find(e=>e.id===id('item'))!,'item'),data(parts.entities.find(e=>e.id===id('item'))!,'item'));
});
test('S05 T105 branch invalidates accepted planner input and uncommitted resource leases',()=>{
 const {s,npc,pc,item}=fixtureState();run(s,pc.id,15);s.npcBehavior!.plannerInputs.push({id:id('pending-ai'),actorId:npc.id,branchId:id('branch'),profileVersion:'v1',baseRevision:0,generation:0,contextHash:'old',planIds:[id('plan')],status:'ACCEPTED',proposal:{planIds:[id('plan')]},eventId:id('cause')});bindBehaviorTimeline(s,id('child'));assert.equal(behaviorActor(s,npc.id).pendingDomain,null);assert.equal(s.npcBehavior!.plannerInputs[0]!.status,'STALE');assert.equal(s.npcBehavior!.leases.filter(l=>l.status==='ACTIVE').length,0);assert.equal(item.data.possessorId,null);
});
test('S05 T117 optional context exclusion cannot be bypassed by direct condition reads',()=>{
 const {s,npc,pc,p}=fixtureState(),claim=addProposition(s,{id:id('excluded-claim'),subjectId:pc.id,predicate:'late',value:true,validFrom:s.clock,truth:'true'});acquireInformation(s,{characterId:npc.id,propositionId:claim.id,type:'belief',confidence:0.5,acquisition:'testimony',sourceId:id('source'),originIds:[],informationAt:s.clock,lastConfirmedAt:null,freshness:'current',secrecyAwareness:'unknown',text:'Claim '.repeat(1000)});const c=data(npc,'character');c.plans[0]!.conditions=[{kind:'fact',subjectId:pc.id,targetId:null,predicate:'late',value:true,at:null,threshold:0,state:'',negate:false}];npc.data=c;s.settings.contextTokens=2000;s.clock='2012-06-01T12:15:00.000Z';const d=decideNpcBehavior(s,npc.id,id('excluded'));assert.notEqual(d.result,'SELECTED');
});
test('S05 T060 returning to calm never reverses external injury, currency or historical claims',()=>{
 const {s,npc}=fixtureState(),a=behaviorActor(s,npc.id);npc.data.cash=137;a.conflicts.test={stage:'RECOVERING',threat:0,changedAt:s.clock,sourceIds:[id('conflict')]};evidence(s,npc.id,'ended-conflict');const owners=behaviorHash({entities:s.entities,information:s.information});updateBehaviorConflict(a,behaviorProfile(s,npc.id)!,'test',0,[id('ended')],new Date(Date.parse(s.clock)+31000).toISOString());assert.equal(a.conflicts.test.stage,'CALM');assert.equal(behaviorHash({entities:s.entities,information:s.information}),owners);
});
test('S05 T086 T087 T088 T089 materialization and promotion use stable identity through the real API',async()=>{
 const f=await fixture();try{const game=new Game(f.store),t=await game.initialize(f.creator,f.campaign.id),{s,room}=fixtureState();await game.bulkEdit(f.creator,t.id,{revision:1,entities:s.entities},key());const auth=await login(f),base='/game/timelines/'+t.id+'/npc-behavior/command';let revision=2;
 const command=async(command:unknown)=>{const r=await f.app.inject({method:'POST',url:base,headers:{cookie:auth.cookie,'x-csrf-token':auth.csrf,origin:f.settings.origin,'idempotency-key':key()},payload:{revision,command}});assert.equal(r.statusCode,200,r.body);revision=r.json().revision;return r.json();};
 const body={operation:'materialize',seed:'crowd-24',name:'Visitor',locationId:room.id,reason:'Consequential interaction'},first=await command(body);const actorId=first.behavior.actorId;await command({...body,name:'Ignored new name'});const before=(await game.load(t.id)).entities.find(e=>e.id===actorId)!;assert.equal(before.name,'Visitor');for(const reason of ['appearance observed','conversation begun'])await command({operation:'promote',actorId,reason});const after=await game.load(t.id);assert.equal(after.entities.filter(e=>e.id===actorId).length,1);assert.deepEqual(after.entities.find(e=>e.id===actorId),before);assert.equal(behaviorActor(after,actorId).promotions.length,1);assert.equal(after.npcBehavior!.interventions.filter(e=>e.actorId===actorId&&e.operation==='promote').length,2);assert.equal(after.entities.find(e=>e.id===actorId)!.data.description,'');
 }finally{await f.close();}
});

test('S05 T098 T099 T107 published templates pin instances and repair releases only unfinished work',async()=>{
 const f=await fixture();try{const game=new Game(f.store),t=await game.initialize(f.creator,f.campaign.id),{s,npc,pc,p}=fixtureState();await game.bulkEdit(f.creator,t.id,{revision:1,entities:s.entities},key());const auth=await login(f);let revision=2;
 const command=async(command:unknown)=>{const response=await f.app.inject({method:'POST',url:'/game/timelines/'+t.id+'/npc-behavior/command',headers:{cookie:auth.cookie,'x-csrf-token':auth.csrf,origin:f.settings.origin,'idempotency-key':key()},payload:{revision,command}});assert.equal(response.statusCode,200,response.body);revision=response.json().revision;return response.json();};
 await command({operation:'template',templateId:'clerk',version:'1',status:'published',profile:p,reason:'Approved version one'});await command({operation:'instantiate',templateId:'clerk',version:'1',actorId:npc.id,reason:'Pin first version'});await command({operation:'template',templateId:'clerk',version:'2',status:'published',profile:{...p,traits:{caution:800}},reason:'New version'});assert.equal(behaviorProfile(await game.load(t.id),npc.id)!.traits.caution,500);await command({operation:'instantiate',templateId:'clerk',version:'2',actorId:npc.id,reason:'Explicit migration'});assert.equal(behaviorProfile(await game.load(t.id),npc.id)!.traits.caution,800);
 const committed=await game.mutate(f.creator,t.id,revision,key(),{},'creator.npc-behavior',true,(state,eventId)=>{withTurnRuntime('repair-fixture',eventId,state,'spacetime',()=>advance(state,15,eventId,[],pc.id));return {result:{ok:true}};});revision=committed.revision;const before=await game.load(t.id),attempt=behaviorActor(before,npc.id).currentActionId!;assert.ok(attempt);await command({operation:'repair',actorId:npc.id,attemptId:attempt,reason:'Cancel obsolete unfinished task'});const after=await game.load(t.id);assert.equal(behaviorActor(after,npc.id).pendingDomain,null);assert.equal(after.npcBehavior!.leases.filter(l=>l.status==='ACTIVE').length,0);assert.equal(behaviorActor(after,npc.id).attempts.find(a=>a.id===attempt)!.status,'CANCELED');assert.deepEqual(after.entities,before.entities);assert.ok(after.npcBehavior!.interventions.some(i=>i.operation==='repair'&&i.reason.includes('obsolete')));
 }finally{await f.close();}
});

test('S05 T113 resource leases do not own items and idempotent release cannot change physical state',()=>{
 const {s,npc,item}=fixtureState(),before=behaviorHash(item);assert.equal(reserveBehaviorResources(s,npc.id,id('attempt'),[item.id,item.id],30,id('cause')),true);assert.equal(reserveBehaviorResources(s,npc.id,id('attempt'),[item.id],30,id('cause')),true);assert.equal(s.npcBehavior!.leases.length,1);releaseBehaviorLeases(s,id('attempt'));releaseBehaviorLeases(s,id('attempt'));assert.equal(behaviorHash(item),before);
});
test('S05 T114 reference population load reports measured context and queue behavior',()=>{
 const {s,npc,p}=fixtureState();for(let n=0;n<80;n++){const entity=validateEntity({...npc,id:id('population'+n),name:'Worker '+n,data:{...npc.data,plans:[]}});s.entities.push(entity);publishBehaviorProfile(s,{...p,actorId:entity.id,providerActions:[]},id('population-publish'+n));}s.clock='2012-06-01T12:15:00.000Z';const times:number[]=[];for(const a of s.npcBehavior!.actors){const began=performance.now();decideNpcBehavior(s,a.actorId,id('load'+a.actorId));times.push(performance.now()-began);}times.sort((a,b)=>a-b);console.log('SYSTEM05_REFERENCE_LOAD '+JSON.stringify({fixture:'s05-completion-v1',node:process.version,platform:process.platform,population:s.entities.filter(e=>e.kind==='character').length,managed:s.npcBehavior!.actors.length,decisions:times.length,p50:times[Math.floor(times.length*.5)],p95:times[Math.floor(times.length*.95)],plannerCalls:0,selected:s.npcBehavior!.decisions.filter(d=>d.result==='SELECTED').length,blocked:s.npcBehavior!.decisions.filter(d=>d.result==='BLOCKED').length,pendingWakes:s.npcBehavior!.actors.reduce((n,a)=>n+a.wakes.length,0)}));assert.equal(s.npcBehavior!.decisions.length,81);
});
