import {test} from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {actionSchema,data,settingsSchema,validateEntity,validateState} from '../src/game/model.ts';
import type {Entity,State} from '../src/game/model.ts';
import {resolveAction} from '../src/game/actions.ts';
import {observerView,project,visible} from '../src/game/epistemics.ts';
import {reviewMechanicalClaims} from '../src/game/context.ts';
import {fixture,key} from './helpers.ts';
import {Game} from '../src/game/engine.ts';

const eventId='24242424-2424-4242-8242-242424242424',seed='24'.repeat(32);
const make=(kind:Entity['kind'],name:string,raw:Record<string,unknown>={},visibility:Entity['visibility']='campaign')=>validateEntity({id:randomUUID(),kind,name,visibility,data:raw});
const rules={dieSides:6,threshold:50,damage:10,treatmentMinutes:10,recoveryPerDay:1,unfamiliarPenalty:0,bleedPerMinute:0,formula:'additive-no-die' as const,outcomeMode:'legacy-binary' as const,outcomeBands:{criticalMargin:10,successAtCostMargin:2,partialFailureMargin:-2,failureInformationMargin:-10}};
const tactics={movementMeters:5,failedChaseVehicleDamage:10,defenseDifficulty:{dodge:10,block:8,parry:12},grappleDifficulty:1,restraintDifficulty:1,disarmDifficulty:1,shoveDifficulty:1,escapeDifficulty:1000,actionPointsPerTurn:1,moraleBase:50,allyMorale:10,injuryMorale:30,surrenderThreshold:15,fleeThreshold:30,chaseTargetProgress:2,chaseProgressPerSuccess:1,chaseFootDifficulty:50,chaseVehicleDifficulty:50,noiseHeat:5};
const state=(entities:Entity[],extra:Record<string,unknown>={}):State=>({clock:'2012-06-01T12:00:00.000Z',settings:settingsSchema.parse({rules,tactics,...extra}),entities,facts:[],knowledge:[],beliefs:[],memories:[],eventIds:[]});
const act=(s:State,actorId:string,raw:unknown,id=eventId)=>resolveAction(s,actorId,actionSchema.parse(raw),id,seed);
const attributes=(Strength:number,Agility:number,Perception=Agility)=>({Strength,Agility,Endurance:50,Intellect:50,Perception,Presence:50,Will:50});

test('multi-actor tactical scenes preserve sides, initiative, authored perception, cover, ammo, and environment state',()=>{
 const near=randomUUID(),far=randomUUID(),barricade=randomUUID(),obstacle=randomUUID(),exit=make('location','Side street',{discoverable:true}),room=make('location','Loading bay',{exits:[{to:exit.id,minutes:1,modes:['walk']}],tacticalZones:[{id:near,name:'Near doors',position:0,cover:0,adjacentZoneIds:[far],exitDestinationId:exit.id},{id:far,name:'Far pallets',position:4,cover:25,adjacentZoneIds:[near]}],tacticalFeatures:[{id:barricade,name:'Concrete divider',kind:'cover',position:1,zoneId:near,cover:40,difficulty:1,actions:[]},{id:obstacle,name:'Rolling cart',description:'A creator-authored steel cart.',kind:'obstacle',position:2,zoneId:near,difficulty:1,damage:0,noise:60,actions:['obstruct']}]});
 const player=make('character','Player',{playable:true,locationId:room.id,attributes:attributes(100,100),goals:['survive']},'owner'),ally=make('character','Ally',{locationId:room.id,attributes:attributes(50,80),goals:['protect']}),enemyA=make('character','Opponent A',{locationId:room.id,attributes:attributes(20,20),goals:['survive']}),enemyB=make('character','Opponent B',{locationId:room.id,attributes:attributes(20,10),goals:['survive']}),witness=make('character','Witness',{locationId:room.id}),outsider=make('character','Outsider',{locationId:exit.id}),gun=make('item','One-round pistol',{category:'firearm',ownerId:player.id,possessorId:player.id,equipped:true,carryState:'held',magazine:1,loaded:1,condition:100,rangeMeters:20}),s=state([exit,room,player,ally,enemyA,enemyB,witness,outsider,gun],{weapons:{conditionLossPerShot:1}});
 const started=act(s,player.id,{type:'combat',targetId:enemyA.id,allyIds:[ally.id],opponentIds:[enemyB.id]});assert.ok(started.effects.some(effect=>effect.type==='combat.started'));const combat=s.entities.find(entity=>entity.kind==='combat')!,c=data(combat,'combat');assert.equal(c.combatSchemaVersion,2);assert.deepEqual(c.participants,[player.id,ally.id,enemyA.id,enemyB.id]);assert.deepEqual(c.turnOrder,[player.id,ally.id,enemyA.id,enemyB.id]);assert.equal(c.sides[player.id],c.sides[ally.id]);assert.equal(c.sides[player.id]===c.sides[enemyA.id],false);assert.equal(c.actorStates[enemyB.id]!.zoneId,far);assert.equal(c.actorStates[player.id]!.readiedWeaponId,gun.id);
 const looked=act(s,player.id,{type:'look'},randomUUID());assert.ok(looked.effects.some(effect=>effect.type==='tactical.look'&&effect.text.includes('Near doors')&&effect.text.includes('Rolling cart')));assert.doesNotMatch(looked.effects.map(effect=>effect.text).join(' '),/unseen balcony/i);
 act(s,player.id,{type:'cover',sourceId:barricade},randomUUID());assert.equal(data(combat,'combat').actorStates[player.id]!.cover,40);assert.equal(data(combat,'combat').actorStates[player.id]!.stance,'crouched');
 const shot=act(s,player.id,{type:'attack',targetId:enemyB.id,weaponId:gun.id,bodyPart:'torso'},randomUUID());assert.ok(shot.effects.some(effect=>effect.type==='weapon.shot'));assert.equal(data(gun,'item').loaded,0);assert.equal(data(gun,'item').condition,99);assert.ok(shot.checks.some(check=>check.difficulty>=rules.threshold+25));assert.ok(s.entities.some(entity=>entity.kind==='evidence'&&entity.data.objectId===gun.id));
 const environment=act(s,player.id,{type:'environmental-action',featureId:obstacle,targetId:enemyA.id,intent:'obstruct'},randomUUID());assert.ok(environment.effects.some(effect=>effect.type==='combat.environment'));assert.ok(data(combat,'combat').usedFeatureIds.includes(obstacle));assert.ok(data(combat,'combat').blockedLines.some(line=>line.fromId===player.id&&line.toId===enemyA.id));assert.ok(s.facts.some(entry=>entry.predicate==='combat-noise'));assert.ok((data(player,'character').heat.violence??0)>0);
 assert.equal(visible(s,combat,outsider.id),false);assert.ok(!observerView(s,outsider.id).entities.some(entity=>entity.id===combat.id));const witnessProjection=project(s,combat,witness.id),enemyProjection=(witnessProjection.data.actorStates as Record<string,Record<string,unknown>>)[enemyA.id]!;for(const hidden of ['goal','fear','morale','surrenderThreshold','fleeThreshold','visibleTargetIds','availableActions'])assert.equal(hidden in enemyProjection,false);validateState(s);
});

test('grappling and authored restraints require control and persist until a mechanical escape',()=>{
 const room=make('location','Hall'),player=make('character','Player',{playable:true,locationId:room.id,attributes:attributes(100,100)},'owner'),target=make('character','Target',{locationId:room.id,attributes:attributes(0,0),goals:['survive']}),cuffs=make('item','Handcuffs',{category:'tool',ownerId:player.id,possessorId:player.id,tags:['restraint']}),s=state([room,player,target,cuffs]);act(s,player.id,{type:'combat',targetId:target.id});
 act(s,player.id,{type:'grapple',targetId:target.id},randomUUID());let combat=data(s.entities.find(entity=>entity.kind==='combat')!,'combat');assert.equal(combat.actorStates[target.id]!.stance,'grappling');assert.equal(data(target,'character').restrainedBy,player.id);
 const restrained=act(s,player.id,{type:'restrain',targetId:target.id,itemId:cuffs.id},randomUUID());combat=data(s.entities.find(entity=>entity.kind==='combat')!,'combat');assert.ok(restrained.effects.some(effect=>effect.type==='combat.restrained'));assert.equal(combat.actorStates[target.id]!.stance,'restrained');assert.equal(combat.actorStates[target.id]!.restraintItemId,cuffs.id);assert.equal(data(target,'character').restrainedBy,player.id);validateState(s);
});

test('foot and vehicle chases use separate phases, route state, witnesses, risk, damage, evidence, and outcomes',()=>{
 const destination=make('location','Underpass',{discoverable:true}),origin=make('location','Avenue',{exits:[{to:destination.id,minutes:2,modes:['walk','drive'],terrainPenalty:0,trafficPenalty:0}]}),player=make('character','Pursuer',{playable:true,locationId:origin.id,attributes:attributes(50,100)},'owner'),quarry=make('character','Quarry',{locationId:origin.id,attributes:attributes(0,0),goals:['escape']}),witness=make('character','Witness',{locationId:origin.id}),s=state([destination,origin,player,quarry,witness]);
 act(s,player.id,{type:'chase',targetId:quarry.id,destinationId:destination.id,vehicleId:null});const chase=s.entities.find(entity=>entity.kind==='chase')!;assert.equal(data(chase,'chase').phase,'setup');act(s,player.id,{type:'chase-action',chaseId:chase.id,maneuver:'pursue'},randomUUID());assert.equal(data(chase,'chase').phase,'closing');const resolved=act(s,player.id,{type:'chase-action',chaseId:chase.id,maneuver:'intercept'},randomUUID());assert.equal(data(chase,'chase').status,'caught');assert.ok(resolved.effects.some(effect=>effect.type==='chase.caught'));assert.equal(data(player,'character').locationId,destination.id);assert.equal(data(quarry,'character').locationId,destination.id);assert.equal(data(chase,'chase').actorStates[quarry.id]!.caught,true);assert.ok(s.knowledge.some(row=>row.observerId===witness.id&&s.facts.some(fact=>fact.id===row.factId&&fact.predicate==='chase-resolved')));validateState(s);

 const road2=make('location','Exit ramp',{discoverable:true}),road1=make('location','Highway',{exits:[{to:road2.id,minutes:2,modes:['drive'],terrainPenalty:0,trafficPenalty:0}]}),driver=make('character','Driver',{playable:true,locationId:road1.id,attributes:attributes(50,0,0)},'owner'),other=make('character','Other driver',{locationId:road1.id,attributes:attributes(0,0,100)}),observer=make('character','Road witness',{locationId:road1.id}),car=make('vehicle','Pursuit car',{ownerId:driver.id,registeredOwnerId:driver.id,locationId:road1.id,locked:false,occupants:[driver.id],condition:100}),otherCar=make('vehicle','Quarry car',{ownerId:other.id,registeredOwnerId:other.id,locationId:road1.id,locked:false,occupants:[other.id]}),vehicleState=state([road2,road1,driver,other,observer,car,otherCar],{fuel:true});
 act(vehicleState,driver.id,{type:'chase',targetId:other.id,destinationId:road2.id,vehicleId:car.id});const vehicleChase=vehicleState.entities.find(entity=>entity.kind==='chase')!,failed=act(vehicleState,driver.id,{type:'chase-action',chaseId:vehicleChase.id,maneuver:'navigate'},randomUUID());assert.ok(failed.effects.some(effect=>effect.type==='chase.collision'));assert.equal(data(car,'vehicle').condition,90);assert.ok(data(car,'vehicle').damageRecords.some(record=>record.kind==='collision'));assert.ok(vehicleState.entities.some(entity=>entity.kind==='evidence'&&entity.data.objectId===car.id));assert.ok((data(driver,'character').heat.chase??0)>0);validateState(vehicleState);
});

test('narration cannot invent restraint, surrender, flight, pursuit outcomes, or collisions',()=>{
 const values=reviewMechanicalClaims('The suspect is handcuffed, surrenders, then the quarry is caught in the chase after a collision.',[]).map(flag=>flag.value);assert.deepEqual(values,['restraint','surrender','chase-caught','collision']);
 const effects=[{id:randomUUID(),text:'Recorded.',observers:[],type:'combat.grappled',subjectId:randomUUID()}];assert.deepEqual(reviewMechanicalClaims('They grapple.',effects),[]);assert.equal(reviewMechanicalClaims('The guard fled.',[])[0]?.value,'combat-flee');
});

test('chase action retries do not reroll or duplicate history and pursuit state survives branching',async()=>{
 const f=await fixture(),game=new Game(f.store);try{
  const timeline=await game.initialize(f.creator,f.campaign.id),destination=make('location','Destination',{discoverable:true}),origin=make('location','Origin',{exits:[{to:destination.id,minutes:2,modes:['walk']}]}),player=make('character','Player',{playable:true,controllerUserId:f.player.id,locationId:origin.id,attributes:{Strength:0,Agility:100,Endurance:0,Intellect:0,Perception:0,Presence:0,Will:0}},'owner'),target=make('character','Target',{locationId:origin.id,attributes:{Strength:0,Agility:0,Endurance:0,Intellect:0,Perception:0,Presence:0,Will:0}});
  await game.bulkEdit(f.creator,timeline.id,{revision:1,entities:[destination,origin,player,target]},key());let revision=(await game.access(f.creator,timeline.id)).t.revision,current=await game.load(timeline.id);await game.configure(f.creator,timeline.id,revision,settingsSchema.parse({...current.settings,rules,tactics:{...tactics,chaseTargetProgress:5}}),key());revision=(await game.access(f.player,timeline.id)).t.revision;
  await game.turn(f.player,timeline.id,{revision,characterId:player.id,action:actionSchema.parse({type:'chase',targetId:target.id,destinationId:destination.id,vehicleId:null})},key());current=await game.load(timeline.id);const chase=current.entities.find(entity=>entity.kind==='chase')!;revision=(await game.access(f.player,timeline.id)).t.revision;const retryKey=key(),request={revision,characterId:player.id,action:actionSchema.parse({type:'chase-action',chaseId:chase.id,maneuver:'pursue' as const})},first=await game.turn(f.player,timeline.id,request,retryKey),retry=await game.turn(f.player,timeline.id,request,retryKey);assert.equal(retry.eventId,first.eventId);
  current=await game.load(timeline.id);const persisted=data(current.entities.find(entity=>entity.id===chase.id)!,'chase');assert.equal(persisted.history.filter(row=>row.eventId===first.eventId).length,2);const save=await game.save(f.player,timeline.id,'Pursuit state'),branch=await game.branch(f.player,timeline.id,save.id,'Pursuit branch'),branched=await game.load(branch.id),restored=data(branched.entities.find(entity=>entity.id===chase.id)!,'chase');assert.deepEqual(restored.history,persisted.history);assert.equal(restored.phase,persisted.phase);assert.equal(restored.status,persisted.status);validateState(branched);
 }finally{await f.close();}
});
