import {test} from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID as uuid} from 'node:crypto';
import {buildNarrativeBundle,deterministicNarrative,deterministicDraft,narrativeChoices,validateNarrativeDraft,presentFact,suppressionManifest} from '../src/game/narrative-runtime.ts';
import {narrativeProfileSchema,narrativePresets,communicationProfileSchema,voiceProfileSchema} from '../src/game/narrative-profile.ts';
import {communicate,phraseCommunication,conversationState} from '../src/game/communication.ts';
import {observerView,fact} from '../src/game/epistemics.ts';
import {observerEffects} from '../src/game/turn-visibility.ts';
import {settingsSchema,validateEntity,data,type State,type Entity} from '../src/game/model.ts';
import {advance,type Effect} from '../src/game/simulation.ts';
import {fixture,key,login} from './helpers.ts';
import {Game,checksum} from '../src/game/engine.ts';
import {TurnKernel} from '../src/game/turn-kernel.ts';
import {NarrativePreferences} from '../src/game/narrative-preferences.ts';
import {NarrativeGateway,GroundedProvider,type NarrativeProvider} from '../src/game/ai.ts';
const make=(kind:Entity['kind'],name:string,value:Record<string,unknown>={},visibility:Entity['visibility']='campaign')=>validateEntity({id:uuid(),kind,name,visibility,data:value});
function scene(){const room=make('location','Diner',{description:'The counter was scuffed.',narrative:{details:[{id:'light',text:'Yellow light filled the room.',sense:'visual',layer:'immediate'},{id:'heat',text:'The room was warm.',sense:'temperature',layer:'current'},{id:'secret',text:'The killer hid a gun beneath the floor.',visibility:'creator'}]}}),pc=make('character','Alex',{playable:true,locationId:room.id}),npc=make('character','Malik',{locationId:room.id}),s:State={clock:'2012-06-01T12:00:00.000Z',settings:settingsSchema.parse({needs:false}),entities:[room,pc,npc],facts:[],knowledge:[],beliefs:[],memories:[],eventIds:[]};return {room,pc,npc,s};}
function bundle(f=scene(),patch:Record<string,unknown>={},effects:Effect[]=[],extra:Partial<Parameters<typeof buildNarrativeBundle>[0]>={}){return buildNarrativeBundle({state:f.s,before:structuredClone(f.s),actorId:f.pc.id,turnId:uuid(),effects:observerEffects(f.s,effects,f.pc.id),profile:narrativeProfileSchema.parse(patch),layers:[],mode:'GAME',control:{holder:'PLAYER'},playerText:'',recent:[],...extra});}
const effect=(f:ReturnType<typeof scene>,text:string,type='resolved.action',subjectId=f.pc.id):Effect=>({id:uuid(),text,type,subjectId,observers:[f.pc.id]});
function rejectText(b:ReturnType<typeof bundle>,text:string){const draft=deterministicDraft(b);draft.paragraphs[0]!.text+=' '+text;assert.throws(()=>validateNarrativeDraft(draft,b),/narrative_unsupported_claim/);}

test('S02-01/02/15: default third past and first present remain stable; wrong perspective is repaired',()=>{const f=scene(),b=bundle(f,{},[effect(f,'Alex waits.')]);assert.match(deterministicNarrative(b),/Alex waited/);const first=bundle(f,{perspective:'first',tense:'present'},[effect(f,'Alex waited.')]);assert.match(deterministicNarrative(first),/I am at Diner/);assert.match(deterministicNarrative(first),/I wait\./);const draft=deterministicDraft(first);draft.paragraphs[0]!.text=draft.paragraphs[0]!.sourceIds.map(id=>first.facts.find(f=>f.id===id)!.text).join(' ');assert.ok(validateNarrativeDraft(draft,first).repairs.some(r=>r.kind==='pov-tense'));assert.equal(presentFact('Alex was here.',narrativeProfileSchema.parse({perspective:'first'}),'Alex'),'I was here.');});
test('S02-03/04: rich adds authored texture; sparse preserves actionable facts; private location pools stay hidden',()=>{const f=scene(),effects=[effect(f,'The only exit was locked.')],rich=bundle(f,{descriptionDensity:'rich',responseLength:'long'},effects),sparse=bundle(f,{descriptionDensity:'sparse'},effects),before=checksum(f.s);assert.match(deterministicNarrative(rich),/Yellow light/);assert.doesNotMatch(deterministicNarrative(sparse),/Yellow light|scuffed/);assert.match(deterministicNarrative(sparse),/only exit was locked/);assert.equal(checksum(f.s),before);assert.doesNotMatch(JSON.stringify(observerView(f.s,f.pc.id)),/killer hid/);rejectText(rich,'A usable safe stood beside the counter.');});
test('S02-05/06/45/46/47: exact speech, nonverbal methods, comprehension and public utterance knowledge',()=>{const f=scene(),effects:Effect[]=[],words='I said NO—do not change that.';communicate(f.s,f.pc.id,{method:'say',language:'en',targetId:null,text:words},uuid(),effects);assert.ok(deterministicNarrative(bundle(f,{},effects)).includes(words));assert.doesNotMatch(JSON.stringify(observerEffects(f.s,effects,f.pc.id)),/"register":|"requiresResponse":|"targetId":/);assert.ok(f.s.knowledge.some(k=>k.observerId===f.npc.id));const record=f.s.facts.at(-1)!;assert.equal(record.truthStatus,'asserted');assert.equal(record.predicate,'communicated');
 f.pc.data.communication=communicationProfileSchema.parse({canSpeak:false,normalMethod:'sign',language:'asl',languages:{asl:{signed:100}}});const signed:Effect[]=[];communicate(f.s,f.pc.id,{method:'sign',language:'asl',targetId:f.npc.id,text:'Meet at noon.'},uuid(),signed);assert.match(signed.find(e=>e.observers.includes(f.npc.id))!.text,/not understood/);assert.equal(signed.find(e=>e.observers.includes(f.npc.id))!.dialogue!.text,'');assert.match(deterministicNarrative(bundle(f,{},signed)),/signed, \*Meet at noon\.\*/);assert.throws(()=>communicate(f.s,f.pc.id,{method:'say',language:'asl',targetId:null,text:'no'},uuid(),[]),/speech_unavailable/);
 f.npc.data.communication=communicationProfileSchema.parse({languages:{asl:{signed:100},fr:{spoken:100}}});const understood:Effect[]=[];communicate(f.s,f.pc.id,{method:'sign',language:'asl',targetId:f.npc.id,text:'The key is under my mat.'},uuid(),understood);assert.ok(understood.find(e=>e.observers.includes(f.npc.id))!.text.includes('under my mat'));
 const foreign:Effect[]=[];communicate(f.s,f.npc.id,{method:'say',language:'fr',targetId:f.pc.id,text:'Un secret'},uuid(),foreign);assert.doesNotMatch(JSON.stringify(observerEffects(f.s,foreign,f.pc.id)),/Un secret/);
 f.pc.data.communication=communicationProfileSchema.parse({normalMethod:'write',canSpeak:false});const written:Effect[]=[];communicate(f.s,f.pc.id,{method:'write',language:'en',targetId:f.npc.id,text:'Wait here.'},uuid(),written);assert.match(deterministicNarrative(bundle(f,{},written)),/wrote, “Wait here\.”/);
});
test('S02-07: Auto-Phrase has bounded intents and never commits speech',()=>{const f=scene(),before=checksum(f.s);assert.equal(phraseCommunication('greet'),'Hello.');assert.equal(phraseCommunication('decline'),'No, thank you.');assert.equal(phraseCommunication('ask-location','Malik'),'Where is Malik?');assert.equal(phraseCommunication('ask-status','Malik'),'How is Malik?');assert.equal(checksum(f.s),before);});
test('S02-08/09/11/12/35: thoughts, hidden attraction, lies, unidentified stains and mistaken theories are not omniscient facts',()=>{const f=scene();f.s.entities.push(make('relationship','Hidden attraction',{fromId:f.npc.id,toId:f.pc.id,attraction:90,secret:true},'creator'));const b=bundle(f,{},[effect(f,'A dark stain marked the floor.')],{playerText:'I think Malik is guilty. I secretly forgive him.'});const text=deterministicNarrative(b);assert.doesNotMatch(text,/guilty|forgive|attraction|blood/);for(const invalid of ['Malik secretly wanted Alex.','Malik was lying.','The stain was blood.','Alex was wrong: Malik was innocent.'])rejectText(b,invalid);});
test('S02-10: NPC speech plans require speaker knowledge and living speakers',()=>{const f=scene(),secret=fact(f.s,f.room.id,'hidden-clue','safe code',uuid(),[f.pc.id]);f.npc.data.plans=[...data(make('character','Plan',{plans:[{id:uuid(),type:'speak',targetId:f.pc.id,text:'The code is 4281.',speechFactIds:[secret],cooldownMinutes:15}]}),'character').plans];const effects:Effect[]=[];advance(f.s,15,uuid(),effects,f.pc.id);assert.equal(effects.filter(e=>e.type==='npc.dialogue').length,0);const known=f.s.facts.find(f=>f.id===secret)!;f.s.knowledge.push({observerId:f.npc.id,factId:known.id,at:f.s.clock,source:'observed'});advance(f.s,15,uuid(),effects,f.pc.id);assert.ok(effects.some(e=>e.type==='npc.dialogue'));f.npc.data.condition='dead';const later:Effect[]=[];advance(f.s,30,uuid(),later,f.pc.id);assert.equal(later.filter(e=>e.type==='npc.dialogue').length,0);});
test('S02-13/14: familiar locations omit established texture and retain persistent damage',()=>{const f=scene(),door=make('item','Door',{locationId:f.room.id,condition:35,mechanism:{kind:'door',open:false}});f.s.entities.push(door);const first=bundle(f),later=bundle(f,{},[],{previousLocationFingerprint:first.locationFingerprint});assert.doesNotMatch(deterministicNarrative(later),/scuffed|Yellow/);assert.match(deterministicNarrative(later),/Door remained damaged/);const rich=data(f.room,'location').narrative!;rich.details.find(d=>d.id==='secret')!.text='A different hidden secret.';f.room.data.narrative=rich;assert.equal(bundle(f).locationFingerprint,first.locationFingerprint);});
for(const [id,claim] of [[16,'Alex forgave Malik.'],[17,'The missed shot hit Malik.'],[23,'Alex felt glad to be here.'],[26,'Malik fell in love with Alex.'],[28,'Alex kissed Malik back.'],[31,'Alex dreamed of the killer.'],[34,'An unseen gunman waited outside.'],[39,'Alex used ChatGPT on an iPhone 16.'],[48,'Across town, the killer destroyed the evidence.'],[49,'A newly invented clue revealed the culprit.'],[50,'The decorative shadow became forensic evidence.']] as const)test('S02-'+String(id).padStart(2,'0')+': rejects unsupported claim: '+claim,()=>{const f=scene(),b=bundle(f,{pacing:'slow',responseLength:'very-long',humorLevel:'high',toneBounds:['High romance emphasis']},[effect(f,'The shot missed. Malik moved behind the counter.')]),before=checksum(f.s);rejectText(b,claim);assert.equal(checksum(f.s),before);});
test('S02-18: concealed NPC identity never enters observer prose or dialogue metadata',()=>{const f=scene();f.npc.data.identityDisclosure={concealed:true,knownByIds:[],label:'The stranger'};const effects:Effect[]=[];communicate(f.s,f.npc.id,{method:'say',language:'en',targetId:f.pc.id,text:'Hello.'},uuid(),effects);const b=bundle(f,{},effects);assert.doesNotMatch(JSON.stringify(b.facts),/Malik/);assert.match(deterministicNarrative(b),/stranger/);});
test('S02-19/20: crowd focus follows resolved speakers and NPC initiative is bounded',()=>{const f=scene();f.s.settings.npcInitiativeBudget=1;for(let i=0;i<8;i++)f.s.entities.push(make('character','Bystander '+i,{locationId:f.room.id,plans:[{id:uuid(),type:'speak',targetId:f.npc.id,text:'Hello.',cooldownMinutes:15}]}));const effects:Effect[]=[];advance(f.s,15,uuid(),effects,f.pc.id);const b=bundle(f,{},effects),speech=b.facts.filter(f=>f.source==='event:npc.dialogue');assert.equal(speech.length,1);assert.equal(b.focus.filter(f=>f.role==='primary').length,1);assert.equal(b.control instanceof Object,true);});
test('S02-21/22/27: very long and fast prose preserve handoff, clock, combat count and positions',()=>{const f=scene();f.s.entities.push(make('combat','Encounter',{active:true,participants:[f.pc.id,f.npc.id],positions:{[f.pc.id]:0,[f.npc.id]:3}}));const b=bundle(f,{responseLength:'very-long',pacing:'fast'},[effect(f,'Malik drew his weapon.','weapon.drawn',f.npc.id),effect(f,'Alex fired once and missed.')],{control:{holder:'PLAYER',reasonCode:'REACTION_WINDOW'}}),before=checksum(f.s),draft=deterministicDraft(b);assert.match(deterministicNarrative(b),/held position/);assert.match(deterministicNarrative(b),/fired once/);assert.equal(validateNarrativeDraft(draft,b).text,deterministicNarrative(b));rejectText(b,'Malik fired before Alex could react.');const duplicate=structuredClone(draft);duplicate.paragraphs.push(draft.paragraphs[0]!);assert.throws(()=>validateNarrativeDraft(duplicate,b),/duplicate/);assert.equal(checksum(f.s),before);});
test('S02-24/25/51/52: terse humorless voice wins; threats are exact; casual equivalents preserve meaning',()=>{const f=scene();f.npc.data.voiceProfile=voiceProfileSchema.parse({sentenceLength:'terse',humor:'none',equivalents:[{canonical:'Hello.',alternatives:['Hi.','Hello, beautiful.']}]});const effects:Effect[]=[];communicate(f.s,f.npc.id,{method:'say',language:'en',targetId:f.pc.id,text:'Hello.'},uuid(),effects,false);const b=bundle(f,{dialogueDensity:'high',humorLevel:'high'},effects),choices=narrativeChoices(b),line=choices.find(c=>c.speakerId===f.npc.id)!;assert.ok(line.variants.some(t=>t.includes('Hi.')));assert.ok(!line.variants.some(t=>t.includes('beautiful')));const draft=deterministicDraft(b),paragraph=draft.paragraphs.find(p=>p.sourceIds.includes(line.id))!;paragraph.text=line.variants.find(t=>t.includes('Hi.'))!;assert.match(validateNarrativeDraft(draft,b).text,/Hi\./);rejectText(b,'Malik told a witty joke.');const threat:Effect[]=[];communicate(f.s,f.npc.id,{method:'say',language:'en',targetId:f.pc.id,text:'Move and I will shoot.'},uuid(),threat,true);const canonical=bundle(f,{},threat);assert.ok(deterministicNarrative(canonical).includes('Move and I will shoot.'));rejectText(canonical,'It was only a joke.');});
test('S02-30/32/33: summaries preserve travel facts, avoid lore dumps and retain rumor attribution',()=>{const f=scene();f.s.entities.push(make('lore','Unrelated history',{description:'A long irrelevant history of the city.'}));const b=bundle(f,{},[effect(f,'Alex traveled with Malik for 12 minutes.'),effect(f,'Malik reported a rumor that the store was closed.')]);const text=deterministicNarrative(b);assert.match(text,/with Malik for 12 minutes/);assert.match(text,/reported a rumor/);assert.doesNotMatch(text,/irrelevant history/);rejectText(b,'The store was definitely closed.');});
test('S02-36/37/38: semantic repetition damping, motif cooldowns and stable straightforward defaults',()=>{const f=scene();(f.room.data.narrative as {details:unknown[]}).details.push({id:'jaw',text:'His jaw tightened.',sense:'visual',layer:'current',visibility:'public'});const p=narrativeProfileSchema.parse({motifs:[{phrase:'Yellow light',cooldownTurns:2}]});assert.ok(suppressionManifest(['His jaw clenched. Yellow light.'],p).categories.includes('jaw'));const b=bundle(f,{descriptionDensity:'rich',motifs:p.motifs},[],{recent:[{narration:'His jaw clenched. Yellow light.'}]});assert.doesNotMatch(deterministicNarrative(b),/jaw tightened|Yellow light/);const refreshed=bundle(f,{descriptionDensity:'rich',motifs:p.motifs},[],{recent:[{narration:'Yellow light.'},{narration:'One.'},{narration:'Two.'}]});assert.match(deterministicNarrative(refreshed),/Yellow light/);for(let i=0;i<50;i++){const simple=bundle(f,narrativePresets.straightforward);assert.doesNotMatch(deterministicNarrative(simple),/Yellow|scuffed|jaw/);assert.equal(simple.profile.literaryIntensity,'straightforward');}});

async function setup(){const f=await fixture(),game=new Game(f.store),t=await game.initialize(f.creator,f.campaign.id),world=scene();world.pc.visibility='owner';world.pc.data.controllerUserId=f.player.id;await game.bulkEdit(f.creator,t.id,{revision:1,entities:world.s.entities},key());const kernel=new TurnKernel(game);const command=async(input:Parameters<typeof kernel.execute>[1],mode:'GAME'|'STORY'='GAME')=>kernel.execute(f.player,{commandId:key(),sessionId:t.id,expectedRevision:(await game.access(f.player,t.id)).t.revision,actorId:world.pc.id,mode,input});return {...f,game,t,kernel,...world,command};}
test('S02-40/41/42/43/44: frozen profiles, bounded repair/retry, outages, regeneration and persistent complex input',async()=>{const f=await setup();try{const settings=(await f.game.load(f.t.id)).settings;settings.tokenBudget=100000;settings.userTokenBudget=100000;await f.game.configure(f.creator,f.t.id,2,settings,key());const prefs=new NarrativePreferences(f.game);await prefs.save(f.player,f.t.id,{characterId:f.pc.id,mode:'GAME',scope:'user',expectedRevision:0,patch:{perspective:'first',tense:'present'}});const turn=await f.command({kind:'action',action:{type:'wait',minutes:1}}),before=checksum(await f.game.load(f.t.id)),original=(await f.game.view(f.player,f.t.id,f.pc.id)).turns.at(-1)!.narration;assert.match(original,/I am/);await prefs.save(f.player,f.t.id,{characterId:f.pc.id,mode:'GAME',scope:'character',expectedRevision:0,patch:{perspective:'second',tense:'past'}});assert.equal((await f.game.view(f.player,f.t.id,f.pc.id)).turns.at(-1)!.narration,original);
 let attempts=0;const provider:NarrativeProvider={id:'broken',arrange:async context=>{attempts++;return {paragraphs:context.fragments.map(x=>({sourceIds:[x.id],text:x.text+' Alex forgave everyone.'}))};}},gateway=new NarrativeGateway(f.game,[provider,new GroundedProvider()]);const failed=await gateway.narrate(f.player,f.t.id,turn.eventId,'broken',undefined,'story');assert.equal(failed.status,'grounded-fallback');assert.equal(attempts,2);assert.equal(checksum(await f.game.load(f.t.id)),before);assert.equal(failed.narration,original);const regenerated=await gateway.narrate(f.player,f.t.id,turn.eventId);assert.match(regenerated.narration,/I am/);assert.equal(checksum(await f.game.load(f.t.id)),before);
 const next=await f.command({kind:'action',action:{type:'look'}});assert.equal(next.status,'COMMITTED');assert.match((await f.game.view(f.player,f.t.id,f.pc.id)).turns.at(-1)!.narration,/You were/);const previous=checksum(await f.game.load(f.t.id)),complex='I privately suspect Malik, but if he apologizes I might follow whoever sent the letter.';const pending=await f.command({kind:'freeform',text:complex},'STORY');assert.equal(pending.status,'NEEDS_CLARIFICATION');assert.equal(pending.pendingDecision.originalText,complex);assert.equal(checksum(await f.game.load(f.t.id)),previous);
 const records=await f.store.all<{record_json:string}>('SELECT record_json FROM narrative_render_records WHERE event_id=?',turn.eventId);assert.ok(records.map(r=>JSON.parse(r.record_json)).some(r=>r.status==='fallback'&&r.retryCount===1));assert.ok(records.every(r=>JSON.parse(r.record_json).mechanicsChanged===false));const canceled=new AbortController();canceled.abort();await assert.rejects(()=>gateway.narrate(f.player,f.t.id,turn.eventId,'broken',canceled.signal),/canceled/);assert.equal(checksum(await f.game.load(f.t.id)),previous);
 }finally{await f.close();}});
test('S02-29: work compression stops at the authored event before narrative length is considered',async()=>{const f=await setup();try{const state=await f.game.load(f.t.id),due=new Date(Date.parse(state.clock)+30*60000).toISOString(),business=make('business','Employer',{locationId:f.room.id,cash:100000}),job=make('job','Shift',{employeeId:f.pc.id,employerId:business.id,locationId:f.room.id,hourlyCents:1200,minutesPerShift:480}),watcher=make('watcher','Decision',{trigger:'time',dueAt:due,effect:'notify',requiresPlayerResponse:true,notifyCharacterIds:[f.pc.id],description:'A visitor drew a weapon.'},'creator');await f.game.bulkEdit(f.creator,f.t.id,{revision:2,entities:[business,job,watcher]},key());const result=await f.command({kind:'action',action:{type:'work',jobId:job.id}});assert.equal(result.worldTime,due);assert.equal(result.interrupted,true);assert.equal(result.control.holder,'PLAYER');assert.match((await f.game.view(f.player,f.t.id,f.pc.id)).turns.at(-1)!.narration,/visitor drew/);}finally{await f.close();}});
test('S02 profiles: independent modes, hierarchy, CAS, authorization, HTTP settings and hidden diagnostics',async()=>{const f=await setup();try{const p=new NarrativePreferences(f.game);await p.save(f.player,f.t.id,{characterId:f.pc.id,mode:'GAME',scope:'user',expectedRevision:0,patch:{perspective:'first'}});assert.equal((await p.read(f.player,f.t.id,f.pc.id,'STORY')).profile.perspective,'third');assert.equal((await p.read(f.player,f.t.id,f.pc.id,'GAME')).profile.perspective,'first');await assert.rejects(()=>p.save(f.player,f.t.id,{characterId:f.pc.id,mode:'GAME',scope:'user',expectedRevision:0,patch:{}}),/conflict/);await assert.rejects(()=>p.save(f.player,f.t.id,{characterId:f.pc.id,mode:'GAME',scope:'campaign',expectedRevision:0,patch:{}}));await assert.rejects(()=>p.read(f.observer,f.t.id,f.pc.id,'GAME'));const turn=await f.command({kind:'action',action:{type:'look'}});await p.save(f.player,f.t.id,{characterId:f.pc.id,mode:'GAME',scope:'scene',expectedRevision:0,patch:{tense:'present'}});const effective=(await p.read(f.player,f.t.id,f.pc.id,'GAME')).profile;assert.equal(effective.tense,'present');assert.equal(effective.perspective,'first');assert.equal(effective.mechanicalFeedbackStyle,'standard');const auth=await login(f,'player@example.test'),headers={cookie:auth.cookie,origin:f.settings.origin,'x-csrf-token':auth.csrf};const read=await f.app.inject({url:'/game/timelines/'+f.t.id+'/narrative/preferences?characterId='+f.pc.id+'&mode=GAME',headers});assert.equal(read.statusCode,200);const diagnostics=await f.app.inject({url:'/game/timelines/'+f.t.id+'/narrative/diagnostics/'+turn.eventId,headers});assert.equal(diagnostics.statusCode,403);assert.doesNotMatch(JSON.stringify(await f.game.view(f.player,f.t.id,f.pc.id)),/profileLayers|voiceProfile|suppression|killer hid/);await assert.rejects(()=>f.store.run('UPDATE narrative_render_records SET record_json=?','{}'),/immutable/);}finally{await f.close();}});

test('S02 conversation continuity: repeated questions use an authored response and a speech handoff bounds time',async()=>{const f=await setup();try{const npc=structuredClone(f.npc);npc.data.plans=[{id:key(),type:'speak',targetId:f.pc.id,text:'At the diner.',repeatedQuestionText:'As I said, at the diner.',answerToLatestQuestion:true,cooldownMinutes:15,speechRequiresResponse:true}];await f.game.edit(f.creator,f.t.id,{revision:2,entity:npc},key());const before=(await f.game.load(f.t.id)).clock;const turn=await f.command({kind:'action',action:{type:'wait',minutes:480}});assert.equal(Date.parse(turn.worldTime)-Date.parse(before),15*60000);assert.equal(turn.interrupted,true);const s=await f.game.load(f.t.id);for(let i=0;i<2;i++)communicate(s,f.pc.id,{method:'say',language:'en',targetId:f.npc.id,text:'Where is Malik?'},uuid(),[]);assert.equal(conversationState(s,f.npc.id,f.pc.id).repeatCount,2);const effects:Effect[]=[];advance(s,15,uuid(),effects,f.pc.id);assert.ok(effects.some(e=>e.dialogue?.text==='As I said, at the diner.'));assert.equal(conversationState(s,f.npc.id,f.pc.id).unresolvedQuestions.length,0);assert.equal(conversationState(s,f.pc.id).previousAnswers.at(-1)?.text,'As I said, at the diner.');}finally{await f.close();}});
test('S02 retry sends repair instructions with the identical facts; mixed paragraphs cannot bypass optional filters',async()=>{const f=await setup();try{const settings=(await f.game.load(f.t.id)).settings;settings.tokenBudget=100000;settings.userTokenBudget=100000;await f.game.configure(f.creator,f.t.id,2,settings,key());const turn=await f.command({kind:'action',action:{type:'look'}}),before=checksum(await f.game.load(f.t.id));let calls=0,firstIds:string[]=[];const provider:NarrativeProvider={id:'repair',complete:async request=>{calls++;const fragments=request.context.provenance.filter(p=>p.id!=='original-story-input'&&p.id!=='narrative-guidance').map(p=>p.content as {id:string;text:string});if(calls===1)firstIds=fragments.map(f=>f.id);else{assert.deepEqual(fragments.map(f=>f.id),firstIds);assert.match(request.prompt.instructions,/Repair the previous validation failure/);}return {traceId:request.traceId,usage:{inputTokens:100,outputTokens:100},toolCalls:[],output:{paragraphs:fragments.map(f=>({sourceIds:[f.id],text:f.text+(calls===1?' Alex used ChatGPT on an iPhone 16.':'' )}))}};}};const result=await new NarrativeGateway(f.game,[provider]).narrate(f.player,f.t.id,turn.eventId,'repair');assert.equal(result.status,'validated');assert.equal(calls,2);assert.equal(checksum(await f.game.load(f.t.id)),before);const b=bundle(scene(),{descriptionDensity:'sparse'}),choices=narrativeChoices(b),draft={paragraphs:[{sourceIds:choices.map(c=>c.id),text:choices.map(c=>c.variants[0]).join(' ')}]};assert.doesNotMatch(validateNarrativeDraft(draft,b).text,/Yellow|scuffed/);}finally{await f.close();}});
test('S02 grammar keeps literal multiline speech, physical adjectives and modal intentions intact',()=>{const past=narrativeProfileSchema.parse({}),present=narrativeProfileSchema.parse({perspective:'first',tense:'present'});assert.equal(presentFact('The door is open.',past,'Alex'),'The door was open.');assert.equal(presentFact('The door was closed.',present,'Alex'),'The door is closed.');assert.equal(presentFact('Alex wants to open the door.',past,'Alex'),'Alex wanted to open the door.');assert.equal(presentFact('Alex said, “I will open it.\nI am sure.”',present,'Alex',true),'I say, “I will open it.\nI am sure.”');});
