import {test} from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {actionSchema,data,settingsSchema,validateEntity,validateState} from '../src/game/model.ts';
import type {Entity,State} from '../src/game/model.ts';
import {resolveAction} from '../src/game/actions.ts';
import {observerView} from '../src/game/epistemics.ts';
import {heatValue,noticeHeatSignal,raiseHeat} from '../src/game/investigation.ts';

const seed='28'.repeat(32),eventId='28282828-2828-4282-8282-282828282828';
const make=(kind:Entity['kind'],name:string,raw:Record<string,unknown>={},visibility:Entity['visibility']='campaign')=>validateEntity({id:randomUUID(),kind,name,visibility,data:raw});
const state=(entities:Entity[]):State=>({clock:'2012-06-01T12:00:00.000Z',settings:settingsSchema.parse({timezone:'America/New_York'}),entities,facts:[],knowledge:[],beliefs:[],memories:[],eventIds:[]});
const act=(s:State,actorId:string,raw:unknown)=>resolveAction(s,actorId,actionSchema.parse(raw),eventId,seed);

test('evidence transfer preserves source and condition while custody and audience knowledge change explicitly',()=>{
 const room=make('location','Evidence room'),detective=make('character','Detective',{playable:true,locationId:room.id},'owner'),technician=make('character','Technician',{locationId:room.id}),outsider=make('character','Outsider',{locationId:room.id}),agency=make('faction','Police',{memberIds:[detective.id,technician.id],jurisdictionIds:[room.id]}),file=make('case','Burglary file',{agencyId:agency.id,investigatorId:detective.id}),sample=make('evidence','Window fingerprint',{medium:'trace',evidenceType:'fingerprint',locationId:room.id,sourceLocationId:room.id,sourceAt:'2012-06-01T11:30:00.000Z',personIds:[],caseId:file.id,discoveredBy:[detective.id],condition:'partial',strength:60});
 const s=state([room,detective,technician,outsider,agency,file,sample]);act(s,detective.id,{type:'collect',evidenceId:sample.id,caseId:file.id});act(s,detective.id,{type:'custody',evidenceId:sample.id,toId:technician.id,reason:'sealed laboratory handoff',sealed:true});
 const evidence=data(sample,'evidence');assert.equal(evidence.sourceLocationId,room.id);assert.equal(evidence.sourceAt,'2012-06-01T11:30:00.000Z');assert.equal(evidence.condition,'partial');assert.equal(evidence.collectorId,detective.id);assert.equal(evidence.custodianId,technician.id);assert.equal(evidence.custody.length,2);assert.equal(evidence.custody[1]!.sealed,true);assert.deepEqual(evidence.custody.map(row=>row.condition),['partial','partial']);assert.ok(data(file,'case').evidenceScore>0);
 assert.equal(observerView(s,technician.id).entities.some(entity=>entity.id===sample.id),true);assert.equal(observerView(s,outsider.id).entities.some(entity=>entity.id===sample.id),false);validateState(s);
});

test('a paid false informant tip becomes an unverified police hypothesis without becoming world truth',()=>{
 const room=make('location','Cafe'),handler=make('character','Handler',{playable:true,locationId:room.id},'owner'),source=make('character','Source',{locationId:room.id}),suspect=make('character','Named suspect',{locationId:room.id}),agency=make('faction','Police',{memberIds:[handler.id],jurisdictionIds:[room.id],treasuryCents:5000}),file=make('case','Tip file',{agencyId:agency.id,investigatorId:handler.id}),tipId=randomUUID(),informant=make('informant','Cafe source',{characterId:source.id,handlerId:handler.id,agencyId:agency.id,motives:['money','revenge'],reliability:35,exposureRisk:70,knowledge:{personIds:[suspect.id],locationIds:[room.id],factionIds:[],topics:['street-theft'],boundaries:['no police interiors']},terms:{paymentCents:500,favorTerm:'',paidCents:0,favorAccepted:false,status:'open'},tips:[{id:tipId,proposition:'The named suspect fenced the stolen watch.',subjectId:suspect.id,caseId:file.id,reliability:30,creatorTruth:'inaccurate',paymentCents:500}]}),s=state([room,handler,source,suspect,agency,file,informant]);
 const before=Date.parse(s.clock);act(s,handler.id,{type:'consult-informant',informantId:informant.id,caseId:file.id,tipId});
 assert.equal(Date.parse(s.clock)-before,15*60000);assert.equal(data(agency,'faction').treasuryCents,4500);assert.equal(data(informant,'informant').tips[0]!.status,'disclosed');assert.equal(data(file,'case').hypotheses[0]!.status,'active');assert.equal(data(file,'case').leadRecords[0]!.kind,'tip');assert.equal(s.facts.length,0);assert.equal(s.beliefs.at(-1)?.truthStatus,'believed');
 const playerInformant=observerView(s,handler.id).entities.find(entity=>entity.id===informant.id);assert.ok(playerInformant);assert.equal(JSON.stringify(playerInformant).includes('inaccurate'),false);validateState(s);
});

test('contamination is persistent and degrades a timed, resource-backed lead into ambiguity',()=>{
 const lab=make('location','Laboratory'),detective=make('character','Detective',{playable:true,locationId:lab.id},'owner'),suspect=make('character','Suspect',{locationId:lab.id}),agency=make('faction','Police',{memberIds:[detective.id],jurisdictionIds:[lab.id],treasuryCents:2000}),file=make('case','DNA file',{agencyId:agency.id,investigatorId:detective.id}),optionId=randomUUID(),sample=make('evidence','Blood swab',{medium:'biological',evidenceType:'dna',locationId:null,sourceLocationId:lab.id,sourceAt:'2012-06-01T10:00:00.000Z',caseId:file.id,caseIds:[file.id],custodianId:detective.id,discoveredBy:[detective.id],strength:90,reliability:100,investigationOptions:[{id:optionId,method:'dna',minutes:30,costCents:750,outcome:'lead',summary:'Profile appears to match the suspect.',reliability:100,personIds:[suspect.id],creatorTruth:'accurate'}]});
 const s=state([lab,detective,suspect,agency,file,sample]),before=Date.parse(s.clock);act(s,detective.id,{type:'evidence-state',evidenceId:sample.id,operation:'contaminate',reason:'seal failed'});act(s,detective.id,{type:'analyze-evidence',caseId:file.id,evidenceId:sample.id,optionId});
 const evidence=data(sample,'evidence'),caseData=data(file,'case');assert.equal(Date.parse(s.clock)-before,35*60000);assert.equal(evidence.condition,'contaminated');assert.equal(evidence.contaminated,true);assert.equal(evidence.analyses[0]!.outcome,'ambiguity');assert.equal(evidence.analyses[0]!.contaminationWarning,true);assert.equal(caseData.leadRecords[0]!.kind,'ambiguity');assert.equal(caseData.hypotheses.length,0);assert.ok(caseData.evidenceScore>0);assert.equal(data(agency,'faction').treasuryCents,1250);assert.ok(evidence.history.some(row=>row.operation==='contaminated'));assert.ok(evidence.history.some(row=>row.operation==='analyzed'));validateState(s);
});

test('directional heat escalates and decays independently while Player Mode exposes only noticed signals',()=>{
 const north=make('location','North district',{category:'district'}),south=make('location','South district',{category:'district'}),player=make('character','Player',{playable:true,locationId:north.id},'owner'),police=make('faction','Police',{jurisdictionIds:[north.id]}),rivals=make('faction','Rival crew',{jurisdictionIds:[south.id]}),s=state([north,south,player,police,rivals]);
 const policeHeat=raiseHeat(s,{subjectId:player.id,watcherId:police.id,locationId:north.id,reason:'direct witness identified a plate',confidence:80,resources:80,eventId}),rivalHeat=raiseHeat(s,{subjectId:player.id,watcherId:rivals.id,locationId:south.id,reason:'street rumor',confidence:25,resources:10,eventId});assert.equal(policeHeat.status,'escalated');assert.notEqual(rivalHeat.status,'escalated');assert.equal(heatValue(s,player.id,police.id,north.id),80);assert.equal(heatValue(s,player.id,rivals.id,south.id),25);
 noticeHeatSignal(s,{subjectId:player.id,watcherId:police.id,locationId:north.id,kind:'tail',description:'The same unmarked sedan appears twice.',noticedByIds:[player.id]});const view=observerView(s,player.id),own=view.entities.find(entity=>entity.id===player.id)!;assert.equal(view.entities.some(entity=>entity.kind==='criminalHeat'),false);assert.equal('heat' in own.data,false);assert.deepEqual(own.data.attentionSignals,[{at:'2012-06-01T12:00:00.000Z',kind:'tail',description:'The same unmarked sedan appears twice.'}]);
 const before=heatValue(s,player.id,police.id,north.id);act(s,player.id,{type:'wait',minutes:7200});assert.ok(heatValue(s,player.id,police.id,north.id)<before);assert.equal(data(policeHeat.entity,'criminalHeat').status,'active');assert.equal(heatValue(s,player.id,rivals.id,south.id),0);validateState(s);
});
