import {test} from 'node:test';
import assert from 'node:assert/strict';
import {chromium,expect} from '@playwright/test';
import {AxeBuilder} from '@axe-core/playwright';
import {fixture,key,password} from './helpers.ts';
import {Game} from '../src/game/engine.ts';
import {validateEntity} from '../src/game/model.ts';
test('S02 browser: mobile writing settings persist; exact communication and preview work during AI outage',async()=>{
 const f=await fixture(),browser=await chromium.launch({headless:true});try{
  const game=new Game(f.store),t=await game.initialize(f.creator,f.campaign.id),room=validateEntity({id:key(),kind:'location',name:'Diner',visibility:'campaign',data:{}}),pc=validateEntity({id:key(),kind:'character',name:'Alex',visibility:'owner',data:{playable:true,controllerUserId:f.player.id,locationId:room.id}});await game.bulkEdit(f.creator,t.id,{revision:1,entities:[room,pc]},key());
  const address=await f.app.listen({host:'127.0.0.1',port:0});f.settings.origin=address;const context=await browser.newContext({viewport:{width:390,height:844}}),page=await context.newPage(),errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(address+'/app');await page.getByLabel('Email address').fill('player@example.test');await page.getByLabel('Password',{exact:true}).fill(password);await page.getByRole('button',{name:'Enter Valor'}).click();await page.getByRole('button',{name:'Load Life',exact:true}).click();await page.getByRole('button',{name:'Open lives',exact:true}).click();await page.getByRole('button',{name:'Open roster',exact:true}).click();await page.getByRole('button',{name:'Continue as Alex',exact:true}).click();await page.getByRole('heading',{name:'Chronicle',exact:true}).waitFor();await page.waitForFunction(()=>!document.querySelector('[aria-busy="true"]'));
  await page.getByRole('button',{name:'Switch to Game Mode',exact:true}).click();await page.getByRole('button',{name:'Open phone',exact:true}).click();await page.locator('[data-pocket-app="Settings"]').click();await page.getByRole('button',{name:/Writing preferences/}).click();await page.getByLabel('Perspective',{exact:true}).selectOption('first');await page.getByLabel('Tense',{exact:true}).selectOption('present');const revision=(await game.access(f.player,t.id)).t.revision;await page.getByRole('button',{name:'Save writing preferences',exact:true}).click();await page.getByText('Writing preferences saved for future turns.',{exact:true}).waitFor();assert.equal((await game.access(f.player,t.id)).t.revision,revision);assert.equal(await page.getByRole('button',{name:'Inspect latest narrative'}).count(),0);assert.equal(await page.locator('.pocket-content').evaluate(e=>e.scrollWidth<=e.clientWidth+1),true);await page.screenshot({path:'artifacts/system02-writing-mobile.png',fullPage:true});
  await page.getByRole('button',{name:'Put away ↘'}).click();await page.getByText('Say / Sign / Write',{exact:true}).click();await page.getByText('Auto-Phrase',{exact:true}).click();await page.getByRole('button',{name:'Preview wording',exact:true}).click();await expect(page.getByLabel('Exact words',{exact:true})).toHaveValue('Hello.');assert.equal((await game.access(f.player,t.id)).t.revision,revision);
  const words='I say EXACTLY this.\nDo not change my words.';await page.getByLabel('Exact words',{exact:true}).fill(words);await page.getByRole('button',{name:'Communicate',exact:true}).click();await page.waitForFunction(expected=>Array.from(document.querySelectorAll('.turn-narrative')).some(e=>e.textContent?.includes(expected)),words);assert.match((await page.locator('.turn-narrative').last().textContent())!,/I say/);assert.equal((await game.access(f.player,t.id)).t.revision,revision+1);assert.deepEqual(errors,[]);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);assert.deepEqual((await new AxeBuilder({page}).analyze()).violations.map(v=>v.id),[]);await page.screenshot({path:'artifacts/system02-communication-mobile.png',fullPage:true});
 }finally{await browser.close();await f.close();}
});
