import {test} from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {actionSchema,data,settingsSchema,validateEntity,validateState} from '../src/game/model.ts';
import type {Entity,State} from '../src/game/model.ts';
import {resolveAction} from '../src/game/actions.ts';
import {observerView} from '../src/game/epistemics.ts';
import {fixture,key} from './helpers.ts';
import {Game} from '../src/game/engine.ts';
import {defaultCampaignConfig} from '../src/campaign-config.ts';

const eventId='26262626-2626-4262-8262-262626262626',seed='26'.repeat(32);
const make=(kind:Entity['kind'],name:string,raw:Record<string,unknown>={},visibility:Entity['visibility']='campaign')=>validateEntity({id:randomUUID(),kind,name,visibility,data:raw});
const state=(entities:Entity[],settings:Record<string,unknown>={},clock='2012-06-01T12:00:00.000Z'):State=>({clock,settings:settingsSchema.parse({timezone:'America/New_York',...settings}),entities,facts:[],knowledge:[],beliefs:[],memories:[],eventIds:[]});
const act=(s:State,actorId:string,raw:unknown)=>resolveAction(s,actorId,actionSchema.parse(raw),eventId,seed);

test('card purchases conserve typed stock and account funds while issuing an immutable-style ledger and receipt',()=>{
 const place=make('location','Corner store'),player=make('character','Player',{playable:true,locationId:place.id,cash:100},'owner'),type=make('itemType','Canned soup',{category:'food',stackability:{mode:'stackable',maxStack:24}}),card=make('item','Debit card',{category:'card',ownerId:player.id,possessorId:player.id},'owner'),account=make('account','Checking',{ownerId:player.id,accountType:'checking',balanceCents:5000,accessMode:'both',cardItemIds:[card.id]},'owner'),shop=make('business','Market',{locationId:place.id,cash:1000,inventory:[{id:randomUUID(),itemTypeId:type.id,quantity:6,unitPriceCents:250}]});
 const s=state([place,player,type,card,account,shop]),stock=data(shop,'business').inventory[0]!;act(s,player.id,{type:'buy',businessId:shop.id,stockId:stock.id,quantity:2,payment:'card',accountId:account.id});
 assert.equal(data(account,'account').balanceCents,4500);assert.equal(data(shop,'business').cash,1500);assert.equal(data(shop,'business').inventory[0]!.quantity,4);const purchased=s.entities.find(entity=>entity.kind==='item'&&entity.data.typeId===type.id)!;assert.equal(data(purchased,'item').quantity,2);assert.equal(data(purchased,'item').ownerId,player.id);
 const transaction=s.entities.find(entity=>entity.kind==='transaction')!,receipt=s.entities.find(entity=>entity.kind==='receipt')!;assert.equal(data(transaction,'transaction').amountCents,500);assert.deepEqual(data(transaction,'transaction').itemIds,[purchased.id]);assert.deepEqual(data(receipt,'receipt').transactionIds,[transaction.id]);assert.equal(data(receipt,'receipt').lines[0]!.quantity,2);validateState(s);
});

test('stolen goods require an authored fence, local availability, trust, and acceptable heat',()=>{
 const place=make('location','Back room'),seller=make('character','Seller',{locationId:place.id,cash:0}),faction=make('faction','Local crew',{reputation:{}}),item=make('item','Marked watch',{ownerId:seller.id,possessorId:seller.id,stolen:true,price:1000}),fence=make('business','Fence',{locationId:place.id,cash:5000,category:'fence',contraband:true,factionId:faction.id,requiredTrust:10,heatLimit:20,heatPerTransaction:5,availableLocationIds:[place.id],sellerPolicy:{acceptsStolen:true}}),s=state([place,seller,faction,item,fence]);
 assert.throws(()=>act(s,seller.id,{type:'sell',businessId:fence.id,itemId:item.id}),/contraband_trust_required/);const factionData=data(faction,'faction');factionData.reputation[seller.id]=15;faction.data=factionData;act(s,seller.id,{type:'sell',businessId:fence.id,itemId:item.id});assert.equal(data(item,'item').ownerId,fence.id);assert.equal(data(seller,'character').heat[faction.id],5);assert.equal(data(seller,'character').cash,1000);
 const second=make('item','Hot camera',{ownerId:seller.id,possessorId:seller.id,stolen:true,price:1000});s.entities.push(second);const sellerData=data(seller,'character');sellerData.heat[faction.id]=21;seller.data=sellerData;assert.throws(()=>act(s,seller.id,{type:'sell',businessId:fence.id,itemId:second.id}),/contraband_heat_too_high/);validateState(s);
});

test('shift eligibility, attendance, wages, tips, advancement, absences, bills, and rent follow authored rules',()=>{
 const place=make('location','Diner'),worker=make('character','Worker',{playable:true,locationId:place.id,cash:5000,tags:['food-handler']}),employer=make('business','Diner',{locationId:place.id,cash:10000,category:'employer'}),job=make('job','Breakfast shift',{employerId:employer.id,employeeId:worker.id,locationId:place.id,hourlyCents:1200,minutesPerShift:60,eligibility:{requiredTags:['food-handler']},shift:{days:[5],startMinute:480,endMinute:540,graceMinutes:10},tipRule:{mode:'fixed',cents:200},advancement:{shiftsRequired:1,hourlyIncreaseCents:100,maxHourlyCents:1500}}),bill=make('bill','Electric bill',{creditorId:employer.id,debtorId:worker.id,category:'utility',amountCents:800,outstandingCents:800,dueAt:'2012-06-01T13:01:00.000Z',lateFeeCents:100},'owner'),home=make('housing','Apartment',{locationId:place.id,landlordId:employer.id,tenantId:worker.id,rentCents:2000,dueAt:'2012-06-01T13:01:00.000Z',periodDays:30},'owner'),s=state([place,worker,employer,job,bill,home]);
 act(s,worker.id,{type:'work',jobId:job.id});assert.equal(data(worker,'character').cash,6400);assert.equal(data(employer,'business').cash,8600);assert.equal(data(job,'job').attendance[0]!.status,'present');assert.equal(data(job,'job').completedShifts,1);assert.equal(data(job,'job').hourlyCents,1300);assert.deepEqual(s.entities.filter(entity=>entity.kind==='transaction').map(entity=>entity.data.category).sort(),['tip','wage']);
 act(s,worker.id,{type:'wait',minutes:1});assert.equal(data(bill,'bill').status,'overdue');assert.equal(data(bill,'bill').outstandingCents,900);assert.equal(data(home,'housing').status,'late');assert.equal(data(home,'housing').arrearsCents,2000);validateState(s);
});

test('a missed shift records one absence and disabled needs stay absent from mechanics and player UI',()=>{
 const place=make('location','Office'),worker=make('character','Worker',{playable:true,locationId:place.id,hunger:40,thirst:50,hygiene:60}),employer=make('business','Office',{locationId:place.id,cash:10000}),job=make('job','Morning shift',{employerId:employer.id,employeeId:worker.id,locationId:place.id,hourlyCents:1000,minutesPerShift:60,shift:{days:[5],startMinute:480,endMinute:540,graceMinutes:0},absencePolicy:{warningAfter:1,terminateAfter:2,description:'Call supervisor.'}}),s=state([place,worker,employer,job],{needs:true,campaign:{...defaultCampaignConfig('2012-06-01T12:00:00.000Z','America/New_York'),needsIntensity:'off',needsPolicy:{ui:'hidden',costs:'none',penalties:'none'}}},'2012-06-01T12:59:00.000Z');
 act(s,worker.id,{type:'wait',minutes:1});assert.equal(data(job,'job').attendance.length,1);assert.equal(data(job,'job').attendance[0]!.status,'absent');assert.equal(data(job,'job').status,'suspended');assert.deepEqual({hunger:data(worker,'character').hunger,thirst:data(worker,'character').thirst,hygiene:data(worker,'character').hygiene},{hunger:40,thirst:50,hygiene:60});const view=observerView(s,worker.id),projected=view.entities.find(entity=>entity.id===worker.id)!;assert.equal(view.settings.needs,false);assert.equal('hunger' in projected.data,false);assert.equal('thirst' in projected.data,false);assert.equal('hygiene' in projected.data,false);validateState(s);
});

test('persisted financial records reject Creator edits and direct database mutation',async()=>{
 const f=await fixture(),game=new Game(f.store);try{const timeline=await game.initialize(f.creator,f.campaign.id),place=make('location','Shop'),player=make('character','Player',{playable:true,controllerUserId:f.player.id,locationId:place.id,cash:2000},'owner'),shop=make('business','Shop',{locationId:place.id,cash:1000}),item=make('item','Book',{ownerId:shop.id,price:500}),shopData=data(shop,'business');shopData.stock.push(item.id);shop.data=shopData;await game.bulkEdit(f.creator,timeline.id,{revision:1,entities:[place,player,shop,item]},key());let revision=(await game.access(f.player,timeline.id)).t.revision;await game.turn(f.player,timeline.id,{revision,characterId:player.id,action:actionSchema.parse({type:'buy',businessId:shop.id,itemId:item.id})},key());const loaded=await game.load(timeline.id),transaction=loaded.entities.find(entity=>entity.kind==='transaction')!;revision=(await game.access(f.creator,timeline.id)).t.revision;const changed=structuredClone(transaction);changed.name='Rewritten ledger';await assert.rejects(()=>game.edit(f.creator,timeline.id,{revision,entity:changed},key()),/immutable_financial_record/);await assert.rejects(()=>f.store.run('UPDATE game_entities SET name=? WHERE timeline_id=? AND id=?','Rewritten',timeline.id,transaction.id),/immutable financial record/);}finally{await f.close();}
});
