import {test} from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID as uuid,createHash} from 'node:crypto';
import {performance} from 'node:perf_hooks';
import {settingsSchema,validateEntity,validateState,type State} from '../src/game/model.ts';
import {information,addProposition,acquireInformation,recordObservation,transmitInformation,exposeTransmission,addInformationRecord,researchInformation,authorInformation,informationProjection,informationHash,syncInformation} from '../src/game/information.ts';
import {authorSecret,revealSecretFacet,declassifyFacet,learnIdentity,learnSpatial,interpretObservation,authorKnowledgePackage,grantKnowledgePackage,copyInformationRecord,repairAcquisition,queryInformation,contextTiers,extendedDiagnostics,changeRecordAccess} from '../src/game/information-operations.ts';
import {buildInformationContext,rebuildInformationSummary,maintainInformationSummaries,contextStillCurrent} from '../src/game/information-context.ts';
import {observerView,locationBrowser,remember} from '../src/game/epistemics.ts';
import {Game,checksum} from '../src/game/engine.ts';
import {TurnKernel} from '../src/game/turn-kernel.ts';
import {fixture,key,login} from './helpers.ts';

const at='2012-06-01T12:00:00.000Z';
function setup(){const room=validateEntity({id:uuid(),kind:'location',name:'Diner',visibility:'campaign',data:{category:'room'}}),hidden=validateEntity({id:uuid(),kind:'location',name:'Private safehouse',visibility:'knowledge',data:{category:'room',discoverable:false}}),people=['Nathaniel','Verdell Wilson','Malik'].map((name,n)=>validateEntity({id:uuid(),kind:'character',name,visibility:'campaign',data:{playable:n===0,locationId:room.id}}));const s:State={clock:at,settings:settingsSchema.parse({contextTokens:8000}),entities:[room,hidden,...people],facts:[],knowledge:[],beliefs:[],memories:[]};information(s);return {s,room,hidden,pc:people[0]!,npc:people[1]!,other:people[2]!,scope:{campaignId:uuid(),timelineId:uuid(),viewerId:people[0]!.id,stateVersion:1,eventCursor:uuid(),sceneId:uuid(),profileVersion:2}};}
function prop(s:State,subjectId:string,text:string,predicate='claim',qualifiers={}){return addProposition(s,{id:uuid(),subjectId,predicate,value:text,qualifiers,validFrom:s.clock,truth:'unknown'});}
function learn(s:State,characterId:string,propositionId:string,text:string){const sourceId=uuid();return acquireInformation(s,{characterId,propositionId,text,type:'belief',confidence:0.6,acquisition:'testimony',sourceId,originIds:[sourceId],informationAt:s.clock,lastConfirmedAt:null,freshness:'current',secrecyAwareness:'unknown'});}
function record(s:State,propositionId:string,text:string,extra={}){return addInformationRecord(s,{id:uuid(),title:'Report',text,propositionIds:[propositionId],createdAt:s.clock,informationAt:s.clock,validUntil:null,scope:'private',allowedCharacterIds:[],requiredItemIds:[],requiredTags:[],locationId:null,supersedesId:null,sourceIds:[],...extra});}
function send(s:State,senderId:string,recipientId:string,propositionId:string,parentId:string|null=null){const t=transmitInformation(s,{id:uuid(),senderId,intendedRecipientIds:[recipientId],propositionIds:[propositionId],text:'Reported claim',channel:'rumor',at:s.clock,secrecy:false,parentId,originIds:[],mutation:'',artifactId:null,recipients:[]});exposeTransmission(s,t.id,recipientId,{delivered:true,exposed:true});return t;}

test('System 3 secret facets disclose independently and declassification changes availability only',()=>{const {s,pc,npc,other}=setup(),meeting=prop(s,npc.id,'Met Malik'),coercion=prop(s,npc.id,'COERCION_CANARY'),proof=learn(s,pc.id,meeting.id,'Saw a meeting');const secret=authorSecret(s,{id:uuid(),subjectId:npc.id,sensitivity:'restricted',authorizedCharacterIds:[npc.id],facets:[{id:uuid(),propositionId:meeting.id,requiredSourceIds:[proof.id],discoverabilityPaths:['witness'],leakConsequences:''},{id:uuid(),propositionId:coercion.id,requiredSourceIds:[],discoverabilityPaths:['sealed confession'],leakConsequences:''}]});revealSecretFacet(s,pc.id,secret.facets[0]!.id,uuid());assert.throws(()=>revealSecretFacet(s,pc.id,secret.facets[1]!.id,uuid()),/discovery_source_unavailable/);const r=record(s,coercion.id,'COERCION_CANARY',{sealed:true});declassifyFacet(s,secret.facets[1]!.id,uuid());assert.equal(r.scope,'public');assert.equal(r.sealed,false);assert.doesNotMatch(JSON.stringify(informationProjection(s,pc.id)),/COERCION_CANARY/);assert.equal(informationProjection(s,other.id).entries.length,0);researchInformation(s,other.id,'COERCION_CANARY');assert.match(JSON.stringify(informationProjection(s,other.id)),/COERCION_CANARY/);});

test('System 3 progressive identity, aliases and later interpretation preserve the raw observation',()=>{const {s,pc,npc,scope}=setup();npc.data.legalName='Verdell Wilson';npc.data.aliases=['Mr Wilson'];const p=prop(s,npc.id,'Introduced himself'),source=learn(s,pc.id,p.id,'Verdell Wilson introduced himself.');const observation=recordObservation(s,{id:uuid(),observerId:pc.id,eventId:uuid(),at,locationId:null,channel:'vision',targetId:npc.id,raw:'An unknown man entered.',clarity:0.7,confidence:0.7,attention:'focused',conditions:{},recognition:'unidentified',recognizedAsId:null,salience:0.8,propositionIds:[]}).observation;const raw=structuredClone(observation);const identity=learnIdentity(s,{id:uuid(),viewerId:pc.id,subjectId:npc.id,label:'Verdell',stage:'first-name',sourceId:source.id,at,previousId:null});assert.doesNotMatch(JSON.stringify(observerView(s,pc.id)),/Wilson/);assert.doesNotMatch(JSON.stringify(buildInformationContext(s,scope,'narration','Verdell').bundle),/Wilson/);interpretObservation(s,{id:uuid(),viewerId:pc.id,observationId:observation.id,recognizedAsId:npc.id,text:'Later identified as Verdell',confidence:0.9,sourceIds:[source.id],at,supersedesId:null});learnIdentity(s,{...identity,id:uuid(),label:'Verdell Wilson',stage:'full-name',previousId:identity.id});assert.deepEqual(observation,raw);assert.equal(observerView(s,pc.id).entities.find(e=>e.id===npc.id)!.name,'Verdell Wilson');assert.equal(information(s).interpretations.length,1);});

test('System 3 field-specific knowledge preserves stale employment without revealing unrelated fields',()=>{const {s,pc,npc}=setup();npc.data.profileVisibility={...npc.data.profileVisibility as object,employerOccupation:'knowledge',familyBackground:'knowledge'};npc.data.employerOccupation='Private new job';npc.data.familyBackground='HIDDEN_HISTORY';const p=prop(s,npc.id,'Old diner job','employerOccupation',{profileValue:'Waiter at diner'});learn(s,pc.id,p.id,'Works at diner');const view=observerView(s,pc.id).entities.find(e=>e.id===npc.id)!;assert.equal(view.data.employerOccupation,'Waiter at diner');assert.equal(view.data.familyBackground,undefined);assert.doesNotMatch(JSON.stringify(view),/Private new job|HIDDEN_HISTORY/);});

test('System 3 approximate spatial knowledge cannot expose an exact pin or hidden target',()=>{const {s,pc,hidden,room}=setup(),p=prop(s,hidden.id,'Somewhere in district'),source=learn(s,pc.id,p.id,'A safehouse is somewhere in the district.');learnSpatial(s,{id:uuid(),viewerId:pc.id,subjectId:hidden.id,precision:'area',areaId:room.id,locationId:null,label:'A safehouse somewhere in the district',sourceId:source.id,at});const markers=informationProjection(s,pc.id).locations;assert.equal(markers[0]!.locationId,null);assert.equal(locationBrowser(s,pc.id).locations.some(l=>l.id===hidden.id),false);assert.throws(()=>learnSpatial(s,{id:uuid(),viewerId:pc.id,subjectId:hidden.id,precision:'rumored',areaId:room.id,locationId:hidden.id,label:'Somewhere',sourceId:source.id,at}),/approximate_location_cannot_have_exact_pin/);});

test('System 3 recall respects conditions and archive access neither recalls nor mutates',()=>{const {s,pc,npc}=setup();remember(s,pc.id,'Friday promise',uuid(),0.8,{decayPerDay:0,recallConditions:{tags:['friday']}});remember(s,npc.id,'PRIVATE_NPC_MEMORY',uuid(),1);remember(s,pc.id,'Forgotten Friday secret',uuid(),0,{decayPerDay:0});const before=informationHash(s),normal=queryInformation(s,pc.id,'remember',''),cue=queryInformation(s,pc.id,'remember','Friday');assert.equal('memories' in normal?normal.memories?.length:0,0);assert.equal('memories' in cue?cue.memories?.length:0,1);assert.doesNotMatch(JSON.stringify(cue),/PRIVATE_NPC|Forgotten/);assert.equal(informationHash(s),before);});

test('System 3 external notes follow custody while independent copies survive carrier loss',()=>{const {s,pc,other}=setup(),phone=validateEntity({id:uuid(),kind:'item',name:'Phone',visibility:'owner',data:{category:'phone',ownerId:pc.id,possessorId:pc.id}});s.entities.push(phone);authorInformation(s,pc.id,{kind:'note',text:'Written plate 4K?19?',custodyItemId:phone.id},uuid());const original=information(s).records[0]!,copy=copyInformationRecord(s,pc.id,original.id,uuid());assert.equal(copy.custodyItemId,null);phone.data.possessorId=other.id;assert.equal(informationProjection(s,pc.id).records.some(r=>r.id===original.id),false);researchInformation(s,pc.id,'plate');assert.equal(informationProjection(s,pc.id).records[0]!.id,copy.id);assert.equal(informationProjection(s,other.id).records.length,0);researchInformation(s,other.id,'plate');assert.equal(informationProjection(s,other.id).records[0]!.id,original.id);});

test('System 3 authored background packages grant only listed claims with source provenance',()=>{const {s,pc,npc}=setup(),p=prop(s,npc.id,'Knows procedure'),hidden=prop(s,npc.id,'HIDDEN_ORDER');const pack=authorKnowledgePackage(s,{id:uuid(),name:'Training',category:'procedural',claims:[{propositionId:p.id,text:'Can file a report',confidence:0.95}]});grantKnowledgePackage(s,pc.id,pack.id,uuid());assert.equal(informationProjection(s,pc.id).entries[0]!.acquisition,'background');assert.ok(!informationProjection(s,pc.id).entries.some(e=>e.propositionId===hidden.id));assert.equal(information(s).sources[0]!.type,'background');});

test('System 3 circular rumors retain one ancestry and distinguish ordinary forwarding',()=>{const {s,pc,npc,other}=setup(),p=prop(s,npc.id,'Claim');learn(s,pc.id,p.id,'Claim');const a=send(s,pc.id,npc.id,p.id),b=send(s,npc.id,other.id,p.id,a.id);assert.equal(extendedDiagnostics(s).circularRumors.length,0);const c=send(s,other.id,pc.id,p.id,b.id);assert.deepEqual(extendedDiagnostics(s).circularRumors.map(r=>r.transmissionId),[c.id]);assert.deepEqual(c.originIds,a.originIds);});

test('System 3 repair quarantines forwarded acquisitions and summaries but preserves historical observations',()=>{const {s,pc,npc,scope}=setup(),p=prop(s,npc.id,'SECRET'),entry=learn(s,pc.id,p.id,'SECRET');send(s,pc.id,npc.id,p.id);const note=authorInformation(s,pc.id,{kind:'hypothesis',text:'Dependent theory',sourceIds:[entry.id]},uuid());rebuildInformationSummary(s,pc.id,'relationship',npc.id,[entry.id,note.id],scope.eventCursor);const downstream=uuid(),repair=repairAcquisition(s,entry.id,'Invalid acquisition',uuid(),[downstream]);assert.equal(informationProjection(s,pc.id).entries.length,0);assert.equal(informationProjection(s,npc.id).entries.length,0);assert.equal(information(s).summaries.length,0);assert.equal(informationProjection(s,pc.id).active.length,0);assert.deepEqual(repair.committedEventIds,[downstream]);assert.equal(repairAcquisition(s,entry.id,'Retry',uuid()).id,repair.id);assert.equal(information(s).transmissions.length,1);});

test('System 3 scene and profile changes invalidate snapshots, required dialogue survives optional trimming',()=>{const {s,scope}=setup(),important={id:uuid(),text:'Where is Malik?',sceneId:scope.sceneId,required:true},context=buildInformationContext(s,scope,'dialogue','',{recentDialogue:[important,...Array.from({length:8},()=>({id:uuid(),text:'Coffee please',sceneId:scope.sceneId}))],tokenBudget:5000});assert.ok(context.bundle.sections.some(s=>s.id===important.id));assert.equal(contextStillCurrent(context,{...scope,sceneId:uuid()}),false);assert.equal(contextStillCurrent(context,{...scope,profileVersion:3}),false);assert.equal(buildInformationContext(s,scope,'dialogue','',{tokenBudget:256}).manifest.required_sources_complete,false);assert.ok(Object.isFrozen(context.bundle.sections));});

test('System 3 malformed identity, secret and propagation references fail validation',()=>{const {s,pc,npc}=setup(),p=prop(s,npc.id,'Claim'),source=learn(s,pc.id,p.id,'Claim'),t=send(s,pc.id,npc.id,p.id);t.parentId=t.id;assert.throws(()=>validateState(s),/information_transmission_cycle/);t.parentId=null;information(s).identities.push({id:uuid(),viewerId:pc.id,subjectId:uuid(),label:'Bad reference',stage:'unknown',sourceId:source.id,at,previousId:null});assert.throws(()=>validateState(s),/invalid_identity_reference/);});

test('System 3 context tiers preserve dormant history and recover active scene state after six months',()=>{const {s,pc,npc,hidden,room}=setup();npc.data.locationId=hidden.id;npc.data.simulationTier='distant';npc.data.plans=[];npc.data.schedule=[];remember(s,npc.id,'Unresolved commitment',uuid(),1,{decayPerDay:0});const original=structuredClone(npc),memory=structuredClone(s.memories[0]);assert.equal(contextTiers(s,pc.id).find(r=>r.characterId===npc.id)!.tier,0);s.clock='2012-12-01T12:00:00.000Z';npc.data.locationId=room.id;assert.equal(contextTiers(s,pc.id).find(r=>r.characterId===npc.id)!.tier,3);assert.equal(npc.name,original.name);assert.deepEqual(s.memories[0],memory);});

test('System 3 50,000-event retrieval finds relevant history within a fixed prompt budget',()=>{const {s,pc,npc,scope}=setup();for(let n=0;n<50000;n++){const eventId=uuid();(s.eventIds??=[]).push(eventId);s.memories.push({id:uuid(),observerId:n%2?pc.id:npc.id,text:'Unrelated routine '+n,salience:0.1,decayPerDay:0,eventId,at,private:true});}remember(s,pc.id,'Malik and Nia promised to meet Friday at the diner.',uuid(),1,{decayPerDay:0});const started=performance.now(),context=buildInformationContext(s,scope,'recap','Malik Nia Friday',{tokenBudget:8000}),elapsed=performance.now()-started;assert.match(JSON.stringify(context.bundle),/promised to meet Friday/);assert.ok(context.manifest.finalEstimatedTokens<=8000);assert.ok(elapsed<5000);console.log(JSON.stringify({system03LargeHistory:{canonicalEventReferences:s.eventIds!.length,elapsedMs:Math.round(elapsed),estimatedInputTokens:context.manifest.finalEstimatedTokens,providerCalls:0,providerCost:0}}));});

test('System 3 query, View As, replay and repair APIs preserve revision and enforce role and timeline isolation',async()=>{const f=await fixture(),game=new Game(f.store);try{const t=await game.initialize(f.creator,f.campaign.id),{s,pc,npc,scope}=setup();pc.data.controllerUserId=f.player.id;await game.bulkEdit(f.creator,t.id,{revision:1,entities:s.entities},key());let entryId='';await game.mutate(f.creator,t.id,2,key(),{},'creator.information',true,(state)=>{const p=prop(state,npc.id,'Knowledge');entryId=learn(state,pc.id,p.id,'A reported claim').id;return {result:{}};});const base='/game/timelines/'+t.id+'/information',player=await login(f,'player@example.test'),creator=await login(f),headers=(who:typeof creator)=>({cookie:who.cookie,origin:f.settings.origin,'x-csrf-token':who.csrf,'idempotency-key':key()});assert.equal((await f.app.inject({method:'GET',url:base+'/inspect?characterId='+pc.id,headers:headers(player)})).statusCode,403);const before=await game.load(t.id),hash=informationHash(before);for(const endpoint of ['/query?characterId='+pc.id+'&kind=know','/inspect?characterId='+npc.id]){const r=await f.app.inject({method:'GET',url:base+endpoint,headers:headers(endpoint.startsWith('/query')?player:creator)});assert.equal(r.statusCode,200,r.body);}assert.equal(informationHash(await game.load(t.id)),hash);const context=buildInformationContext(before,{...scope,campaignId:f.campaign.id,timelineId:t.id},'recap','claim');await f.store.run('INSERT INTO information_context_manifests VALUES (?,?,?,?,?,?,?,?)',context.manifest.callId,t.id,pc.id,'recap',3,scope.eventCursor,JSON.stringify(context),at);const replay=await f.app.inject({method:'POST',url:base+'/replay',headers:headers(creator),payload:{callId:context.manifest.callId}});assert.equal(replay.statusCode,200,replay.body);assert.equal(replay.json().manifest.noncanonical,true);const absent=await f.app.inject({method:'POST',url:base+'/replay',headers:headers(creator),payload:{callId:uuid()}});assert.equal(absent.statusCode,404);const kernel=new TurnKernel(game),query=await kernel.execute(f.player,{commandId:key(),sessionId:t.id,actorId:pc.id,expectedRevision:3,mode:'STORY',input:{kind:'freeform',text:'What does Nathaniel know about claim?'}});assert.equal(query.status,'PRESENTED');assert.equal(query.revision,3);assert.equal((await game.load(t.id)).clock,before.clock);const repair=await f.app.inject({method:'POST',url:base+'/operations',headers:headers(creator),payload:{revision:3,command:{operation:'repair',entryId,reason:'Invalid source'}}});assert.equal(repair.statusCode,200,repair.body);assert.equal(informationProjection(await game.load(t.id),pc.id).entries.length,0);}finally{await f.close();}});

test('System 3 repaired legacy knowledge remains quarantined after persistence and bridge backfill',async()=>{const f=await fixture(),game=new Game(f.store);try{const t=await game.initialize(f.creator,f.campaign.id),{s,pc,hidden}=setup(),id=uuid();s.facts.push({id,subjectId:hidden.id,predicate:'address',value:'HIDDEN_ADDRESS',eventId:uuid(),at,retiredAt:null});s.knowledge.push({observerId:pc.id,factId:id,source:'invalid-grant',at});syncInformation(s);const entry=information(s).entries[0]!;await game.persist(t.id,s);repairAcquisition(s,entry.id,'Repair corrupt grant',uuid());await game.persist(t.id,s);const loaded=await game.load(t.id);syncInformation(loaded);assert.doesNotMatch(JSON.stringify(observerView(loaded,pc.id)),/HIDDEN_ADDRESS/);assert.equal(informationProjection(loaded,pc.id).entries.length,0);assert.equal(information(loaded).repairs.length,1);assert.equal(information(loaded).sources.length,1);}finally{await f.close();}});

test('System 3 briefing attendance, independent witnesses and rumor mutation remain separate',()=>{const {s,pc,npc,other}=setup(),p=prop(s,npc.id,'questioned','police-status'),q=prop(s,npc.id,'arrested','police-status');learn(s,npc.id,p.id,'Police questioned him.');const briefing=transmitInformation(s,{id:uuid(),senderId:npc.id,intendedRecipientIds:[pc.id,other.id],propositionIds:[p.id],text:'Police questioned him.',channel:'briefing',at,secrecy:false,parentId:null,originIds:[],mutation:'',artifactId:null,recipients:[]});exposeTransmission(s,briefing.id,pc.id,{delivered:true,exposed:true});exposeTransmission(s,briefing.id,other.id,{delivered:true});assert.equal(informationProjection(s,other.id).entries.length,0);learn(s,pc.id,q.id,'I believe he was arrested.');const rumor=transmitInformation(s,{id:uuid(),senderId:pc.id,intendedRecipientIds:[other.id],propositionIds:[q.id],text:'He was arrested.',channel:'rumor',at,secrecy:false,parentId:briefing.id,originIds:[],mutation:'questioned became arrested',artifactId:null,recipients:[]});assert.deepEqual(rumor.originIds,briefing.originIds);assert.equal(p.value,'questioned');const witnessA=learn(s,pc.id,p.id,'Unrelated witness A'),witnessB=learn(s,pc.id,p.id,'Unrelated witness B');assert.notEqual(witnessA.originIds[0],witnessB.originIds[0]);});

test('System 3 mistaken identification is corrected separately from immutable observation and belief history',()=>{const {s,pc,npc,other}=setup(),p=prop(s,npc.id,'Seen'),source=learn(s,pc.id,p.id,'The witness thought it was Malik.'),o=recordObservation(s,{id:uuid(),observerId:pc.id,eventId:uuid(),at,locationId:null,channel:'vision',targetId:npc.id,raw:'A figure in a dark coat.',clarity:0.4,confidence:0.4,attention:'normal',conditions:{},recognition:'likely',recognizedAsId:other.id,salience:0.7,propositionIds:[]}).observation;const first=interpretObservation(s,{id:uuid(),observationId:o.id,viewerId:pc.id,recognizedAsId:other.id,text:'Possibly Malik',confidence:0.4,sourceIds:[source.id],at,supersedesId:null});interpretObservation(s,{...first,id:uuid(),recognizedAsId:npc.id,text:'Correction: it was Verdell',confidence:0.9,supersedesId:first.id});assert.equal(o.recognizedAsId,other.id);assert.equal(information(s).interpretations.length,2);assert.match(source.text,/thought it was Malik/);});

test('System 3 incremental summary hierarchy rebuilds equivalent facts and excludes forgotten cue-bound memories',()=>{const {s,pc,npc,scope}=setup(),p=prop(s,npc.id,'Might be at diner');learn(s,pc.id,p.id,'A witness said Verdell might be at the diner.');remember(s,pc.id,'CUE_BOUND_CANARY',uuid(),1,{recallConditions:{tags:['specialcue']}});const summaries=maintainInformationSummaries(s,pc.id,scope.eventCursor),texts=summaries.map(row=>[row.level,row.text]);assert.ok(summaries.some(row=>row.level==='relationship'));assert.ok(summaries.some(row=>row.level==='period'));assert.doesNotMatch(JSON.stringify(summaries),/CUE_BOUND_CANARY/);assert.ok(summaries.every(row=>row.text.includes('might')));information(s).summaries=[];assert.deepEqual(maintainInformationSummaries(s,pc.id,scope.eventCursor).map(row=>[row.level,row.text]),texts);});

test('System 3 explicit faction access grants availability while unread contents remain unknown',()=>{const {s,pc,npc}=setup(),faction=validateEntity({id:uuid(),kind:'faction',name:'Agency',visibility:'campaign',data:{}});s.entities.push(faction);pc.data.factionIds=[faction.id];const p=prop(s,npc.id,'Case address'),r=record(s,p.id,'Agency case address',{scope:'faction',audienceFactionIds:[faction.id]});assert.equal(informationProjection(s,pc.id).entries.length,0);assert.equal(informationProjection(s,pc.id).records.length,0);researchInformation(s,pc.id,'Agency case');assert.equal(informationProjection(s,pc.id).entries.length,1);changeRecordAccess(s,r.id,{sealed:true},uuid());assert.throws(()=>copyInformationRecord(s,pc.id,r.id,uuid()),/information_unavailable/);assert.equal(informationProjection(s,pc.id).records.length,0);assert.equal(informationProjection(s,pc.id).entries.length,1);});

test('System 3 scaling preserves the existing checksum contract and never caches mutable values',()=>{const old=(v:unknown):string=>Array.isArray(v)?'['+v.map(old).join(',')+']':v&&typeof v==='object'?'{'+Object.entries(v).sort(([a],[b])=>a.localeCompare(b)).map(([k,x])=>JSON.stringify(k)+':'+old(x)).join(',')+'}':JSON.stringify(v);const source={z:[1,null,{é:'accent',a:true}],a:{'1':undefined,'x:y':'quote"',empty:[]},state:1};for(let n=0;n<100;n++){source.state=n;assert.equal(checksum(source),createHash('sha256').update(old(source)).digest('hex'));}const before=checksum(source);source.z.push(7);assert.notEqual(checksum(source),before);});
